<section class="content" style="margin-left: 9px; margin-right: 9px; padding-top: 75px;">
    <div class="container-fluid">
        <div class="row">
            <div class="col-6">
                <div class="small-box bg-success" onclick="openModule('compras')" style="cursor: pointer;">
                    <div class="inner text-white">
                        <p>Total de Compras <br>Realizadas</p>
                        <h3>
                            R$ <?php echo number_format($this->view->total_purchases, 2, ",", "."); ?>
                        </h3>
                    </div>
                    <div class="icon">
                        <i class="fas fa-shopping-cart text-white"></i>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="small-box bg-success" onclick="openModule('pagamentos')" style="cursor: pointer;">
                    <div class="inner text-white">
                        <p>Total de Pagamentos <br>Realizados</p>
                        <h3>
                            R$ <?php echo number_format($this->view->total_expenses, 2, ",","."); ?>
                        </h3>
                    </div>
                    <div class="icon">
                        <i class="fas fa-dollar-sign text-white"></i>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="small-box bg-purple" onclick="openModule('orcamentos')" style="cursor: pointer;">
                    <div class="inner text-white">
                        <p>Orçamentos <br>Pendentes</p>
                        <h3>
                            <?php echo $this->view->total_pending_budgets; ?>
                        </h3>
                    </div>
                    <div class="icon">
                        <i class="fas fa-file text-white"></i>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="small-box bg-purple" onclick="openModule('os')" style="cursor: pointer;">
                    <div class="inner text-white">
                        <p>Ordens de Serviço <br>Pendentes</p>
                        <h3>
                            <?php echo $this->view->total_pending_os; ?>
                        </h3>
                    </div>
                    <div class="icon">
                        <i class="fas fa-file-invoice-dollar text-white"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>