<?php
$data = $this->view->data;

$isAdmin = $_SESSION['ROLE_ADM'] == '1';
$role = $_SESSION['ROLE'];

$canView = $isAdmin || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('payment-types'));
$canCreate = $isAdmin || $this->acl($role, $this->resourceCodes('create'), $this->moduleCodes('payment-types'));
$canUpdate = $isAdmin || $this->acl($role, $this->resourceCodes('update'), $this->moduleCodes('payment-types'));
$canDelete = $isAdmin || $this->acl($role, $this->resourceCodes('delete'), $this->moduleCodes('payment-types'));
?>
<?php if ($canView): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row">
                <div class="col-11">
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-th-list pr-1"></i>
                        Formas de Pagamento
                    </h1>
                </div>
                <div class="col-1">
                    <?php if ($canCreate): ?>
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item">
                                <button type="button" class="btn btn-outline-success" onclick="createTable();"
                                    style="width: 100%;" title="Adicionar Forma de Pagamento">
                                    <i class="fas fa-plus"></i>
                                </button>
                            </li>
                        </ol>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover" id="table_pt" style="width: 100%;">
                                    <thead>
                                        <tr class="text-center" style="height: 30px;">
                                            <th style="font-size: 14px;">Forma de Pagamento</th>
                                            <th style="font-size: 14px;">Situação</th>
                                            <th style="display: none;">Situação</th>
                                            <th style="display: none;">Cadastrado em</th>
                                            <th style="display: none;">Atualizado em</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($data as $entity): ?>
                                            <tr class="text-center" style="cursor: pointer;"
                                                onclick="openDetails('<?php echo $entity['uuid']; ?>');">
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['name']; ?>
                                                </td>
                                                <td style="width: 80px;">
                                                    <?php if ($entity['status'] == '1'): ?>
                                                        <i class="fa fa-circle pr-1" style="color: green;"></i>
                                                    <?php else: ?>
                                                        <i class="fa fa-circle pr-1" style="color: red;"></i>
                                                    <?php endif; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo ($entity['status'] == '1') ? 'Ativa' : 'Inativa'; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $this->formatDateTime($entity['created_at']); ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $this->formatDateTime($entity['updated_at']); ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script type="text/javascript">
        $(document).ready(function () {
            let buttonCommon = {
                exportOptions: {
                    format: {
                        body: function (data) {
                            return data;
                        }
                    }
                }
            };

            $('#table_pt').DataTable({
                "sDom": 'flBtip',
                searching: true,
                buttons: [
                    $.extend(true, {}, buttonCommon, {
                        extend: 'excel',
                        title: 'Formas de Pagamento',
                        exportOptions: { columns: [0, 2, 3, 4] }
                    })
                ],
                order: [[0, "asc"]],
                columnDefs: [{ orderable: false, targets: [1] }],
                responsive: true,
                info: true,
                processing: true,
                scrollCollapse: true,
                paging: true,
                "pageLength": 25,
                "language": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ &nbsp;",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Filtrar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
        });

        function openDetails(uuid) {
            $("#baseLoader").show();
            $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>formas-pagamento/detalhes",
                data: { uuid: uuid },
                async: true
            }).done(function (data) {
                $("#sis_content").html(data);
                $("#baseLoader").hide();
            }).fail(function () {
                showInternalErrorAlert();
                $("#baseLoader").hide();
            });
        }
    </script>
    <?php if ($canCreate): ?>
        <script>
            function createTable() {
                $("#baseLoader").show();
                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>formas-pagamento/cadastrar",
                    async: true
                }).done(function (data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").hide();
                }).fail(function () {
                    showInternalErrorAlert();
                    $("#baseLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canUpdate): ?>
        <script>
            function updateTable(uuid) {
                $("#baseLoader").show();
                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>formas-pagamento/editar",
                    data: { uuid: uuid },
                    async: true
                }).done(function (data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").hide();
                }).fail(function () {
                    showInternalErrorAlert();
                    $("#baseLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canDelete): ?>
        <script>
            function deleteTable(uuid) {
                $("#modalXL").modal('hide');
                $("#modalDeleteTitle").html('<i class="fa fa-trash pr-2"></i> Excluir Forma de Pagamento');
                $("#modalDeleteLoader").hide();
                $("#modalDelete").modal('show');
                $("#modalDeleteResult").html('<button type="button" class="btn btn-danger" title="Confirmar Exclusão" onclick="runDelete(\'' + uuid + '\');"><i class="fa fa-trash"></i> CONFIRMAR E EXCLUIR</button>');
            }

            function runDelete(uuid) {
                if (uuid !== null) {
                    $("#modalDeleteLoader").show();

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>formas-pagamento/excluir",
                        data: { uuid: uuid },
                        dataType: 'json',
                        async: true
                    }).done(function (data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#modalDelete").modal('hide');
                        $("#modalXL").modal('hide');
                        openModule('formas-pagamento');
                    }).fail(function () {
                        showInternalErrorAlert();
                        $("#modalDeleteLoader").hide();
                    });
                }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>