<?php
$entity = $this->view->entity;
$role = $_SESSION['ROLE'];
?>
<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($role, $this->resourceCodes('update'), $this->moduleCodes('payment-types'))): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row">
                <div class="col-11">
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-pen-square pr-1"></i>
                        Forma de Pagamento
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Formas de Pagamento"
                                onclick="openDetails('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i>
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formUpdateTable" id="formUpdateTable" enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="name">Situação*</label>
                                            <select name="status" id="status_1" class="form-control">
                                                <option value="1" <?php echo ($entity['status'] == '1' ? 'selected' : ''); ?>>
                                                    Ativa no sistema</option>
                                                <option value="0" <?php echo ($entity['status'] == '0' ? 'selected' : ''); ?>>
                                                    Inativa no Sistema</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12"><hr></div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="name">Nome*</label>
                                            <input type="text" class="form-control" name="name" id="name" required
                                                value="<?php echo $entity['name']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="row">
                                            <input type="hidden" name="uuid" id="uuid_pgto"
                                                value="<?php echo $entity['uuid']; ?>">
                                            <div class="col-md-8 mt-2 mb-2">
                                                <button type="submit" class="btn btn-success w-100" id="btnSubmit"
                                                    title="Salvar Forma de Pagamento">
                                                    <i class="fa fa-save pr-1"></i> Salvar
                                                </button>
                                            </div>
                                            <div class="col-md-4 mt-2 mb-2">
                                                <button type="button" class="btn btn-outline-primary w-100"
                                                    onclick="openDetails('<?php echo $entity['uuid']; ?>');"
                                                    title="Voltar para Formas de Pagamento">
                                                    <i class="fas fa-arrow-left pr-1"></i> Voltar
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function () {
            $('#formUpdateTable').validate({
                rules: {
                    name: {
                        remote: {
                            type: "post",
                            url: "<?php echo baseUrl; ?>formas-pagamento/valor-existente",
                            data: { uuid: '<?php echo $_POST['uuid']; ?>' }
                        }
                    },
                },
                messages: {
                    name: {
                        remote: "Forma de Pagamento já cadastrada"
                    },
                },
                submitHandler: function () {
                    let form_data = new FormData();

                    form_data.append('name', $("#name").val());
                    form_data.append('status', $("#status_1").val());
                    form_data.append('uuid', $("#uuid_pgto").val());
                    form_data.append('target', '<?php echo $this->getTarget(); ?>');

                    $("#baseLoader").show();
                    $("#btnSubmit").attr('disabled', true);

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>formas-pagamento/processa-edicao",
                        cache: false,
                        contentType: false,
                        processData: false,
                        data: form_data,
                        dataType: 'json',
                        async: true
                    }).done(function (data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        if (data.type === 'success') {
                            openDetails('<?php echo $entity['uuid']; ?>');
                        } else {
                            $("#baseLoader").hide();
                            $("#btnSubmit").attr('disabled', false);
                        }
                    }).fail(function () {
                        showInternalErrorAlert();
                        $("#baseLoader").hide();
                        $("#btnSubmit").attr('disabled', false);
                    });

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>