<?php
$config = $this->getSiteConfig();
$isAdmin = $this->isAdmin();

$canViewUsers = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('user'));
$canViewConfigs = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('configs'));
$canViewLogs = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('logs'));
$canViewCustomers = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('customers'));
$canViewPayments = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('payment-types'));
$canViewServices = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('services'));
$canViewItems = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('items'));
$canViewCategories = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('categories'));
$canViewExpenses = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('expenses'));
$canViewFinancial = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('financial'));
$canViewReports = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('reports'));
$canViewSchedules = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('schedules'));

$config['logo'] = $this->isImage($config['logo'], 'logo') ? $config['logo'] : 'jaconsultoriati.png';
$config['logo_icon'] = $this->isImage($config['logo_icon'], 'logo') ? $config['logo_icon'] : 'jaconsultoriati.png';
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        <?php echo $config['site_title']; ?>
    </title>
    <meta author="João Augusto Bonfante">
    <link rel="icon" href="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo_icon']; ?>"
        type="image/x-icon" />
    <meta name="robots" content="noindex">
    <meta name="googlebot" content="noindex">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet"
        href="<?php echo baseUrl; ?>public/app/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/dist/css/adminlte.css">
    <link rel="stylesheet"
        href="<?php echo baseUrl; ?>public/app/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <link href="<?php echo baseUrl; ?>public/app/css/buttons.dataTables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/css/dataTables.bootstrap4.min.css">
    <script src="<?php echo baseUrl; ?>public/app/plugins/jquery/jquery.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/plugins/jquery-ui/jquery-ui.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script
        src="<?php echo baseUrl; ?>public/app/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/dist/js/adminlte.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/jquery.maskMoney.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/jquery.maskedinput.js" type="text/javascript"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/jquery.validate.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/jquery.inputmask.js"></script>
    <link rel="stylesheet"
        href="<?php echo baseUrl; ?>public/app/plugins/jquery-toast-plugin/dist/jquery.toast.min.css">
    <script src="<?php echo baseUrl; ?>public/app/plugins/jquery-toast-plugin/dist/jquery.toast.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/alerts.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/jquery.dataTables.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/dataTables.bootstrap4.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/date-eu.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/date-eu-com-filtro.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/dataTables.valoremreais.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/dataTables.buttons.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/jszip.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/pdfmake.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/vfs_fonts.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/buttons.html5.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/buttons.print.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo baseUrl; ?>public/app/plugins/select2/css/select2.min.css">
    <script src="<?php echo baseUrl; ?>public/app/plugins/select2/js/select2.min.js"></script>
    <link href="<?php echo baseUrl; ?>public/lightbox2/src/css/lightbox.css" rel="stylesheet" />
    <script src="<?php echo baseUrl; ?>public/lightbox2/src/js/lightbox.js"></script>
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <style>
        h1 {
            color:
                <?php echo $config['primary_color']; ?>
                !important;
        }

        .bg-primary {
            background:
                <?php echo $config['primary_color']; ?>
                !important;
        }

        .bg-primary:hover {
            background:
                <?php echo $config['secondary_color']; ?>
                !important;
        }

        .bg-secondary {
            background:
                <?php echo $config['secondary_color']; ?>
                !important;
        }

        .bg-secondary:hover {
            background:
                <?php echo $config['primary_color']; ?>
                !important;
        }

        .btn-primary {
            background:
                <?php echo $config['primary_color']; ?>
                !important;
        }

        .btn-primary:hover {
            background:
                <?php echo $config['secondary_color']; ?>
                !important;
        }

        .btn-secondary {
            background:
                <?php echo $config['secondary_color']; ?>
                !important;
        }

        .btn-secondary:hover {
            background:
                <?php echo $config['primary_color']; ?>
                !important;
        }

        .page-link:hover {
            z-index: 2;
            color: #fff;
            text-decoration: none;
            background-color:
                <?php echo $config['secondary_color']; ?>
            ;
            border-color:
                <?php echo $config['secondary_color']; ?>
            ;
        }


        .page-item.active .page-link {
            z-index: 3;
            color: #fff;
            background-color:
                <?php echo $config['primary_color']; ?>
                !important;
            ;
            border-color:
                <?php echo $config['primary_color']; ?>
                !important;
            ;
        }


        .btn-outline-primary {
            color:
                <?php echo $config['primary_color']; ?>
            ;
            border-color:
                <?php echo $config['primary_color']; ?>
            ;
        }

        .btn-outline-primary:hover {
            color: #fff;
            background-color:
                <?php echo $config['primary_color']; ?>
            ;
            border-color:
                <?php echo $config['primary_color']; ?>
            ;
        }

        .btn-outline-primary.disabled,
        .btn-outline-primary:disabled {
            color:
                <?php echo $config['primary_color']; ?>
            ;
            background-color: transparent;
        }

        .btn-outline-primary:not(:disabled):not(.disabled):active,
        .btn-outline-primary:not(:disabled):not(.disabled).active,
        .show>.btn-outline-primary.dropdown-toggle {
            color: #fff;
            background-color:
                <?php echo $config['primary_color']; ?>
            ;
            border-color:
                <?php echo $config['primary_color']; ?>
            ;
        }

        .btn-outline-secondary {
            color:
                <?php echo $config['secondary_color']; ?>
            ;
            border-color:
                <?php echo $config['secondary_color']; ?>
            ;
        }

        .btn-outline-secondary:hover {
            color: #fff;
            background-color:
                <?php echo $config['secondary_color']; ?>
            ;
            border-color:
                <?php echo $config['secondary_color']; ?>
            ;
        }

        .btn-outline-secondary.disabled,
        .btn-outline-secondary:disabled {
            color:
                <?php echo $config['secondary_color']; ?>
            ;
            background-color: transparent;
        }

        .btn-outline-secondary:not(:disabled):not(.disabled):active,
        .btn-outline-secondary:not(:disabled):not(.disabled).active,
        .show>.btn-outline-secondary.dropdown-toggle {
            color: #fff;
            background-color:
                <?php echo $config['secondary_color']; ?>
            ;
            border-color:
                <?php echo $config['secondary_color']; ?>
            ;
        }

        .bg-gradient-primary {
            background:
                <?php echo $config['secondary_color']; ?>
                linear-gradient(180deg,
                    <?php echo $config['primary_color']; ?>
                    ,
                    <?php echo $config['secondary_color']; ?>
                ) repeat-x !important;
            color: #fff;
        }

        .bg-gradient-primary.btn.disabled,
        .bg-gradient-primary.btn:disabled,
        .bg-gradient-primary.btn:not(:disabled):not(.disabled):active,
        .bg-gradient-primary.btn:not(:disabled):not(.disabled).active,
        .show>.bg-gradient-primary.btn.dropdown-toggle {
            background-image: none !important;
        }

        .bg-gradient-primary.btn:hover {
            background:
                <?php echo $config['secondary_color']; ?>
                linear-gradient(180deg,
                    <?php echo $config['primary_color']; ?>
                    , #666666) repeat-x !important;
            border-color:
                <?php echo $config['secondary_color']; ?>
            ;
            color: #ececec;
        }

        .bg-gradient-primary.btn:not(:disabled):not(.disabled):active,
        .bg-gradient-primary.btn:not(:disabled):not(.disabled).active,
        .bg-gradient-primary.btn:active,
        .bg-gradient-primary.btn.active {
            background:
                <?php echo $config['secondary_color']; ?>
                linear-gradient(180deg,
                    <?php echo $config['primary_color']; ?>
                    ,
                    <?php echo $config['secondary_color']; ?>
                ) repeat-x !important;
            border-color:
                <?php echo $config['secondary_color']; ?>
            ;
            color: #fff;
        }

        @media print {
            body * {
                visibility: hidden;
            }
            #printable, #printable * {
                visibility: visible;
            }
            #printable {
                position: fixed;
                left: 0;
                top: 0;
            }

            .newPrintable, .newPrintable * {
                visibility: visible;
            }
            .newPrintable {
                position: fixed;
                left: 0;
                top: 0;
            }
        }

        .cPointer {
            cursor: pointer;
        }

        .badge-primary {
            background:
                <?php echo $config['primary_color']; ?>
                !important;
        }

        .btnRadius {
            border-radius: 20px !important;
        }

        .btnRadiusLg {
            border-radius: 30px !important;
        }

        .cardWrapper {
            padding: 10px 15px 10px 15px;
        }

        .cardWrapperList {
            padding: 25px 15px 20px 15px;
        }

        .cardWrapperBody {
            padding: 18px 15px 15px 15px;
        }

        .cardWrapperDetails {
            padding: 3px 10px 10px 10px;
        }

        .cardBox {
            padding: 12px 0 0 0;
            color: white;
        }

        .cardLine {
            margin-top: 0;
        }

        .inputUpload {
            height: 43px !important;
        }
    </style>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo_icon']; ?>"
                alt="<?php echo $config['site_title']; ?>" height="200">
        </div>
        <nav class="main-header navbar navbar-expand navbar-white navbar-light fixed-top">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item">
                    <a href="<?php echo baseUrl; ?>" class="nav-link cPointer">
                        Início
                    </a>
                </li>
                <li class="nav-item">
                    <a onclick="openModule('chamados');" class="nav-link cPointer">
                        Chamados
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <div id="messages_box"></div>
                </li>
                <li class="nav-item dropdown">
                    <div id="notifications_box"></div>
                </li>
                <li class="nav-item">
                    <a onclick="setLogout();" class="nav-link cPointer">
                        <i class="fa fa-sign-out-alt"></i> 
                    </a>
                </li>
            </ul>
        </nav>
        <?php
        if (!empty($config['file_menu']) && $this->isImage($config['file_menu'], 'menu')):
            $imageUrl = baseUrl . 'public/uploads/menu/' . $config['file_menu'];
            $bgStyle = "background-image: url('$imageUrl'); background-size: cover;";
        else:
            $bgStyle = 'background-color:' . $config['primary_color'];
        endif;
        ?>
        <aside class="main-sidebar sidebar-dark-primary elevation-4 text-center"
            style="<?php echo $bgStyle; ?> !important;">
            <div class="bg-white">
                <a href="<?php echo baseUrl; ?>" class="">
                    <img src="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo']; ?>" alt="logo"
                        style="width: 100%;">
                </a>
            </div>
            <div class="sidebar">
                <div class="user-panel mt-3 pb-3 mb-3 d-flex" style="border-bottom: 1px solid white;">
                    <div class="image">
                        <?php if (!empty($_SESSION['PHOTO']) && $this->isImage($_SESSION['PHOTO'], 'users')): ?>
                            <img src="<?php echo baseUrl . 'public/uploads/users/' . $_SESSION['PHOTO']; ?>"
                                class="img-circle elevation-2" alt="<?php echo $_SESSION['NAME']; ?>"
                                style="width: 46px; height: 46px;">
                        <?php else: ?>
                            <img src="<?php echo baseUrl; ?>public/app/dist/img/avatar5.png" class="img-circle elevation-2"
                                alt="avatar" style="width: 40px;">
                        <?php endif; ?>
                    </div>
                    <div class="info" style="margin-top: -8px; text-align: left;">
                        <a onclick="openModule('meu-perfil');" class="d-block text-white" style="cursor: pointer">
                            <?php 
                            $name = explode(" ", $_SESSION['NAME']);
                            echo $name[0] . (!empty($name[1]) ? ' ' . $name[1] : ''); 
                            ?><br>
                            <small style="font-size: 13px;">
                                <a onclick="openModule('meu-perfil');" class="d-block text-white"
                                    style="cursor: pointer">
                                    (
                                    <?php echo $_SESSION['ROLE_NAME']; ?> )
                                </a>
                            </small>
                        </a>
                    </div>
                </div>
                <nav class="mt-2 text-left">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="true">
                        <?php if (
                            $this->view->isAdmin
                            || $canViewPayments
                            || $canViewCategories
                            || $canViewServices
                            || $canViewItems
                        ): ?>
                            <li class="nav-item">
                                <a href="#" class="nav-link text-white">
                                    <i class="nav-icon fas fa-plus-circle"></i>
                                    <p>
                                        Cadastros
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview" style="display: none;">
                                    <?php if ($this->view->isAdmin || $canViewCategories): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('categorias');" class="nav-link text-white" 
                                                style="cursor: pointer;">
                                                <i class="nav-icon fas fa-filter"></i>
                                                <p>
                                                    Categorias
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($this->view->isAdmin || $canViewItems): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('estoque');" class="nav-link text-white"
                                                style="cursor: pointer;">
                                                <i class="nav-icon fas fa-cubes"></i>
                                                <p>
                                                    Produtos
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($this->view->isAdmin || $canViewServices): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('servicos');" class="nav-link text-white"
                                                style="cursor: pointer;">
                                                <i class="nav-icon fas fa-tools"></i>
                                                <p>
                                                    Serviços
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($this->view->isAdmin || $canViewPayments): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('formas-pagamento');" class="nav-link text-white"
                                                style="cursor: pointer;">
                                                <i class="nav-icon fas fa-credit-card"></i>
                                                <p>
                                                    Formas Pagamento
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </li>
                        <?php endif; ?>
                        <?php if (
                            $this->view->isAdmin
                            || $canViewSchedules
                            || $canViewCustomers
                        ): ?>
                            <li class="nav-item">
                                <a href="#" class="nav-link text-white">
                                    <i class="nav-icon fas fa-building"></i>
                                    <p>
                                        Gestão
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview" style="display: none;">
                                    <?php if ($this->view->isAdmin || $canViewSchedules): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('agendamentos');" class="nav-link text-white"
                                                style="cursor: pointer;">
                                                <i class="nav-icon fas fa-calendar"></i>
                                                <p>
                                                    Agendamentos
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($this->view->isAdmin || $canViewCustomers): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('clientes');" class="nav-link text-white"
                                                style="cursor: pointer;">
                                                <i class="nav-icon fas fa-users"></i>
                                                <p>
                                                    Clientes
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </li>
                        <?php endif; ?>
                        <?php if (
                            $this->view->isAdmin
                            || $canViewExpenses
                            || $canViewFinancial
                            || $canViewPurchases
                        ): ?>
                            <li class="nav-item">
                                <a href="#" class="nav-link text-white">
                                    <i class="nav-icon fas fa-dollar-sign"></i>
                                    <p>
                                        Financeiro
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview" style="display: none;">
                                    <?php if ($this->view->isAdmin || $canViewExpenses): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('contas');" class="nav-link text-white"
                                                style="cursor: pointer;">
                                                <i class="nav-icon fas fa-money-bill-wave"></i>
                                                <p>
                                                    Contas
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($this->view->isAdmin || $canViewFinancial): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('financeiro');" class="nav-link text-white"
                                                style="cursor: pointer;">
                                                <i class="nav-icon fas fa-dollar-sign"></i>
                                                <p>
                                                    Fluxo de Caixa
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </li>
                        <?php endif; ?>
                        <?php if ($this->view->isAdmin || $canViewReports): ?>
                            <li class="nav-item">
                                <a onclick="openModule('relatorios');" class="nav-link text-white"
                                    style="cursor: pointer;">
                                    <i class="nav-icon fas fa-file-pdf"></i>
                                    <p>
                                        Relatórios
                                    </p>
                                </a>
                            </li>
                        <?php endif; ?>
                        <?php if (
                            $this->view->isAdmin
                            || $canViewConfigs
                            || $canViewSmtp
                            || $canViewLogs
                        ): ?>
                            <li class="nav-item">
                                <a href="#" class="nav-link text-white">
                                    <i class="nav-icon fas fa-cog"></i>
                                    <p>
                                        Sistema
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview" style="display: none;">
                                    <?php if ($this->view->isAdmin || $canViewConfigs): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('configuracoes');" class="nav-link text-white"
                                                style="cursor: pointer;">
                                                <i class="nav-icon fas fa-cogs"></i>
                                                <p>
                                                    Configurações
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($this->view->isAdmin): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('controle-acesso');" class="nav-link text-white"
                                                style="cursor: pointer;">
                                                <i class="nav-icon fas fa-lock"></i>
                                                <p>
                                                    Controle de Acesso
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($this->view->isAdmin || $canViewLogs): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('logs');" class="nav-link text-white"
                                                style="cursor: pointer;">
                                                <i class="nav-icon fas fa-list"></i>
                                                <p>
                                                    Logs do Sistema
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </li>
                        <?php endif; ?>
                        <?php if ($this->view->isAdmin || $canViewUsers): ?>
                            <li class="nav-item">
                                <a onclick="openModule('usuarios');" class="nav-link text-white"
                                    style="cursor: pointer;">
                                    <i class="nav-icon fas fa-user"></i>
                                    <p>
                                        Usuários
                                    </p>
                                </a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </nav>
            </div>
        </aside>
        <div class="content-wrapper">
            <div id="sis_content">
                <?php echo $this->content(); ?>
            </div>
            <div class="modal fade" id="modalMid" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalMidLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-primary">
                            <h4 class="modal-title" id="modalMidTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalMidResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalMonth" data-keyboard="false">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="overlay" id="modalMonthLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-primary">
                            <h4 class="modal-title" id="modalMonthTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalMonthResult">
                            <div class="form-group">
                                <label for="month">Informe o Mês</label>
                                <input type="month" id="f_month" class="form-control" required
                                    value="<?php echo date('Y-m'); ?>">
                            </div>
                            <button type="button" class="btn btn-primary btnRadius" onclick="selectMonth();" style="width: 100%;">
                                <i class="fas fa-filter pr-1"></i> FILTRAR
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalXL">
                <div class="modal-dialog modal-xl">
                    <div class="modal-content">
                        <div class="overlay" id="modalXLLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header bg-primary text-white">
                            <h4 class="modal-title" id="modalXLTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalXLResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalLarge" data-keyboard="false">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="overlay" id="modalLargeLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-primary">
                            <h4 class="modal-title" id="modalLargeTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalLargeResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalGreenMid" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalGreenMidLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-success">
                            <h4 class="modal-title" id="modalGreenMidTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalGreenMidResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalGreenLarge" data-keyboard="false">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="overlay" id="modalGreenLargeLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-success">
                            <h4 class="modal-title" id="modalGreenLargeTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalGreenLargeResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalDelete" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalDeleteLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-danger">
                            <h4 class="modal-title" id="modalDeleteTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="text-center pt-3">
                            <b>Tem certeza que deseja excluir este registro? <br>Após esta operação, não será possível
                                revertê-la.</b>
                        </div>
                        <div class="modal-body text-center" id="modalDeleteResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalDeleteTimeSheet" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalDeleteTimeSheetLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-danger">
                            <h4 class="modal-title" id="modalDeleteTimeSheetTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="text-center pt-3">
                            <div class="row">
                                <div class="col-md-12">
                                    <b>Tem certeza que deseja excluir este registro? 
                                        <br>Após esta operação, não será possível revertê-la.</b>
                                </div>
                                <div class="col-md-12 mt-3">
                                    <input type="checkbox" name="time_sheet_delete_notification" id="time_sheet_delete_notification" value="1" class="mr-1"> 
                                    <small style="position: relative; top: -2px;">Enviar notificação sobre a operação.</small>
                                </div>
                            </div>
                        </div>
                        <div class="modal-body text-center" id="modalDeleteTimeSheetResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalApproval" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalApprovalLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-success">
                            <h4 class="modal-title" id="modalApprovalTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="text-center pt-3">
                            <b>Confirmar ação? <br>Após esta operação, não será possível revertê-la.</b>
                        </div>
                        <div class="modal-body text-center" id="modalApprovalResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalDisapproval" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalDisapprovalLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-danger">
                            <h4 class="modal-title" id="modalDisapprovalTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="text-center pt-3">
                            <b>Confirmar ação? <br>Após esta operação, não será possível revertê-la.</b>
                        </div>
                        <div class="modal-body text-center" id="modalDisapprovalResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalReportDetails" data-keyboard="false">
                <div class="modal-dialog modal-xl">
                    <div class="modal-content">
                        <div class="overlay" id="modalReportDetailsLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-primary">
                            <h4 class="modal-title" id="modalReportDetailsTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalReportDetailsResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalMini" data-keyboard="false">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="overlay" id="modalMiniLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-primary">
                            <h4 class="modal-title" id="modalMiniTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalMiniResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalDeleteBasicFile" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalDeleteBasicFileLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-danger">
                            <h4 class="modal-title" id="modalDeleteBasicFileTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="text-center pt-3">
                            <div class="row">
                                <div class="col-md-12">
                                    <b>Tem certeza que deseja excluir este registro? 
                                        <br>Após esta operação, não será possível revertê-la.</b>
                                </div>
                                <div class="col-md-12 mt-3">
                                    <input type="checkbox" name="basic_delete_notification_file" id="basic_delete_notification_file" value="1" class="mr-1"> 
                                    <small style="position: relative; top: -2px;">Enviar notificação sobre a operação.</small>
                                </div>
                            </div>
                        </div>
                        <div class="modal-body text-center" id="modalDeleteBasicFileResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalRestore" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalRestoreLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-primary">
                            <h4 class="modal-title" id="modalRestoreTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="text-center pt-3">
                            <div class="row">
                                <div class="col-md-12">
                                    <b>Tem certeza que deseja restaurar este registro?</b>
                                </div>
                                <div class="col-md-12 mt-3">
                                    <input type="checkbox" name="basic_restore_notification" 
                                        id="basic_restore_notification" value="1" class="mr-1"> 
                                    <small style="position: relative; top: -2px;">Enviar notificação sobre a operação.</small>
                                </div>
                            </div>
                        </div>
                        <div class="modal-body text-center" id="modalRestoreResult"></div>
                    </div>
                </div>
            </div>
            <div class="overlay-wrapper" id="baseLoader" style="display: none;">
                <div class="overlay">
                    <i class="fas fa-3x fa-sync-alt fa-spin"></i>
                    <div class="text-bold pt-2 ml-3">Carregando...</div>
                </div>
            </div>
            <div class="overlay-wrapper" id="baseLoaderTop" style="display: none;">
                <div class="overlay">
                    <i class="fas fa-3x fa-sync-alt fa-spin"></i>
                    <div class="text-bold pt-2 ml-3">Carregando...</div>
                </div>
            </div>
        </div>
        <footer class="main-footer">
            <div class="text-center" style="font-size: 11px">
                <b>Licenciado para</b>
                <?php echo $config['site_title'] ?> &nbsp;
                <b>Versão</b>
                <?php echo $config['version']; ?> <br>
                Sistema desenvolvido por <a href="https://jaconsultoriati.com.br/" target="_blank">JA Consultoria TI</a>
            </div>
        </footer>
    </div>
    <script>
        async function loadSystemNotifications() {
            $("#baseLoader").show();
            await $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>notificacoes/conteudo",
                data: {
                    target: '<?php echo $this->getTarget(); ?>'
                },  
                async: true
            }).done(async function (dataNot) {
                await $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>mensagens/checa-mensagens",
                    data: {
                        target: '<?php echo $this->getTarget(); ?>'
                    },  
                    async: true
                }).done(function (dataMsg) {
                    $("#messages_box").html(dataMsg);
                    $("#notifications_box").html(dataNot);
                    $("#baseLoader").fadeOut();
                }).fail(function () {
                    showInternalErrorAlert();
                    $("#baseLoader").fadeOut();
                });
            }).fail(function () {
                showInternalErrorAlert();
                $("#baseLoader").fadeOut();
            });
        }
            
        loadSystemNotifications();

        async function openModule(urlParam) {
            $("#baseLoader").hide();
            $("#baseLoaderTop").show();
            
            await $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>notificacoes/conteudo",
                data: {
                    target: '<?php echo $this->getTarget(); ?>'
                },  
                async: true
            }).done(async function (dataNot) {
                await $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>mensagens/checa-mensagens",
                    data: {
                        target: '<?php echo $this->getTarget(); ?>'
                    },  
                    async: true
                }).done(async function (dataMsg) {
                    $("#messages_box").html(dataMsg);
                    $("#notifications_box").html(dataNot);
                    
                    await $.ajax({
                        type: 'post',
                        url: "<?php echo baseUrl; ?>" + urlParam,
                        data: {
                            target: '<?php echo $this->getTarget(); ?>'
                        },    
                        async: true
                    }).done(async function (data) {
                        $("#sis_content").html(data);
                        $("#baseLoaderTop").fadeOut();
                    }).fail(function () {
                        showInternalErrorAlert();
                        $("#baseLoaderTop").fadeOut();
                    });

                }).fail(function () {
                    showInternalErrorAlert();
                    $("#baseLoader").fadeOut();
                });
            }).fail(function () {
                showInternalErrorAlert();
                $("#baseLoader").fadeOut();
            });
        }

        function setLogout() {
            $("#modalMiniTitle").html('<i class="fa fa-sign-out-alt pr-2"></i> Encerrar Sessão');
            $("#modalMiniLoader").hide();
            $("#modalMini").modal('show');
            $("#modalMiniResult").html('<button type="button" class="btn btn-danger btnRadius w-100" title="Confirmar" onclick="runLogout();">SAIR</button>');
        }

        function runLogout() {
            $("#modalMiniLoader").show();
            window.location.href = "<?php echo baseUrl . 'sair'; ?>";
        }
    </script>
    <?php if (!empty($_GET['mod'])): ?>
        <script>
            openModule('<?php echo $_GET['mod']; ?>');
        </script>
    <?php endif; ?>
</body>
</html>