<?php 
$config = $this->getSiteConfig();

$canViewUsers = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('user'));
$canViewConfigs = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('configs'));
$canViewPolitics = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('politics'));
$canViewLogs = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('logs'));
$canViewCustomers = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('customers'));
$canViewUseTerms = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('use-terms'));
$canViewExpenses = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('expenses'));
$canViewPayments = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('payment-types'));
$canViewSmtp = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('smtp'));
$canViewSchedules = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('schedules'));
$canViewServices = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('services'));
$canViewFinancial = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('financial'));
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $config['site_title']; ?></title>
    <meta author="João Augusto Bonfante">
    <link rel="icon" href="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo_icon']; ?>" type="image/x-icon" />
    <meta name="robots" content="noindex">
    <meta name="googlebot" content="noindex">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/dist/css/adminlte.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <link href="<?php echo baseUrl; ?>public/app/css/buttons.dataTables.min.css" rel="stylesheet">
	<link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/css/dataTables.bootstrap4.min.css">
    <script src="<?php echo baseUrl; ?>public/app/plugins/jquery/jquery.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/plugins/jquery-ui/jquery-ui.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/dist/js/adminlte.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/jquery.maskMoney.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/jquery.maskedinput.js" type="text/javascript"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/jquery.validate.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/jquery.inputmask.js"></script>
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/plugins/jquery-toast-plugin/dist/jquery.toast.min.css">
    <script src="<?php echo baseUrl; ?>public/app/plugins/jquery-toast-plugin/dist/jquery.toast.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/alerts.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/jquery.dataTables.min.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/dataTables.bootstrap4.min.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/date-eu.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/date-eu-com-filtro.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/dataTables.valoremreais.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/dataTables.buttons.min.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/jszip.min.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/pdfmake.min.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/vfs_fonts.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/buttons.html5.min.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/buttons.print.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo baseUrl; ?>public/app/plugins/select2/css/select2.min.css">
    <script src="<?php echo baseUrl; ?>public/app/plugins/select2/js/select2.min.js"></script>
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <style>
        .pst {
           
        }

        h1 {
            color: <?php echo $config['primary_color']; ?> !important;
        }

        .bg-primary {
            background: <?php echo $config['primary_color']; ?> !important;
        }

        .bg-primary:hover {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .bg-secondary {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .bg-secondary:hover {
            background: <?php echo $config['primary_color']; ?> !important;
        }

        .btn-primary {
            background: <?php echo $config['primary_color']; ?> !important;
        }

        .btn-primary:hover {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .btn-secondary {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .btn-secondary:hover {
            background: <?php echo $config['primary_color']; ?> !important;
        }
        
        .page-link:hover {
            z-index: 2;
            color: #fff;
            text-decoration: none;
            background-color: <?php echo $config['secondary_color']; ?>;
            border-color: <?php echo $config['secondary_color']; ?>;
        }


        .page-item.active .page-link {
            z-index: 3;
            color: #fff;
            background-color: <?php echo $config['primary_color']; ?> !important;;
            border-color: <?php echo $config['primary_color']; ?> !important;;
        }
    </style>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo_icon']; ?>"
            alt="<?php echo $config['site_title']; ?>" height="200">
        </div>
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link"  href="<?php echo baseUrl . 'sair' ?>" >
                        Sair
                    </a>
                </li>
            </ul>
        </nav>
        <?php
        if (!empty($config['file_menu'])):
            $imageUrl = baseUrl . 'public/uploads/menu/' . $config['file_menu'];
            $bgStyle = "background-image: url('$imageUrl'); background-size: cover;";
        else:
            $bgStyle = 'background-color:' . $config['secondary_color'];
        endif;
        ?>
        <aside class="main-sidebar sidebar-dark-primary elevation-4 text-center" style="<?php echo $bgStyle; ?> !important;">
            <div class="bg-white">
                <a href="<?php echo baseUrl; ?>" class="">
                    <img src="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo']; ?>" alt="logo" style="width: 100%;">
                </a>
            </div>
            <div class="sidebar">
                <div class="user-panel mt-3 pb-3 mb-3 d-flex" style="border-bottom: 1px solid white;">
                    <div class="image">
                        <?php if (!empty($_SESSION['PHOTO'])): ?>
                            <img src="<?php echo baseUrl . 'public/uploads/users/' . $_SESSION['PHOTO']; ?>" class="img-circle elevation-2" alt="<?php echo $_SESSION['NAME']; ?>"
                                style="width: 46px; height: 46px;">
                        <?php else: ?>
                            <img src="<?php echo baseUrl; ?>public/app/dist/img/avatar5.png" class="img-circle elevation-2" alt="avatar"
                                style="width: 40px;">
                        <?php endif; ?>
                    </div>
                    <div class="info" style="margin-top: -10px;">
                        <a onclick="openModule('meu-perfil');" class="d-block text-white" style="cursor: pointer"><?php echo $_SESSION['NAME']; ?><br>
                        <small><a onclick="openModule('meu-perfil');" class="d-block text-white" style="cursor: pointer">(<?php echo $_SESSION['ROLE_NAME']; ?>)</a></small></a>
                    </div>
                </div>
                <nav class="mt-2 text-left">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="true">
                        <li class="nav-item">
                            <a href="<?php echo baseUrl; ?>" class="nav-link text-white">
                                <i class="nav-icon fas fa-home"></i>
                                <p>
                                    Início
                                </p>
                            </a>
                        </li>
                        <?php if (
                            $_SESSION['ROLE_ADM'] == '1'
                            || $canViewCustomers
                            || $canViewUsers
                            || $canViewExpenses
                            || $canViewSchedules
                            || $canViewServices
                        ): ?>
                            <li class="nav-item">
                                <a href="#" class="nav-link text-white">
                                    <i class="nav-icon fas fa-users-cog"></i>
                                    <p>
                                        ADMINISTRAÇÃO
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview" style="display: none;">
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewSchedules): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('agendamentos');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-calendar"></i>
                                                <p>
                                                    Agendamentos
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewCustomers): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('clientes');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-users"></i>
                                                <p>
                                                    Clientes
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewUsers): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('usuarios');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-user-cog"></i>
                                                <p>
                                                    Colaboradores
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewExpenses): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('despesas');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-file-invoice-dollar"></i>
                                                <p>
                                                    Despesas
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewFinancial): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('financeiro');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-cash-register"></i>
                                                <p>
                                                    Financeiro
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewServices): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('servicos');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-cubes"></i>
                                                <p>
                                                    Serviços
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </li>
                        <?php endif; ?>
                        <?php if (
                            $_SESSION['ROLE_ADM'] == '1'
                            || $canViewPayments
                            || $canViewConfigs
                            || $canViewSmtp
                            || $canViewLogs

                        ): ?>
                            <li class="nav-item">
                                <a href="#" class="nav-link text-white">
                                    <i class="nav-icon fas fa-cog"></i>
                                    <p>
                                        CONFIGURAÇÕES
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview" style="display: none;">
                                    <?php if ($_SESSION['ROLE_ADM'] == '1'): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('controle-acesso');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-lock"></i>
                                                <p>
                                                    Controle de Acesso
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewPayments): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('formas-pagamento');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-th-list"></i>
                                                <p>
                                                    Formas de Pagamento
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewConfigs): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('configuracoes');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-cogs"></i>
                                                <p>
                                                    Geral
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewLogs): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('logs');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-list"></i>
                                                <p>
                                                    Logs
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewSmtp): ?>
                                        <li class="nav-item ml-2">
                                            <a onclick="openModule('smtp');" class="nav-link text-white" style="cursor: pointer;">
                                                <i class="nav-icon fas fa-envelope-square"></i>
                                                <p>
                                                    SMTP
                                                </p>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </li>
                        <?php endif; ?>

                        <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewPolitics): ?>
                            <li class="nav-item">
                                <a onclick="openModule('politica-privacidade');" class="nav-link text-white" style="cursor: pointer;">
                                    <i class="nav-icon fas fa-eye"></i>
                                    <p>
                                        Política de Privacidade
                                    </p>
                                </a>
                            </li>
                        <?php endif; ?>
                        <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewUseTerms): ?>
                            <li class="nav-item">
                                <a onclick="openModule('termos-de-uso');" class="nav-link text-white" style="cursor: pointer;">
                                    <i class="nav-icon fas fa-check-circle"></i>
                                    <p>
                                        Termos de Uso
                                    </p>
                                </a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </nav>
            </div>
        </aside>
        <div class="content-wrapper">
            <div id="sis_content">
                <?php echo $this->content(); ?>
            </div>
            <div class="modal fade" id="modalMid" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalMidLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-primary">
                            <h4 class="modal-title" id="modalMidTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalMidResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalMonth" data-keyboard="false">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="overlay" id="modalMonthLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-primary">
                            <h4 class="modal-title" id="modalMonthTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalMonthResult">
                            <div class="form-group">
                                <label for="month">Informe o Mês</label>
                                <input type="month" id="f_month" class="form-control" required
                                    value="<?php echo date('Y-m'); ?>">
                            </div>
                            <button type="button" class="btn btn-primary"
                                onclick="selectMonth();" style="width: 100%;">
                                <i class="fas fa-filter pr-1"></i> FILTRAR
                            </button>            
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalXL" >
                <div class="modal-dialog modal-xl">
                    <div class="modal-content">
                        <div class="overlay" id="modalXLLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header bg-primary text-white">
                            <h4 class="modal-title" id="modalXLTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalXLResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalLarge" data-keyboard="false">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="overlay" id="modalLargeLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-primary">
                            <h4 class="modal-title" id="modalLargeTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" id="modalLargeResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalDelete" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalDeleteLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-danger">
                            <h4 class="modal-title" id="modalDeleteTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="text-center pt-3">
                            <b>Tem certeza que deseja excluir este registro? <br>Após esta operação, não será possível revertê-la.</b>
                        </div>
                        <div class="modal-body text-center" id="modalDeleteResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalApproval" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalApprovalLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-success">
                            <h4 class="modal-title" id="modalApprovalTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="text-center pt-3">
                            <b>Confirmar ação? <br>Após esta operação, não será possível revertê-la.</b>
                        </div>
                        <div class="modal-body text-center" id="modalApprovalResult"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="modalDisapproval" data-keyboard="false">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="overlay" id="modalDisapprovalLoader">
                            <i class="fas fa-2x fa-sync fa-spin"></i>
                        </div>
                        <div class="modal-header text-white bg-danger">
                            <h4 class="modal-title" id="modalDisapprovalTitle"></h4>
                            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="text-center pt-3">
                            <b>Confirmar ação? <br>Após esta operação, não será possível revertê-la.</b>
                        </div>
                        <div class="modal-body text-center" id="modalDisapprovalResult"></div>
                    </div>
                </div>
            </div>
            <div class="overlay-wrapper" id="baseLoader" style="display: none;">
                <div class="overlay">
                    <i class="fas fa-3x fa-sync-alt fa-spin"></i>
                    <div class="text-bold pt-2 ml-3">Carregando...</div>
                </div>
            </div>
        </div>
        <footer class="main-footer">
            <b>Versão</b> <?php echo $config['version']; ?>
            <div class="float-right ">
                <strong>Desenvolvido por <a href="https://jaconsultoriati.com.br/" target="_blank">JA Consultoria TI</a></strong>
            </div>
        </footer>
    </div>
    <script>
        function openModule(urlParam) {
            $("#baseLoader").show();
            $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>" + urlParam,
                async: true
            }).done(function(data) {
                $("#sis_content").html(data);
                $("#baseLoader").hide();
            }).fail(function() {
                showInternalErrorAlert();
                $("#baseLoader").hide();
            });
        }
    </script>
    <?php if (!empty($_GET['mod'])): ?>
        <script>
            openModule('<?php echo $_GET['mod']; ?>');
        </script>
    <?php endif; ?>
</body>
</html>
