<?php if ($this->view->acl['canUpdate']): ?>
    <?php $entity = $this->view->entity; ?>
    <form method="post" name="formCreateChangeStatusModal" id="formCreateChangeStatusModal">
        <div class="col-md-12">
            <span class="fa fa-info-circle pr-1"></span>
            <label for="status">Situação Atual</label>
            <p>
                <?php if ($entity['status'] == '1'): ?>
                    <i class="fa fa-circle pr-1 text-info"></i> Pendente
                <?php endif; ?>
                <?php if ($entity['status'] == '2'): ?>
                    <i class="fa fa-circle pr-1 text-success"></i> Paga
                <?php endif; ?>
                <?php if ($entity['status'] == '3'): ?>
                    <i class="fa fa-circle pr-1 text-danger"></i> Cancelada
                <?php endif; ?>
                <?php if ($entity['status'] == '4'): ?>
                    <i class="fa fa-circle pr-1 text-purple"></i> Em Análise
                <?php endif; ?>
            </p>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label for="status">Escolha a nova Situação*</label>
                <select name="status" id="status_1" class="form-control" required>
                    <option value="">Selecione</option>
                    <?php if ($entity['status'] != 1): ?><option value="1">1 - Pendente</option><?php endif; ?>
                    <?php if ($entity['status'] != 2): ?><option value="2">2 - Paga</option><?php endif; ?>
                    <?php if ($entity['status'] != 3): ?><option value="3">3 - Cancelada</option><?php endif; ?>
                    <?php if ($entity['status'] != 4): ?><option value="4">4 - Em Análise</option><?php endif; ?>
                </select>
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <label for="payment_type_id">Forma de Pagamento</label>
                <select name="payment_type_id" id="payment_type_id" class="form-control">
                    <option value="">Selecione</option>
                    <?php foreach ($this->view->paymentTypes as $paymentType): ?>    
                        <option value="<?php echo $paymentType['id']; ?>"
                            <?php echo ($paymentType['id'] == $entity['payment_type_id'])
                                ? 'selected' : ''; ?>>
                            <?php echo $paymentType['id'] . ' - ' . $paymentType['name']; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label for="description">Informações adicionais</label>
                <textarea name="description" id="description" class="form-control" rows="5" 
                    placeholder="Informações adicionais da conta"><?php echo $entity['description']; ?></textarea>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label for="send_email_status">Notificação</label><br>
                <input type="checkbox" name="send_email_status" id="send_email_status" value="1" class="mr-1"> 
                <small style="position: relative; top: -2px;">Enviar notificação sobre a operação.</small>
            </div>
        </div>
        <div class="col-md-12 mt-3 mb-2">
            <button type="submit" class="btn btn-success w-100 btnRadius" id="btnSubmitModalChangeStatus" title="Aplicar nova situação">
                <i class="fa fa-check pr-1"></i> Aplicar
            </button>
        </div>
    </form>
    <script>
        $(document).ready(function () {
            $('#formCreateChangeStatusModal').validate({
                submitHandler: async function () {
                    let form_data = new FormData();         
                        
                    form_data.append('status', $("#status_1").val());
                    form_data.append('description', $("#description").val());
                    form_data.append('payment_type_id', $("#payment_type_id").val());
                    form_data.append('id', '<?php echo $_POST['id']; ?>');    
                    form_data.append('target', '<?php echo $this->getTarget(); ?>');

                    if ($('#send_email_status').is(':checked')) {
                        form_data.append('send_email_status', $("#send_email_status").val());    
                    }

                    $("#modalMidLoader").show();
                    $("#btnSubmitModalChangeStatus").attr('disabled', true);

                    await $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>contas/processa-situacao",
                        cache: false,
                        contentType: false,
                        processData: false,
                        data: form_data,
                        dataType: 'json',
                        async: true
                    }).done(async function (data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        if (data.type === 'success') {
                            await openExpenseDetails(data.id);
                            $("#modalMid").modal('hide');
                        } else {
                            $("#modalMidLoader").hide();
                            $("#btnSubmitModalChangeStatus").attr('disabled', false);
                        }
                    }).fail(function () {
                        showInternalErrorAlert();
                        $("#modalMidLoader").hide();
                        $("#btnSubmitModalChangeStatus").attr('disabled', false);
                    });

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>