<?php if ($_SESSION['ROLE_ADM'] == '0' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('create'), $this->moduleCodes('expenses'))): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-plus-square pr-1"></i>
                        Despesa
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Despesas"
                                onclick="openModule('despesas?m=<?php echo $_POST['month']; ?>');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formCreateExpense" id="formCreateExpense"
                                enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="title">Situação*</label>
                                            <select name="status" id="status_1" class="form-control" required>
                                                <option value="1">Pendente</option>
                                                <option value="2">Concluída</option>
                                                <option value="3">Cancelada</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <hr>
                                        <div class="form-group">
                                            <label for="title">Título da Despesa*</label>
                                            <input type="text" class="form-control" name="title" id="title" required maxlength="100"
                                                placeholder="Nome da Despesa a ser paga">
                                        </div>
                                    </div>   
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="description">Descrição completa</label>
                                            <textarea name="description" id="description" class="form-control" rows="3"
                                                placeholder="Informe a descrição completo caso necessário"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-4">
                                        <div class="form-group">
                                            <label for="amount">Valor*</label>
                                            <input type="text" class="form-control" name="amount" id="amount" required placeholder="0,00">
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-4">
                                        <div class="form-group">
                                            <label for="payment_type_uuid">Forma de Pagamento*</label>
                                            <select name="payment_type_uuid" id="payment_type_uuid" class="form-control" required>
                                                <option value="">Selecione</option>
                                                <?php foreach ($this->view->paymentTypes as $paymentType): ?>    
                                                    <option value="<?php echo $paymentType['uuid']; ?>">
                                                        <?php echo $paymentType['name']; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-4">
                                        <div class="form-group">
                                            <label for="expense_date">Data*</label>
                                            <input type="date" class="form-control" name="expense_date" id="expense_date" required>
                                        </div>
                                    </div>
                                    <div class="col-12"><hr></div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="customer_uuid">Atribuir Cliente</label>
                                            <a onclick="newCustomer();" class="text-success" 
                                                style="cursor: pointer; float: right" title="Adicionar Serviço">
                                                <span class="fa fa-plus-circle"></span>
                                            </a> 
                                            <select name="customer_uuid" id="customer_uuid" class="form-control">
                                                <option value="">Selecione</option>
                                                <?php foreach ($this->view->customers as $customer): ?>
                                                    <option value="<?php echo $customer['uuid']; ?>">
                                                        <?php echo $customer['name']; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="title">Atribuir Usuário</label>
                                            <select name="user_uuid" id="user_uuid" class="form-control">
                                                <option value="">Selecione</option>
                                                <?php foreach ($this->view->users as $user): ?>
                                                    <option value="<?php echo $user['uuid']; ?>">
                                                        <?php echo $user['name'] . ' (' . $user['email'] . ')'; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12"><hr></div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="description">Anexar Arquivos</label>
                                            <input type="file" class="form-control" name="file[]" multiple id="file"
                                                accept="jpg,jpeg,png,pdf">
                                        </div>
                                    </div>
                                    <div class="col-md-8 mt-3 mb-2">
                                        <button type="submit" class="btn btn-success w-100" id="btnSubmit" title="Salvar Despesa">
                                            <i class="fa fa-save pr-1"></i> Salvar
                                        </button>
                                    </div>
                                    <div class="col-md-4 mt-3 mb-2">
                                        <button type="button" class="btn btn-outline-primary w-100"
                                                onclick="openModule('despesas?m=<?php echo $_POST['month']; ?>');" title="Voltar para Despesas">
                                            <i class="fas fa-arrow-left pr-1"></i> Voltar
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function(){
            $("input[id=amount]").maskMoney({allowNegative: false, thousands:'.', decimal:',', affixesStay: true});

            $('#formCreateExpense').validate({
               
                submitHandler: function() {
                    let form_data = new FormData();         
                    
                    $.each($("input[type='file']")[0].files, function (i, file) {
                        form_data.append('file_' + i, file);
                    });

                    form_data.append('title', $("#title").val());    
                    form_data.append('description', $("#description").val());    
                    form_data.append('amount', $("#amount").val());    
                    form_data.append('payment_type_uuid', $("#payment_type_uuid").val());    
                    form_data.append('expense_date', $("#expense_date").val());    
                    form_data.append('customer_uuid', $("#customer_uuid").val());    
                    form_data.append('user_uuid', $("#user_uuid").val());    
                    form_data.append('status', $("#status_1").val());

                    form_data.append('target', '<?php echo $this->getTarget(); ?>');

                    $("#baseLoader").show();
                    $("#btnSubmit").attr('disabled', true);

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>despesas/processa-cadastro",
                        cache: false,
                        contentType: false,
                        processData: false,
                        data: form_data,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#baseLoader").hide();
                        $("#btnSubmit").attr('disabled', false);
                        $('#formCreateExpense').trigger("reset");
                    }).fail(function() {
                        showInternalErrorAlert(); 
                        $("#baseLoader").hide();   
                        $("#btnSubmit").attr('disabled', false);
                    }); 

                    return false;
                }
            });
        });
    </script>
    <script>
        function newCustomer() {
            $("#modalGreenLargeResult").empty();
            $("#modalGreenLarge").modal('hide');
            $("#modalGreenLargeTitle").html('<i class="fa fa-plus-circle pr-1"></i> Adicionar Cliente');
            $("#modalGreenLargeLoader").show();
            $("#modalGreenLarge").modal('show');

            $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>despesas/cadastrar-cliente",
                data: {
                    target: '<?php echo $this->getTarget(); ?>'
                },
                async: true
            }).done(function(data) {
                $("#modalGreenLargeResult").html(data);
                $("#modalGreenLargeLoader").hide();
            }).fail(function() {
                showInternalErrorAlert();
                $("#modalGreenLargeLoader").hide();
            });
        }
    </script>
<?php endif; ?>