<?php
$aclData = $this->view->acl;
$canView = $aclData['canView'];
$canCreate = $aclData['canCreate'];

if ($canView): ?>
    <?php 
    $data = $this->view->data; 
    $totalExpenses = $this->getTotalExpenses();
    ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="card">
                <div class="card-body cardWrapper">
                    <div class="row">
                        <div class="col-8">
                            <h5 class="pt-2">
                                <i class="fas fa-money-bill-wave pr-1"></i>
                                Contas a Pagar / Receber
                            </h5>
                        </div>
                        <div class="col-4 text-right">
                            <?php if ($canCreate): ?>
                                <button type="button" class="btn btn-success btnRadius" 
                                    title="Adicionar Conta"
                                    onclick="createExpense();">
                                    <i class="fas fa-plus"></i>
                                </button>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="row">
                        <div class="col-md-4 text-center">
                            <div class="card bg-info">
                                <div class="card-body cardBox">
                                    <span style="font-size: 1em"><i class="fa fa-minus-circle pr-1"></i> A Pagar</span>
                                    <h3>R$
                                        <?php echo number_format($totalExpenses['totalByStatus_1'], 2, ",", "."); ?>
                                    </h3>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 text-center">
                            <div class="card bg-success">
                                <div class="card-body cardBox">
                                    <span style="font-size: 1em"><i class="fa fa-check-circle pr-1"></i> A Receber</span>
                                    <h3>R$
                                        <?php echo number_format($totalExpenses['totalByStatus_2'], 2, ",", "."); ?>
                                    </h3>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 text-center">
                            <div class="card bg-danger">
                                <div class="card-body cardBox">
                                    <span style="font-size: 1em"><i class="fa fa-minus-circle pr-1"></i> Atrasadas</span> 
                                    <h3><?php echo $totalExpenses['totalDelayed']; ?></h3>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-4 offset-md-4 mb-3 text-center">
                            <a onclick="changeMonth();" style="width: 100%; cursor: pointer;" title="Alterar Mês">
                                <i class="fas fa-sync  pr-1"></i> Mês Atual:
                                <?php echo $this->view->month; ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body cardWrapperList">
                            <?php if (!$data): ?>
                                <div class="alert alert-info mt-3" role="alert">
                                    <i class="fas fa-info-circle pr-1"></i> Nenhuma informação até o momento.
                                </div>
                            <?php else: ?>
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover" id="table_contas" style="width: 100%;">
                                        <thead>
                                            <tr class="text-center" style="height: 30px;">
                                                <th style="font-size: 14px;">Código</th>
                                                <th style="font-size: 14px;">Data</th>
                                                <th style="font-size: 14px;">Conta</th>
                                                <th style="font-size: 14px;">Valor</th>
                                                <th style="font-size: 14px;">Tipo</th>
                                                <th style="font-size: 14px;">Situação</th>
                                                <th style="display: none;">Situação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($data as $entity): ?>
                                                <?php 
                                                $today = strtotime(date('Y-m-d'));
                                                $entityDate = strtotime($entity['expense_date']);

                                                $textColor = "";
                                                if ($entityDate == $today && ($entity['status'] == 1)):
                                                    $textColor = "color: blue !important";
                                                elseif ($entityDate < $today && ($entity['status'] == 1)):
                                                    $textColor = "color: red !important;";
                                                endif;
                                                ?>
                                                <tr class="text-center" style="cursor: pointer;" 
                                                    onclick="openExpenseDetails('<?php echo $entity['id']; ?>');">
                                                    <td style="font-size: 15px; <?php echo $textColor; ?>">
                                                        <?php echo $entity['id']; ?>
                                                    </td>
                                                    <td style="font-size: 15px; <?php echo $textColor; ?>">
                                                        <?php echo $this->formatDate($entity['expense_date']); ?>
                                                    </td>
                                                    <td style="font-size: 15px; <?php echo $textColor; ?>">
                                                        <?php echo $entity['title']; ?>
                                                    </td>
                                                    <td style="font-size: 15px; <?php echo $textColor; ?>">
                                                        <?php echo number_format($entity['amount'], 2, ",", "."); ?>
                                                    </td>
                                                    <td style="font-size: 15px; <?php echo $textColor; ?>">
                                                        <?php if ($entity['expense_type'] == '1'): ?>
                                                            Receber
                                                        <?php endif; ?>
                                                        <?php if ($entity['expense_type'] == '2'): ?>
                                                            Pagar
                                                        <?php endif; ?>
                                                    </td>
                                                    <td style="font-size: 15px;">
                                                        <?php if ($entity['status'] == '1'): ?>
                                                            <span class="text-info" style="<?php echo $textColor; ?>">Pendente</span>
                                                        <?php endif; ?>
                                                        <?php if ($entity['status'] == '2'): ?>
                                                            <span class="text-success" style="<?php echo $textColor; ?>">Paga</span>
                                                        <?php endif; ?>
                                                        <?php if ($entity['status'] == '3'): ?>
                                                            <span class="text-danger" style="<?php echo $textColor; ?>">Cancelada</span>
                                                        <?php endif; ?>
                                                        <?php if ($entity['status'] == '4'): ?>
                                                            <span class="text-purple" style="<?php echo $textColor; ?>">Em Análise</span>
                                                        <?php endif; ?>
                                                    </td>
                                                    <td style="display: none;">
                                                        <?php echo ($entity['status'] == '1') ? 'Pendente' : ''; ?>
                                                        <?php echo ($entity['status'] == '2') ? 'Paga' : ''; ?>
                                                        <?php echo ($entity['status'] == '3') ? 'Cancelada' : ''; ?>
                                                        <?php echo ($entity['status'] == '4') ? 'Em Análise' : ''; ?>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function () {
            $("#f_month").val('<?php echo $this->view->month_not_formatted ?>');
        });
    </script>
    <?php if ($data): ?>
        <script type="text/javascript">
            $(document).ready(function () {
                let buttonCommon = {
                    exportOptions: {
                        format: {
                            body: function (data, row, column) {
                                return column === 3 ?
                                    parseFloat(data.replace(/[.]/g, '').replace(',', '.')).toLocaleString('en-IN',
                                        { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : data;
                            }
                        }
                    }
                };

                $('#table_contas').DataTable({
                    "sDom": 'flBtip',
                    searching: true,
                    buttons: [
                        $.extend(true, {}, buttonCommon, {
                            extend: 'excel',
                            title: 'Contas',
                            exportOptions: { columns: [0, 1, 2, 3, 4, 6] }
                        })
                    ],
                    order: [[0, "desc"]],
                    columnDefs: [
                        { type: 'date-eu', targets: [1] },
                        { type: 'valoresemreais', targets: [3] },
                    ],
                    responsive: true,
                    info: true,
                    processing: true,
                    scrollCollapse: true,
                    paging: true,
                    "pageLength": 25,
                    "language": {
                        "sEmptyTable": "Nenhum registro encontrado",
                        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                        "sInfoPostFix": "",
                        "sInfoThousands": ".",
                        "sLengthMenu": "_MENU_ &nbsp;",
                        "sLoadingRecords": "Carregando...",
                        "sProcessing": "Processando...",
                        "sZeroRecords": "Nenhum registro encontrado",
                        "sSearch": "Filtrar",
                        "oPaginate": {
                            "sNext": "Próximo",
                            "sPrevious": "Anterior",
                            "sFirst": "Primeiro",
                            "sLast": "Último"
                        },
                        "oAria": {
                            "sSortAscending": ": Ordenar colunas de forma ascendente",
                            "sSortDescending": ": Ordenar colunas de forma descendente"
                        }
                    }
                });
            });
        </script>
    <?php endif; ?>
    <script>
        async function changeMonth() {
            $("#modalMonthTitle").html('<i class="fa fa-info-circle pr-2"></i> Alterar Mês');
            $("#modalMonthLoader").hide();
            $("#modalMonth").modal('show');
        }

        async function selectMonth() {
            let month = $("#f_month").val();
            $("#modalMonthLoader").show();
            await openModule('contas?m=' + month);
            $("#modalMonthLoader").hide();
            $("#modalMonth").modal('hide');
        }
    </script>
    <?php if ($canCreate): ?>
        <script>
            async function createExpense() {
                $("#baseLoader").show();
                await $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>contas/cadastrar",
                    data: {
                        month: $("#f_month").val(),
                        target: '<?php echo $this->getTarget(); ?>'
                    },  
                    async: true
                }).done(function (data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").fadeOut();
                }).fail(function () {
                    showInternalErrorAlert();
                    $("#baseLoader").fadeOut();
                });
            }
        </script>
    <?php endif; ?>
    <script>
        async function openExpenseDetails(id) {
            $("#baseLoader").show();
            await $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>contas/detalhes",
                data: {
                    id:id,
                    month: $("#f_month").val(),
                    target: '<?php echo $this->getTarget(); ?>'
                },
                async: true
            }).done(function (data) {
                $("#sis_content").html(data);
                $("#baseLoader").fadeOut();
            }).fail(function () {
                showInternalErrorAlert();
                $("#baseLoader").fadeOut();
            });
        }
    </script>
<?php endif; ?>