<?php if ($_SESSION['ROLE_ADM'] == '0' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('expenses'))): ?>
    <?php $entity = $this->view->entity; ?>
    <?php if(empty($_POST['modal'])): ?>
        <section class="content-header mt-5">
            <div class="container-fluid mt-2">
                <div class="row">
                    <div class="col-9" >
                        <h1 style="position: relative; top: 5px; font-size: 25px;">
                            <i class="fas fa-info-circle pr-1"></i>
                            Despesa para <?php echo $this->formatDate($entity['expense_date']); ?>
                        </h1>
                    </div>
                    <div class="col-3">
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item">
                                <button type="button" class="btn btn-outline-info mr-1" title="Imprimir"
                                    onclick="window.print();">
                                    <i class="fas fa-print"></i> 
                                </button>
                                <button type="button" class="btn btn-outline-primary" title="Voltar para Despesas"
                                    onclick="openModule('despesas?m=<?php echo $_POST['month']; ?>');">
                                    <i class="fas fa-arrow-left"></i> 
                                </button>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>
        <section class="content" style="margin-left: 9px; margin-right: 9px;">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                    <?php endif; ?>
                    <div class="card">
                        <div class="card-body"> 
                            <div class="row" id="printable">
                                <div class="col-md-12">
                                    <?php if ($entity['status'] == '1'): ?>
                                        <i class="fa fa-circle pr-1" style="color: orange;"></i> Pagamento pendente
                                    <?php endif; ?>
                                    <?php if ($entity['status'] == '2'): ?>
                                        <i class="fa fa-circle pr-1" style="color: green;"></i> Pagamento concluído
                                    <?php endif; ?>
                                    <?php if ($entity['status'] == '3'): ?>
                                        <i class="fa fa-circle pr-1" style="color: red;"></i> Pagamento cancelada
                                    <?php endif; ?>
                                    <hr>
                                </div>
                                <div class="col-md-12">
                                    <b>Despesa</b>
                                    <p><?php echo $entity['title']; ?></p>
                                </div>
                                <?php if (!empty($entity['description'])): ?>
                                    <div class="col-md-12">
                                        <b>Descrição</b>
                                        <p><?php echo $entity['description']; ?></p>
                                    </div>
                                <?php endif; ?>
                                <?php if (!empty($entity['customerName'])): ?>
                                    <div class="col-md-12">
                                        <b>Cliente</b>
                                        <p><?php echo $entity['customerName']; ?></p>
                                    </div>
                                <?php endif; ?>
                                <div class="col-md-12"><hr></div>
                                <div class="col-md-3">
                                    <b>Data</b>
                                    <p><?php echo $this->formatDate($entity['expense_date']); ?></p>
                                </div>
                                <div class="col-md-3">
                                    <b>Valor</b>
                                    <p>R$ <?php echo number_format($entity['amount'], 2, ",", "."); ?></p>
                                </div>
                                <div class="col-md-4">
                                    <b>Forma de Pagamento</b>
                                    <p>
                                        <?php echo $entity['paymentTypeName']; ?>    
                                    </p>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-md-12 text-center">
                                    <b>Arquivos Enviados</b>
                                    <?php if (!empty($this->view->files)) : ?>
                                        <?php foreach ($this->view->files as $file) : ?>
                                            <div>
                                                <?php if ($this->isImage($file['file'])): ?>
                                                    <a href="<?php echo baseUrl . 'public/uploads/expenses/' . $entity['uuid'] . '/' . $file['file']; ?>" 
                                                        data-lightbox="image-1"
                                                        data-title="<?php echo $file['file']; ?>">
                                                        <span class="fa fa-image pr-1"></span> <?php echo $file['file']; ?>
                                                    </a>
                                                <?php else: ?>
                                                    <a href="<?php echo baseUrl . 'public/uploads/expenses/' . $entity['uuid'] . '/' . $file['file']; ?>" 
                                                        target="_blank">
                                                        <span class="fa fa-file-pdf pr-1"></span> <?php echo $file['file']; ?>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endforeach; ?>
                                    <?php else : ?>
                                        <p class="text-center mt-2">Nenhum arquivo enviado</p>
                                    <?php endif; ?>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-6 text-left">
                                    <span class="fa fa-calendar pr-1"></span>
                                    <span>Cadastrada em</span> <br>
                                    <b>
                                        <?php echo $this->formatDateTime($entity['created_at']); ?>
                                    </b>
                                </div>
                                <div class="col-6 text-right">
                                    <?php if (!empty($entity['updated_at'])): ?>
                                        <span class="fa fa-calendar pr-1"></span>
                                        <span>Atualizada em</span> <br>
                                        <b>
                                            <?php echo $this->formatDateTime($entity['updated_at']); ?>
                                        </b>
                                    <?php endif; ?>
                                </div>
                                <div class="col-md-12"><hr></div>                            
                            </div>
                            <div class="row">
                                <?php if(empty($_POST['modal'])): ?>
                                    <?php if ($entity['status'] == '1'): ?>
                                        <div class="col-md-6 col-lg-4 mt-2 mb-2">
                                            <?php if ($_SESSION['ROLE_ADM'] == '0' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('delete'), $this->moduleCodes('expenses'))): ?>
                                                <button type="button" class="btn btn-outline-danger"  title="Excluir Despesa"
                                                    onclick="deleteExpense('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                                    <i class="fa fa-trash"></i> Excluir
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                        <div class="col-md-6 col-lg-4 mt-2 mb-2">
                                            <?php if ($_SESSION['ROLE_ADM'] == '0' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('update'), $this->moduleCodes('expenses'))): ?>
                                                <button type="button" class="btn btn-outline-success"  title="Editar Despesa"
                                                    onclick="updateExpense('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                                    <i class="fa fa-pen pr-1"></i> Editar
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                        <div class="col-md-12 col-lg-4 mt-2 mb-2">
                                            <button type="button" class="btn btn-outline-primary" title="Voltar para Despesas"
                                                onclick="openModule('despesas?m=<?php echo $_POST['month']; ?>');" style="width: 100%;">
                                                <i class="fas fa-arrow-left pr-1"></i> Voltar
                                            </button>
                                        </div>
                                    <?php else: ?>
                                        <div class="col-md-4 offset-md-4 mt-2 mb-2">
                                            <button type="button" class="btn btn-outline-primary" title="Voltar para Despesas"
                                                onclick="openModule('despesas?m=<?php echo $_POST['month']; ?>');" style="width: 100%;">
                                                <i class="fas fa-arrow-left pr-1"></i> Voltar
                                            </button>
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <?php if (!empty($_POST['modal']) && $_POST['modal'] == true): ?>
                        <div class="row mt-md-4">
                            <div class="col-12 col-md-4">
                                <button type="button" class="btn btn-outline-success w-100 mb-3" 
                                    onclick="openModDetails('<?php echo $entity['uuid']; ?>', 'despesas', '<?php echo substr($entity['expense_date'], 0,7); ?>');">
                                    <i class="fa fa-external-link-alt pr-1"></i> Acessar
                                </button>
                            </div>
                            <div class="col-12 col-md-4">
                                <button type="button" class="btn btn-outline-primary w-100 mb-3" title="Imprimir"
                                    onclick="window.print();">
                                    <i class="fas fa-print pr-1"></i> Imprimir
                                </button>
                            </div>
                            <div class="col-12 col-md-4">
                                <button type="button" class="btn btn-outline-danger w-100" data-dismiss="modal">
                                    <i class="fa fa-window-close pr-1"></i> Fechar
                                </button>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if(empty($_POST['modal'])): ?>
                    </div>
                </div>
            </div>
        </section>
    <?php endif; ?>
<?php endif; ?>