<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('expenses'))): ?>
    <?php $entity = $this->view->entity; ?>
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-12">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-info-circle pr-1"></i>
                        Dados da Despesa
                    </h1>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body"> 
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="name">Despesa</label>
                                        <p><?php echo $entity['title']; ?></p>
                                    </div>
                                </div>
                                <?php if (!empty($entity['description'])): ?>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="name">Descrição</label>
                                            <p><?php echo $entity['description']; ?></p>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <?php if (!empty($entity['customerName'])): ?>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="name">Cliente</label>
                                            <p><?php echo $entity['customerName']; ?></p>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <div class="col-md-12"><hr></div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="name">Data</label>
                                        <p><?php echo $this->formatDate($entity['expense_date']); ?></p>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="name">Valor</label>
                                        <p>R$ <?php echo number_format($entity['amount'], 2, ",", "."); ?></p>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="name">Forma de Pagamento</label>
                                        <p>
                                        <?php echo $entity['paymentTypeName']; ?>    
                                        </p>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label for="name">Status</label>
                                        <?php if ($entity['status'] == '1'): ?>
                                            <p>
                                                <i class="fa fa-circle" style="color: orange;"></i> Pendente
                                            </p>
                                        <?php endif; ?>
                                        <?php if ($entity['status'] == '2'): ?>
                                            <p>
                                                <i class="fa fa-circle" style="color: green;"></i> Concluída
                                            </p>
                                        <?php endif; ?>
                                        <?php if ($entity['status'] == '3'): ?>
                                            <p>
                                                <i class="fa fa-circle" style="color: red;"></i> Cancelada
                                            </p>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php if (!empty($entity['file'])): ?>
                                    <div class="col-md-12"><hr></div>
                                    <div class="col-12 text-center">
                                        <div class="form-group">
                                            <label for="name">Anexo</label>
                                            <p>
                                                <a href="<?php echo baseUrl . 'public/uploads/expenses/' . $entity['file']; ?>" target="_blank">
                                                    <?php echo $entity['file']; ?>
                                                </a>
                                            </p>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <div class="col-md-12"><hr></div>
                                <div class="col-6 col-md-6 text-left">
                                    <span>Cadastrada em:</span> <br>
                                    <b><?php echo $this->formatDateTime($entity['created_at']); ?></b>
                                </div>
                                <div class="col-6 col-md-6 text-right">
                                    <?php if (!empty($entity['updated_at'])): ?>
                                        <span>Atualizada em:</span> <br>
                                        <b><?php echo $this->formatDateTime($entity['updated_at']); ?></b>
                                    <?php endif; ?>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-6 col-lg-4 mt-2 mb-2">
                                            <button type="button" class="btn btn-primary" onclick="openModule('despesas');" style="width: 100%;">
                                                <i class="fas fa-arrow-left pr-1"></i> Voltar
                                            </button>
                                        </div>
                                        <div class="col-md-6 col-lg-4 mt-2 mb-2">
                                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('update'), $this->moduleCodes('expenses'))): ?>
                                                <button type="button" class="btn btn-primary" onclick="updateExpense('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                                    <i class="fa fa-pen pr-1"></i> Editar
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                        <div class="col-md-6 col-lg-4 mt-2 mb-2">
                                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('delete'), $this->moduleCodes('expenses'))): ?>
                                                <button type="button" class="btn btn-primary" onclick="deleteExpense('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                                    <i class="fa fa-trash"></i> Remover
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>