<?php 
$entity = $this->view->entity; 
$role = $_SESSION['ROLE'];
?>
<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($role, $this->resourceCodes('update'), $this->moduleCodes('expenses'))): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-pen-square pr-1"></i>
                        Despesa
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Detalhamento"
                                onclick="openDetails('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formUpdateExpense" id="formUpdateExpense"
                                enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="title">Situação*</label>
                                            <select name="status" id="status_1" class="form-control">
                                                <option value="1" <?php echo ($entity['status'] == '1' ? 'selected' : ''); ?>>Pendente</option>
                                                <option value="2" <?php echo ($entity['status'] == '2' ? 'selected' : ''); ?>>Concluída</option>
                                                <option value="3" <?php echo ($entity['status'] == '3' ? 'selected' : ''); ?>>Cancelada</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <hr>
                                        <div class="form-group">
                                            <label for="title">Título da Despesa*</label>
                                            <input type="text" class="form-control" name="title" id="title" required maxlength="100"
                                                value="<?php echo $entity['title']; ?>" placeholder="Nome da Despesa a ser paga">
                                        </div>
                                    </div>   
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="description">Descrição completa</label>
                                            <textarea name="description" id="description" class="form-control"
                                                rows="3" placeholder="Informe a descrição completo caso necessário"><?php echo $entity['title']; ?></textarea>
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-4">
                                        <div class="form-group">
                                            <label for="amount">Valor*</label>
                                            <input type="text" class="form-control" name="amount" id="amount" required placeholder="0,00"
                                                value="<?php echo number_format($entity['amount'], 2, ",", "."); ?>">
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-4">
                                        <div class="form-group">
                                            <label for="payment_type_uuid">Forma de Pagamento*</label>
                                            <select name="payment_type_uuid" id="payment_type_uuid" class="form-control" required>
                                                <option value="">Selecione</option>
                                                <?php foreach ($this->view->paymentTypes as $paymentType): ?>    
                                                    <option value="<?php echo $paymentType['uuid']; ?>"
                                                        <?php echo ($paymentType['uuid'] == $entity['payment_type_uuid'])
                                                            ? 'selected' : ''; ?>>
                                                        <?php echo $paymentType['name']; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-4">
                                        <div class="form-group">
                                            <label for="expense_date">Data*</label>
                                            <input type="date" class="form-control" name="expense_date" id="expense_date" required
                                                value="<?php echo $entity['expense_date']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-12"><hr></div>
                                    <div class="col-12 col-md-12">
                                        <div class="form-group">
                                            <label for="customer_uuid">Atribuir Cliente</label>
                                            <select name="customer_uuid" id="customer_uuid" class="form-control">
                                                <option value="">Selecione</option>
                                                <?php foreach ($this->view->customers as $customer): ?>
                                                    <option value="<?php echo $customer['uuid']; ?>"
                                                        <?php echo ($customer['uuid'] == $entity['customer_uuid'])
                                                            ? 'selected' : ''; ?>>
                                                        <?php echo $customer['name']; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12"><hr></div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="user_uuid">Anexar Arquivo:</label>
                                            <input type="file" class="form-control" name="file" id="file">
                                        </div>
                                    </div>
                                    <div class="col-md-8 mt-3 mb-2">
                                        <button type="submit" class="btn btn-success w-100 btn-lg" id="btnSubmit" title="Salvar Despesa">
                                            <i class="fa fa-save pr-1"></i> Salvar
                                        </button>
                                    </div>
                                    <div class="col-md-4 mt-3 mb-2">
                                        <input type="hidden" name="uuid" id="id_despesa" value="<?php echo $entity['uuid']; ?>">
                                        <button type="button" class="btn btn-outline-primary btn-lg w-100"
                                                onclick="openDetails('<?php echo $entity['uuid']; ?>');" title="Voltar para Detalhamento">
                                            <i class="fas fa-arrow-left pr-1"></i> Voltar
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function(){
            $("input[id=amount]").maskMoney({allowNegative: false, thousands:'.', decimal:',', affixesStay: true});

            $('#formUpdateExpense').validate({
                submitHandler: function() {
                    let file_data = $('#file').prop('files')[0];
                    let form_data = new FormData();         
                    
                    form_data.append('file', file_data);    
                    form_data.append('title', $("#title").val());    
                    form_data.append('description', $("#description").val());    
                    form_data.append('amount', $("#amount").val());    
                    form_data.append('expense_date', $("#expense_date").val());    
                    form_data.append('customer_uuid', $("#customer_uuid").val());    
                    form_data.append('payment_type_uuid', $("#payment_type_uuid").val());    
                    form_data.append('status', $("#status_1").val());
                    form_data.append('uuid', $("#id_despesa").val());    

                    $("#baseLoader").show();
                    $("#btnSubmit").attr('disabled', true);

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>despesas/processa-edicao",
                        cache: false,
                        contentType: false,
                        processData: false,
                        data: form_data,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        if (data.type === 'success') {
                            updateExpense('<?php echo $entity['uuid']; ?>');
                        } else {
                            $("#baseLoader").hide();
                            $("#btnSubmit").attr('disabled', false);
                        }
                    }).fail(function() {
                        showInternalErrorAlert(); 
                        $("#baseLoader").hide();   
                        $("#btnSubmit").attr('disabled', false);
                    }); 

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>