<?php 
$data = $this->view->data;
$aclData = $this->view->acl;

$canView = $aclData['canViewAcl'];
$canUpdate = $aclData['canUpdateAcl'];
?>
<?php if ($canView): ?>
    <section class="content" style="margin-left: 9px; margin-right: 9px; padding-top: 75px;">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body cardWrapper">
                    <div class="row">
                        <div class="col-6">
                            <h5 class="pt-2">
                                <i class="fas fa-unlock pr-1"></i>
                                <?php echo $this->view->user['name']; ?>
                                <small style="color: #666">
                                    <?php echo ' #' . $this->view->user['id']; ?>
                                </small>
                            </h5>
                        </div>
                        <div class="col-6 text-right">
                            <button type="button" class="btn btn-primary btnRadius" 
                                title="Voltar para Usuário"
                                onclick="openUserDetails('<?php echo $_POST['id']; ?>');">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body cardWrapperBody">
                            <?php if (!$data): ?>
                                <div class="alert alert-info mt-3" role="alert">
                                    <i class="fas fa-info-circle pr-1"></i> Nenhuma informação até o momento.
                                </div>
                            <?php else: ?>
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover" id="table_acl_users" style="width: 100%;">
                                        <thead>
                                            <tr class="text-center" style="height: 30px;">
                                                <th style="font-size: 14px;">Ação</th>
                                                <th style="font-size: 14px;">Módulo</th>
                                                <th style="font-size: 14px;">Situação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($data as $entity): ?>
                                                <tr class="text-center" style="height: 30px; cursor: pointer;">
                                                    <td style="font-size: 15px">
                                                        <?php echo $entity['resourceName']; ?>
                                                    </td>
                                                    <td style="font-size: 15px">
                                                        <?php echo $entity['moduleName']; ?>
                                                    </td>
                                                    <td class="text-center">
                                                        <?php if ($canUpdate): ?>
                                                            <input type="checkbox" id="my-checkbox-<?php echo $entity['id']; ?>"
                                                                data-bootstrap-switch data-off-color="danger" 
                                                                data-on-color="success" onchange="getVal('<?php echo $entity['id']; ?>');"
                                                                <?php echo ($entity['status'] == 1) ? 'checked' : ''; ?>>
                                                        <?php else: ?>
                                                            <?php echo ($entity['status'] == 1) ? 'Ativo' : 'Inativo'; ?>
                                                        <?php endif; ?>
                                                    </td> 
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php if ($data): ?>
        <script>
            $(document).ready(function() {
                $("input[data-bootstrap-switch]").each(function(){
                    $(this).bootstrapSwitch();
                });

                let buttonCommon = {
                    exportOptions: {
                        format: {
                            body: function ( data ) {
                                return data;
                            }
                        }
                    }
                };	

                $('#table_acl_users').DataTable({
                    "sDom": 'fltip',
                    searching: true,
                    buttons: [
                        $.extend( true, {}, buttonCommon, {
                            extend: 'excel',
                            title: 'PRIVILÉGIOS DE ACESSO',
                            exportOptions: {columns: [0,1]}
                        }), 
                        {extend: 'pdf', 
                            title: 'PRIVILÉGIOS DE ACESSO',
                            orientation: 'landscape',
                            pageSize: 'LEGAL',
                            exportOptions: {columns: [0,1]}
                        }
                    ],
                    order: [ [1, "asc"] ],
                    responsive: true,
                    info: true,
                    processing: true,
                    scrollCollapse: true,
                    paging: true,
                    "pageLength": 25,
                    "language": {
                        "sEmptyTable": "Nenhum registro encontrado",
                        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                        "sInfoPostFix": "",
                        "sInfoThousands": ".",
                        "sLengthMenu": "_MENU_ &nbsp;",
                        "sLoadingRecords": "Carregando...",
                        "sProcessing": "Processando...",
                        "sZeroRecords": "Nenhum registro encontrado",
                        "sSearch": "Filtrar",
                        "oPaginate": {
                            "sNext": "Próximo",
                            "sPrevious": "Anterior",
                            "sFirst": "Primeiro",
                            "sLast": "Último"
                        },
                        "oAria": {
                            "sSortAscending": ": Ordenar colunas de forma ascendente",
                            "sSortDescending": ": Ordenar colunas de forma descendente"
                        }
                    }
                });
            });
        </script>
    <?php endif; ?>
    <?php if ($canUpdate): ?>
        <script>
            async function getVal(id) {
                let status_acl;
                if ($('#my-checkbox-' + id).is(":checked")) {
                    status_acl = 1;    
                } else {
                    status_acl = 0;
                }
                
                $("#baseLoader").show();
                await $.ajax({
                    type: "POST",
                    url: "<?php echo baseUrl; ?>usuarios/altera-permissao",
                    data: {
                        id: id,
                        status: status_acl,
                        target: '<?php echo $this->getTarget(); ?>'
                    },
                    dataType: 'json',
                    async: true
                }).done(function(data) {
                    showAlert(data.type, data.title, data.msg, data.pos);
                    $("#baseLoader").fadeOut();
                }).fail(function() {
                    showInternalErrorAlert(); 
                    $("#baseLoader").fadeOut();   
                }); 
            }
        </script>
    <?php endif; ?>
<?php endif; ?>