<?php
$aclData = $this->view->acl;
$canView = $aclData['canView'];
$canCreate = $aclData['canCreate'];

if ($canView): ?>
    <?php $data = $this->view->data; ?>
    <section class="content" style="margin-left: 9px; margin-right: 9px; padding-top: 75px;">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body cardWrapper">
                    <div class="row">
                        <div class="col-6">
                            <h5 class="pt-2">
                                <i class="fas fa-user pr-1"></i>
                                Usuários
                            </h5>
                        </div>
                        <div class="col-6 text-right">
                            <?php if ($canCreate): ?>
                                <button type="button" class="btn btn-success btnRadius"
                                    title="Adicionar Usuário"
                                    onclick="createUser();">
                                    <i class="fas fa-plus"></i>
                                </button>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body cardWrapperList">
                            <?php if (!$data): ?>
                                <div class="alert alert-info mt-3" role="alert">
                                    <i class="fas fa-info-circle pr-1"></i> Nenhuma informação até o momento.
                                </div>
                            <?php else: ?>
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover" id="table_user" style="width: 100%;">
                                        <thead>
                                            <tr class="text-center" style="height: 30px;">
                                                <th style="font-size: 14px;"><i class="fa fa-image"></i></th>
                                                <th style="font-size: 14px;">Código</th>
                                                <th style="font-size: 14px;">Nome</th>
                                                <th style="font-size: 14px;">Email</th>
                                                <th style="font-size: 14px;">Celular</th>
                                                <th style="font-size: 14px;">Cargo</th>
                                                <th style="font-size: 14px;">Perfil</th>
                                                <th style="font-size: 14px;">Situação</th>
                                                <th style="display: none;">Situação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($data as $entity): ?>
                                                <tr class="text-center" style="cursor: pointer;"
                                                    onclick="openUserDetails('<?php echo $entity['id']; ?>');">
                                                    <td style="width: 35px; text-align: center;">
                                                        <?php if (!empty($entity['file']) && $this->isImage($entity['file'], 'users')): ?>
                                                            <a href="<?php echo baseUrl . 'public/uploads/users/' . $entity['file']; ?>" 
                                                                data-lightbox="image-1"
                                                                data-title="<?php echo $entity['file']; ?>">
                                                                <img src="<?php echo baseUrl . 'public/uploads/users/'
                                                                    . $entity['file']; ?>" style="width: 30px; height: 30px;" 
                                                                    alt="<?php echo $entity['name']; ?>"
                                                                    class="img-circle">
                                                            </a>
                                                        <?php else: ?>
                                                            <img src="<?php echo baseUrl . 'public/uploads/semfoto.png'; ?>" 
                                                                style="width: 30px; height: 30px;" alt="<?php echo $entity['name']; ?> - SEM FOTO"
                                                                title="Sem foto"
                                                                class="img-circle">
                                                        <?php endif; ?>
                                                    </td>
                                                    <td style="font-size: 15px">
                                                        <?php echo $entity['id']; ?>
                                                    </td>
                                                    <td style="font-size: 15px; ">
                                                        <?php echo $entity['name']; ?>
                                                    </td>
                                                    <td style="font-size: 15px">
                                                        <?php echo $entity['email']; ?>
                                                    </td>
                                                    <td style="font-size: 15px">
                                                        <?php echo $entity['cellphone']; ?>
                                                    </td>
                                                    <td style="font-size: 15px">
                                                        <?php echo $entity['job_role']; ?>
                                                    </td>
                                                    <td style="font-size: 15px">
                                                        <?php echo $entity['role']; ?>
                                                    </td>
                                                    <td style="font-size: 15px;">
                                                        <?php if ($entity['status'] == '1'): ?>
                                                            <span class="text-success">Ativo</span>
                                                        <?php else: ?>
                                                            <span class="text-danger">Inativo</span>
                                                        <?php endif; ?>
                                                    </td>
                                                    <td style="display: none;">
                                                        <?php echo ($entity['status'] == '1') ? 'Ativo' : 'Inativo'; ?>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php if ($data): ?>
        <script type="text/javascript">
            $(document).ready(function () {
                let buttonCommon = {
                    exportOptions: {
                        format: {
                            body: function (data) {
                                return data;
                            }
                        }
                    }
                };

                $('#table_user').DataTable({
                    "sDom": 'flBtip',
                    searching: true,
                    buttons: [
                        $.extend(true, {}, buttonCommon, {
                            extend: 'excel',
                            title: 'Usuários',
                            exportOptions: { columns: [1, 2, 3, 4, 5, 6, 8] }
                        })
                    ],
                    order: [[1, "asc"]],
                    columnDefs: [
                        { orderable: false, targets: [0] },
                    ],
                    paging: true,
                    "pageLength": 25,
                    "language": {
                        "sEmptyTable": "Nenhum registro encontrado",
                        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                        "sInfoPostFix": "",
                        "sInfoThousands": ".",
                        "sLengthMenu": "_MENU_ &nbsp;",
                        "sLoadingRecords": "Carregando...",
                        "sProcessing": "Processando...",
                        "sZeroRecords": "Nenhum registro encontrado",
                        "sSearch": "Filtrar",
                        "oPaginate": {
                            "sNext": "Próximo",
                            "sPrevious": "Anterior",
                            "sFirst": "Primeiro",
                            "sLast": "Último"
                        },
                        "oAria": {
                            "sSortAscending": ": Ordenar colunas de forma ascendente",
                            "sSortDescending": ": Ordenar colunas de forma descendente"
                        }
                    }
                });
            });
        </script>
    <?php endif; ?>
    <?php if ($canCreate): ?>
        <script>
            async function createUser() {
                $("#baseLoader").show();
                await $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>usuarios/cadastrar",
                    data: {
                        target: '<?php echo $this->getTarget(); ?>'
                    },
                    async: true
                }).done(function (data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").fadeOut();
                }).fail(function () {
                    showInternalErrorAlert();
                    $("#baseLoader").fadeOut();
                });
            }
        </script>
    <?php endif; ?>
    <script>
        async function openUserDetails(id) {
            $("#baseLoader").show();
            await $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>usuarios/detalhes",
                data: { 
                    id: id,
                    target: '<?php echo $this->getTarget(); ?>' 
                },
                async: true
            }).done(function (data) {
                $("#sis_content").html(data);
                $("#baseLoader").fadeOut();
            }).fail(function () {
                showInternalErrorAlert();
                $("#baseLoader").fadeOut();
            });
        }
    </script>
<?php endif; ?>