<?php 
$entity = $this->view->entity; 

$isAdmin = $_SESSION['ROLE_ADM'] == '1';
$role    = $_SESSION['ROLE'];

$canView    = $isAdmin || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('user'));
$canUpdate  = $isAdmin || $this->acl($role, $this->resourceCodes('update'), $this->moduleCodes('user'));
$canDelete  = $isAdmin || $this->acl($role, $this->resourceCodes('delete'), $this->moduleCodes('user'));
$canViewAcl = $isAdmin || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('privileges'));
?>
<?php if ($canView): ?>
    <section class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-info-circle pr-1"></i>
                        Colaborador
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-primary"
                                onclick="openModule('usuarios');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12" style="border-radius: 5px;">
                                    <h5 class="pt-2"><i class="fas fa-user pr-1"></i> Dados Pessoais</h5>
                                    <hr>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name">Nome:</label>
                                        <input type="text" class="form-control" readonly
                                                value="<?php echo $entity['name']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="cnpj">CPF</label>
                                        <input type="text" class="form-control" readonly
                                            value="<?php echo $entity['document_1']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="cnpj">CNPJ</label>
                                        <input type="text" class="form-control" readonly
                                        value="<?php echo $entity['document_2']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="job_role">Cargo:</label>
                                        <input type="text" class="form-control" readonly
                                                value="<?php echo $entity['job_role']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="role">Nível de Acesso:</label>
                                        <input type="text" class="form-control" readonly
                                                value="<?php echo $entity['role']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="name">Email:</label>
                                        <input type="text" class="form-control" readonly
                                                value="<?php echo $entity['email']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="phone">Telefone:</label>
                                        <input type="text" class="form-control" readonly
                                            value="<?php echo $entity['phone']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="cellphone">Celular:</label>
                                        <input type="text" class="form-control" readonly
                                            value="<?php echo $entity['cellphone']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="whatsapp">WhatsApp:</label>
                                        <input type="text" class="form-control" readonly
                                                value="<?php echo $entity['whatsapp']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-12" style="border-radius: 5px;">
                                    <h5 class="pt-2"><i class="fas fa-map-marker-alt pr-1"></i> Localização</h5>
                                    <hr>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="postal_code">CEP</label>
                                        <input type="text" class="form-control"  readonly
                                            value="<?php echo $entity['postal_code']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="address">Endereço</label>
                                        <input type="text" class="form-control" readonly 
                                            value="<?php echo $entity['address']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label for="number">Número</label>
                                        <input type="text" class="form-control"  readonly 
                                            value="<?php echo $entity['number']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="complement">Complemento</label>
                                        <input type="text" class="form-control" readonly
                                            value="<?php echo $entity['complement']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <label for="neighborhood">Bairro</label>
                                        <input type="text" class="form-control"  readonly
                                            value="<?php echo $entity['neighborhood']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <label for="city">Cidade</label>
                                        <input type="text" class="form-control" readonly 
                                            value="<?php echo $entity['city']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label for="state">UF</label>
                                        <input type="text" class="form-control" readonly 
                                            value="<?php echo $entity['state']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-md-4 text-left">
                                    <span>Status</span> <br>
                                    <b><?php echo ($entity['status'] == '1') ? 'Ativo' : 'Inativo'; ?></b>
                                </div>
                                <div class="col-md-4 text-center">
                                    <span>Cadastrado em:</span> <br>
                                    <b><?php echo $this->formatDateTime($entity['created_at']); ?></b>
                                </div>
                                <div class="col-md-4 text-right">
                                    <?php if (!empty($entity['updated_at'])): ?>
                                        <span>Atualizado em:</span> <br>
                                        <b><?php echo $this->formatDateTime($entity['updated_at']); ?></b>
                                    <?php endif; ?>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-6 col-md-6 mt-3">
                                    <?php if ($entity['uuid'] != $_SESSION['COD']): ?>
                                        <?php if ($canDelete): ?>
                                            <button type="button" class="btn btn-default mr-2 mb-2" onclick="deleteUser('<?php echo $entity['uuid']; ?>');">
                                                <i class="fa fa-trash"></i> Remover
                                            </button>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if ($canViewAcl): ?>
                                        <button type="button" class="btn btn-primary mb-2" onclick="aclUser('<?php echo $entity['uuid']; ?>');">
                                            <i class="fa fa-unlock pr-1"></i> Permissões
                                        </button>
                                    <?php endif; ?>
                                </div>
                                <div class="col-6 col-md-6 text-right mt-3 mb-2">
                                    <button type="button" class="btn btn-default mr-2"
                                            onclick="openModule('usuarios');">
                                        <i class="fas fa-arrow-left pr-1"></i> Voltar
                                    </button>
                                    <?php if ($canUpdate): ?>
                                        <button type="button" class="btn btn-primary" onclick="updateUser('<?php echo $entity['uuid']; ?>');">
                                            <i class="fa fa-pen pr-1"></i> Editar
                                        </button>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>