<?php if ($this->view->acl['canUpdate']): ?>
    <?php 
    $entity = $this->view->entity; 
    $roles = $this->view->roles; 
    ?>
    <section class="content" style="margin-left: 9px; margin-right: 9px; padding-top: 75px;">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body cardWrapper">
                    <div class="row">
                        <div class="col-6">
                            <h5 class="pt-2">
                                <i class="fas fa-pen-square pr-1"></i>
                                Usuário <small class="text-gray">#<?php echo $entity['id']; ?></small>
                            </h5>
                        </div>
                        <div class="col-6 text-right">
                            <button type="button" class="btn btn-primary btnRadius" 
                                title="Voltar para Usuário"
                                onclick="openUserDetails('<?php echo $entity['id']; ?>');">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body cardWrapperBody">
                            <form method="post" name="formUpdateUser" id="formUpdateUser">
                                <div class="row">
                                    <div class="col-md-12" style="border-radius: 5px;">
                                        <h5 class="pt-2"><i class="fas fa-user pr-1"></i> Dados Pessoais</h5>
                                        <hr>
                                    </div>
                                    <div class="col-6 col-md-4">
                                        <div class="form-group">
                                            <label>Código</label>
                                            <input type="text" class="form-control" value="<?php echo $entity['id']; ?>" disabled>
                                        </div>
                                    </div>
                                    <div class="col-6 col-md-4">
                                        <div class="form-group">
                                            <label for="status">Situação</label>
                                            <select name="status" id="status_1" class="form-control">
                                                <option value="1" <?php echo ($entity['status'] == '1' ? 'selected' : ''); ?>>1 - Ativo</option>
                                                <option value="0" <?php echo ($entity['status'] == '0' ? 'selected' : ''); ?>>2 - Inativo</option>
                                            </select>
                                        </div>
                                    </div>
                                    <?php if ($this->view->isAdmin): ?>
                                        <div class="col-12 col-md-4">
                                            <div class="form-group">
                                                <label for="name">Nível de Acesso</label>
                                                <select class="form-control" name="role_id" required>
                                                    <option value="">-</option>
                                                    <?php foreach ($roles as $role): ?>
                                                        <option value="<?php echo $role['id']; ?>" 
                                                            <?php echo ($entity['role_id'] == $role['id']) ? 'selected' : ''; ?>>
                                                            <?php echo $role['name']; ?>
                                                        </option>
                                                    <?php endforeach; ?>
                                                </select>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    <div class="col-12"><hr></div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="name">Nome</label>
                                            <input type="text" class="form-control" name="name" id="name" required
                                                value="<?php echo $entity['name']; ?>" maxlength="100">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="birthdate">Dt. Nascimento</label>
                                            <input type="date" class="form-control" name="birthdate" id="birthdate"
                                                value="<?php echo $entity['birthdate']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="document_1">Sexo</label>
                                            <select name="gender" id="gender" class="form-control">
                                                <option value="">-</option>
                                                <option value="F" <?php echo ($entity['gender'] == 'F') ? 'selected' : ''; ?>>1 - Feminino</option>
                                                <option value="M" <?php echo ($entity['gender'] == 'M') ? 'selected' : ''; ?>>2 - Masculino</option>
                                                <option value="O" <?php echo ($entity['gender'] == 'O') ? 'selected' : ''; ?>>3 - Outros</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="document_1">CPF</label>
                                            <input type="text" class="form-control" name="document_1" id="document_1" 
                                                value="<?php echo $entity['document_1']; ?>" onchange="validateCPF();">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="document_2">CNPJ</label>
                                            <input type="text" class="form-control" name="document_2" id="document_2" 
                                                value="<?php echo $entity['document_2']; ?>" onchange="validateCNPJ();">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="phone">Telefone</label>
                                            <input type="text" class="form-control" name="phone" id="phone"
                                                value="<?php echo $entity['phone']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="cellphone">Celular</label>
                                            <input type="text" class="form-control" name="cellphone" id="cellphone" 
                                                value="<?php echo $entity['cellphone']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="email">Email</label>
                                            <input type="email" class="form-control" name="email" id="email" required maxlength="100"
                                                value="<?php echo $entity['email']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-12" style="border-radius: 5px;">
                                        <h5 class="pt-2"><i class="fas fa-map-marker-alt pr-1"></i> Localização</h5>
                                        <hr>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="postal_code">CEP</label>
                                            <input type="text" class="form-control" name="postal_code" id="postal_code" 
                                                value="<?php echo $entity['postal_code']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="address">Endereço</label>
                                            <input type="text" class="form-control" name="address" id="address"  maxlength="100"
                                                value="<?php echo $entity['address']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="number">Número</label>
                                            <input type="text" class="form-control" name="number" id="number"  maxlength="50"
                                                value="<?php echo $entity['number']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="complement">Complemento</label>
                                            <input type="text" class="form-control" name="complement" id="complement"  maxlength="50"
                                                value="<?php echo $entity['complement']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="neighborhood">Bairro</label>
                                            <input type="text" class="form-control" name="neighborhood" id="neighborhood"  maxlength="100"
                                                value="<?php echo $entity['neighborhood']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="city">Cidade</label>
                                            <input type="text" class="form-control" name="city" id="city"  maxlength="100"
                                                value="<?php echo $entity['city']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="state">UF</label>
                                            <input type="text" class="form-control" name="state" id="state"  maxlength="2"
                                                value="<?php echo $entity['state']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-12" style="border-radius: 5px;">
                                        <h5 class="pt-2"><i class="fas fa-info-circle pr-1"></i> Informação Profissional</h5>
                                        <hr>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="job_role">Cargo</label>
                                            <input type="text" class="form-control" name="job_role" id="job_role" required
                                                value="<?php echo $entity['job_role']; ?>" maxlength="50">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="salary">Salário</label>
                                            <input type="text" class="form-control" name="salary" id="salary"
                                                value="<?php echo !empty($entity['salary']) ? number_format($entity['salary'], 2, ",",".") : '0,00'; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="start_date">Dt. Admissão</label>
                                            <input type="date" class="form-control" name="start_date" id="start_date" required
                                                value="<?php echo $entity['start_date']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="end_date">Dt. Saída</label>
                                            <input type="date" class="form-control" name="end_date" id="end_date"
                                                value="<?php echo $entity['end_date']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-12 mt-1">
                                        <div class="row">
                                            <div class="col-md-6 offset-md-3 mb-2">
                                                <input type="hidden" name="target" value="<?php echo $this->getTarget(); ?>">
                                                <input type="hidden" name="id" value="<?php echo $entity['id']; ?>">
                                                <button type="submit" class="btn btn-success w-100 btnRadius" id="btnSubmit" title="Salvar Usuário">
                                                    <i class="fa fa-save pr-1"></i> Salvar
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 text-center mb-3">
                    <button type="button" class="btn btn-default btn-sm btnRadius"
                        onclick="openUserDetails('<?php echo $entity['id']; ?>');" 
                        title="Voltar para Usuário">
                        <i class="fas fa-arrow-left pr-1"></i> Voltar
                    </button>
                </div>
            </div>
        </div>
    </section>
    <script src="<?php echo baseUrl; ?>public/js/api_cep.js"></script>
    <script src="<?php echo baseUrl; ?>public/js/documents_validators.js"></script>
    <script>
        $(document).ready(function() {
            $("input[id=salary]").maskMoney({allowNegative: false, thousands:'.', decimal:',', affixesStay: true});
            
            $("#document_1").mask("999.999.999-99");
            $("#document_2").mask("99.999.999/9999-99");
            $("#phone").mask("(99)9999-9999");
            $("#cellphone").mask("(99)99999-9999");
            $("#postal_code").mask("99999-999");

            $('#formUpdateUser').validate({
                submitHandler: async function( form ){
                    let dados = $( form ).serialize();

                    $("#baseLoader").show();
                    $("#btnSubmit").attr('disabled', true);
                
                    await $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>usuarios/processa-edicao",
                        data: dados,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        if (data.type === 'success') {
                            openUserDetails('<?php echo $entity['id']; ?>');
                        } else {
                            $("#baseLoader").fadeOut();
                            $("#btnSubmit").attr('disabled', false);
                        }
                    }).fail(function() {
                        showInternalErrorAlert(); 
                        $("#baseLoader").fadeOut(); 
                        $("#btnSubmit").attr('disabled', false);
                    }); 

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>