<?php if ($this->view->isAdmin): ?>
    <?php $data = $this->view->data; ?>
    <section class="content" style="margin-left: 9px; margin-right: 9px; padding-top: 75px;">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body cardWrapper">
                    <div class="row">
                        <div class="col-6">
                            <h5 class="pt-2">
                                <i class="fas fa-lock pr-1"></i>
                                Controle de Acesso
                            </h5>
                        </div>
                        <div class="col-6 text-right">
                            <button type="button" class="btn btn-success btnRadius" 
                                title="Adicionar Perfil"
                                onclick="createRole();">
                                <i class="fas fa-plus"></i> 
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body cardWrapperList">
                            <?php if (!$data): ?>
                                <div class="alert alert-info mt-3" role="alert">
                                    <i class="fas fa-info-circle pr-1"></i> Nenhuma informação até o momento.
                                </div>
                            <?php else: ?>
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover" id="table_role" style="width: 100%;">
                                        <thead>
                                            <tr class="text-center" style="height: 30px;">
                                                <th style="font-size: 14px;">Nome</th>
                                                <th style="font-size: 14px;">Administrador</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($data as $entity): ?>
                                                <tr class="text-center" style="cursor: pointer;" 
                                                    onclick="openRoleDetails('<?php echo $entity['id']; ?>');">
                                                    <td style="font-size: 15px">
                                                        <?php echo $entity['name']; ?>
                                                    </td>
                                                    <td style="font-size: 15px">
                                                        <?php echo ($entity['is_admin'] == 1) ? 'Sim' : 'Não'; ?>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php if ($data): ?>
        <script type="text/javascript">
            $(document).ready(function() {
                let buttonCommon = {
                    exportOptions: {
                        format: {
                            body: function ( data ) {
                                return data;
                            }
                        }
                    }
                };	

                $('#table_role').DataTable({
                    "sDom": 'flBtp',
                    searching: true,
                    buttons: [
                        $.extend( true, {}, buttonCommon, {
                            extend: 'excel',
                            title: 'NÍVEIS DE ACESSO',
                            exportOptions: {columns: [0,1]}
                        })
                    ],
                    order: [ [0, "asc"] ],
                    responsive: true,
                    info: true,
                    processing: true,
                    scrollCollapse: true,
                    paging: true,
                    "pageLength": 25,
                    "language": {
                        "sEmptyTable": "Nenhum registro encontrado",
                        "sInfo": "_START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty": "0 até 0 de 0 registros",
                        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                        "sInfoPostFix": "",
                        "sInfoThousands": ".",
                        "sLengthMenu": "_MENU_ &nbsp;",
                        "sLoadingRecords": "Carregando...",
                        "sProcessing": "Processando...",
                        "sZeroRecords": "Nenhum registro encontrado",
                        "sSearch": "Filtrar",
                        "oPaginate": {
                            "sNext": "Próximo",
                            "sPrevious": "Anterior",
                            "sFirst": "Primeiro",
                            "sLast": "Último"
                        },
                        "oAria": {
                            "sSortAscending": ": Ordenar colunas de forma ascendente",
                            "sSortDescending": ": Ordenar colunas de forma descendente"
                        }
                    }
                });
            });
        </script>
    <?php endif; ?>
    <script>
        async function createRole() {
            $("#baseLoader").show();
            await $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>controle-acesso/cadastrar",
                data: { 
                    target: '<?php echo $this->getTarget(); ?>' 
                },
                async: true
            }).done(function(data) {
                $("#sis_content").html(data);
                $("#baseLoader").fadeOut();
            }).fail(function() {
                showInternalErrorAlert();
                $("#baseLoader").fadeOut();
            });
        }

        async function openRoleDetails(id) {
            $("#baseLoader").show();
            await $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>controle-acesso/detalhes",
                data: { 
                    id: id,
                    target: '<?php echo $this->getTarget(); ?>' 
                },
                async: true
            }).done(function(data) {
                $("#sis_content").html(data);
                $("#baseLoader").fadeOut();
            }).fail(function() {
                showInternalErrorAlert();
                $("#baseLoader").fadeOut();
            });
        }
    </script>
<?php endif; ?>