<?php if ($this->view->isAdmin): ?>
    <?php $entity = $this->view->entity; ?>
    <section class="content" style="margin-left: 9px; margin-right: 9px; padding-top: 75px;">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body cardWrapper">
                    <div class="row">
                        <div class="col-6">
                            <h5 class="pt-2">
                                <i class="fas fa-pen-square pr-1"></i>
                                Perfil
                            </h5>
                        </div>
                        <div class="col-6 text-right">
                            <button type="button" class="btn btn-primary btnRadius" 
                                title="Voltar para Controle de Acesso"
                                onclick="openRoleDetails('<?php echo $entity['id']; ?>');">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body cardWrapperBody">
                            <form method="post" name="formUpdateRole" id="formUpdateRole">
                                <div class="row">
                                    <div class="col-md-9">
                                        <div class="form-group">
                                            <label for="name">Nível</label>
                                            <input type="text" class="form-control" name="name" id="name" required
                                                value="<?php echo $entity['name']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="is_admin">Administrador</label>
                                            <select name="is_admin" id="is_admin" class="form-control" required>
                                                <option value="1" <?php echo ($entity['is_admin'] == '1') ? 'selected' : ''; ?>>Sim</option>
                                                <option value="0" <?php echo ($entity['is_admin'] == '0') ? 'selected' : ''; ?>>Não</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12 mt-1">
                                        <div class="row">
                                            <div class="col-md-6 offset-md-3 mb-2">
                                                <input type="hidden" name="id" value="<?php echo $entity['id']; ?>">
                                                <input type="hidden" name="target" value="<?php echo $this->getTarget(); ?>">
                                                <button type="submit" class="btn btn-success w-100 btnRadius" id="btnSubmit" title="Salvar Perfil">
                                                    <i class="fa fa-save pr-1"></i> Salvar
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 text-center mb-3">
                    <button type="button" class="btn btn-default btn-sm btnRadius"
                        onclick="openRoleDetails('<?php echo $entity['id']; ?>');" 
                        title="Voltar para Controle de Acesso">
                        <i class="fas fa-arrow-left pr-1"></i> Voltar
                    </button>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function(){
            $('#formUpdateRole').validate({
                submitHandler: async function( form ){
                    let dados = $( form ).serialize();

                    $("#baseLoader").show();
                    $("#btnSubmit").attr('disabled', false);
                
                    await $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>controle-acesso/processa-edicao",
                        data: dados,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        if (data.type === 'success') {
                            openRoleDetails('<?php echo $entity['id']; ?>');
                        } else {
                            $("#baseLoader").fadeOut();
                            $("#btnSubmit").attr('disabled', false);
                        }
                    }).fail(function() {
                        showInternalErrorAlert(); 
                        $("#baseLoader").fadeOut();
                        $("#btnSubmit").attr('disabled', false);
                    }); 

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>