<?php $unreadTotal = $this->userUnreadNotifications(); ?>
<a class="nav-link cPointer" data-toggle="dropdown">
    <i class="far fa-bell"></i>
    <span class="badge <?php echo ($unreadTotal > 0) ? 'badge-danger' : 'badge-primary'; ?> navbar-badge">
        <span id="unread_notifications_1"><?php echo $unreadTotal; ?></span>
    </span>
</a>
<div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
    <span class="dropdown-item dropdown-header cPointer" onclick="openModule('notificacoes');">
        <span id="unread_notifications_2"><?php echo $unreadTotal; ?></span>
        <?php if ($unreadTotal == 1): ?>
            <span id="notificaton_single">Notificação</span>
        <?php else: ?>
            <span id="notificaton_plural">Notificações</span>
        <?php endif; ?>
    </span>
    <div class="dropdown-divider"></div>
    <?php foreach ($this->view->user_notifications as $userNotification): ?>
        <a onclick="jumpToModule(<?php echo $userNotification['id']; ?>, '<?php echo $userNotification['parent']; ?>', '<?php echo $userNotification['for_files']; ?>');" 
            class="dropdown-item cPointer">
            <div class="media">
                <div class="media-body">
                    <p class="text-sm"><?php echo $userNotification['description']; ?></p>
                    <p class="text-sm text-muted">
                        <i class="far fa-clock mr-1"></i> <?php echo $this->formatDateTime($userNotification['created_at']); ?>
                    </p>
                </div>
            </div>
        </a>
    <?php endforeach; ?>
    <a onclick="openModule('notificacoes');"
        class="dropdown-item dropdown-footer bg-primary cPointer">
        <i class="fa fa-arrow-right"></i> Todas as Notificações
    </a>
</div>
<script>
    async function jumpToModule(id, param, forFilesParam) {
        $("#baseLoader").show();
        await $.ajax({
            type: 'post',
            url: '<?php echo baseUrl; ?>notificacoes/valida-modulo',
            data: {
                id: id,
                param: param,
                target: '<?php echo $this->getTarget(); ?>',
            },  
            dataType: 'json',
            async: true
        }).done(async function (data) {
            if (data.mod_id) {
                await $.ajax({
                    type: 'post',
                    url: '<?php echo baseUrl; ?>notificacoes/lida',
                    data: {
                        id: id,
                        target: '<?php echo $this->getTarget(); ?>',
                    },  
                    async: true
                }).done(async function() {
                    await $.ajax({
                        type: 'post',
                        url: "<?php echo baseUrl; ?>notificacoes/conteudo",
                        data: {
                            target: '<?php echo $this->getTarget(); ?>'
                        },  
                        async: true
                    }).done(async function (dataNot) {
                        $("#notifications_box").html(dataNot);
                        await $.ajax({
                            type: 'post',
                            url: `<?php echo baseUrl; ?>${data.mod_name}`,
                            data: {
                                id: data.mod_id,
                                target: '<?php echo $this->getTarget(); ?>',
                                month: $("#f_month").val(),
                                viewFiles: forFilesParam
                            },  
                            async: true
                        }).done(function (data) {
                            $("#sis_content").html(data);
                            $("#baseLoader").fadeOut();
                        }).fail(function () {
                            showInternalErrorAlert();
                            $("#baseLoader").fadeOut();
                        });
                    }).fail(function () {
                        showInternalErrorAlert();
                        $("#baseLoader").fadeOut();
                    });
                }).fail(function () {
                    showInternalErrorAlert();
                    $("#baseLoader").fadeOut();
                });
            } else {
                showInternalErrorAlert();
                $("#baseLoader").fadeOut();
            }
        }).fail(function () {
            showInternalErrorAlert();
            $("#baseLoader").fadeOut();
        });
    }
</script>