<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('revenues'))): ?>
    <?php $entity = $this->view->entity; ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-info-circle pr-1"></i>
                        Receita para <?php echo $this->formatDate($entity['revenue_date']); ?>
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Receitas"
                                onclick="openModule('receitas');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body"> 
                            <div class="row">
                                <div class="col-md-12">
                                    <?php if ($entity['status'] == '1'): ?>
                                        <i class="fa fa-circle pr-1" style="color: orange;"></i> Pendente
                                    <?php endif; ?>
                                    <?php if ($entity['status'] == '2'): ?>
                                        <i class="fa fa-circle pr-1" style="color: green;"></i> Concluída
                                    <?php endif; ?>
                                    <?php if ($entity['status'] == '3'): ?>
                                        <i class="fa fa-circle pr-1" style="color: red;"></i> Cancelada
                                    <?php endif; ?>
                                    <hr>
                                </div>
                                <div class="col-md-12">
                                    <b>Receita</b>
                                    <p><?php echo $entity['title']; ?></p>
                                </div>
                                <?php if (!empty($entity['description'])): ?>
                                    <div class="col-md-12">
                                        <b>Descrição</b>
                                        <p><?php echo $entity['description']; ?></p>
                                    </div>
                                <?php endif; ?>
                                <?php if (!empty($entity['customerName'])): ?>
                                    <div class="col-md-12">
                                        <b>Cliente</b>
                                        <p><?php echo $entity['customerName']; ?></p>
                                    </div>
                                <?php endif; ?>
                                <div class="col-md-12"><hr></div>
                                <div class="col-md-3">
                                    <b>Data</b>
                                    <p><?php echo $this->formatDate($entity['revenue_date']); ?></p>
                                </div>
                                <div class="col-md-3">
                                    <b>Valor</b>
                                    <p>R$ <?php echo number_format($entity['amount'], 2, ",", "."); ?></p>
                                </div>
                                <div class="col-md-4">
                                    <b>Forma de Pagamento</b>
                                    <p>
                                        <?php echo $entity['paymentTypeName']; ?>    
                                    </p>
                                </div>
                                <?php if (!empty($entity['file'])): ?>
                                    <div class="col-md-12"><hr></div>
                                    <div class="col-12 text-center">
                                        <b>Anexo</b>
                                        <p>
                                            <a href="<?php echo baseUrl . 'public/uploads/revenues/' . $entity['file']; ?>" target="_blank">
                                                <?php echo $entity['file']; ?>
                                            </a>
                                        </p>
                                    </div>
                                <?php endif; ?>
                                <div class="col-md-12"><hr></div>
                                <div class="col-6 text-left">
                                    <span class="fa fa-calendar pr-1"></span>
                                    <span>Cadastrada em</span> <br>
                                    <b>
                                        <?php echo $this->formatDateTime($entity['created_at']); ?>
                                    </b>
                                </div>
                                <div class="col-6 text-right">
                                    <?php if (!empty($entity['updated_at'])): ?>
                                        <span class="fa fa-calendar pr-1"></span>
                                        <span>Atualizada em</span> <br>
                                        <b>
                                            <?php echo $this->formatDateTime($entity['updated_at']); ?>
                                        </b>
                                    <?php endif; ?>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-md-12">
                                    <div class="row">
                                        <?php if ($entity['status'] == '1'): ?>
                                            <div class="col-md-6 col-lg-4 mt-2 mb-2">
                                                <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('delete'), $this->moduleCodes('revenues'))): ?>
                                                    <button type="button" class="btn btn-outline-danger"  title="Remover Receita"
                                                        onclick="deleteRevenue('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                                        <i class="fa fa-trash"></i> Remover
                                                    </button>
                                                <?php endif; ?>
                                            </div>
                                            <div class="col-md-6 col-lg-4 mt-2 mb-2">
                                                <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('update'), $this->moduleCodes('revenues'))): ?>
                                                    <button type="button" class="btn btn-outline-success"  title="Editar Receita"
                                                        onclick="updateRevenue('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                                        <i class="fa fa-pen pr-1"></i> Editar
                                                    </button>
                                                <?php endif; ?>
                                            </div>
                                            <div class="col-md-12 col-lg-4 mt-2 mb-2">
                                                <button type="button" class="btn btn-outline-primary" title="Voltar para Receitas"
                                                    onclick="openModule('receitas');" style="width: 100%;">
                                                    <i class="fas fa-arrow-left pr-1"></i> Voltar
                                                </button>
                                            </div>
                                        <?php else: ?>
                                            <div class="col-md-4 offset-md-4 mt-2 mb-2">
                                                <button type="button" class="btn btn-outline-primary" title="Voltar para Receitas"
                                                    onclick="openModule('receitas');" style="width: 100%;">
                                                    <i class="fas fa-arrow-left pr-1"></i> Voltar
                                                </button>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>