<?php 
$entity = $this->view->entity; 
$role = $_SESSION['ROLE'];
?>
<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($role, $this->resourceCodes('update'), $this->moduleCodes('revenues'))): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-pen-square pr-1"></i>
                        Receita
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Detalhamento"
                                onclick="openDetails('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formUpdateRevenue" id="formUpdateRevenue"
                                enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="title">Situação*</label>
                                            <select name="status" id="status_1" class="form-control">
                                                <option value="1" <?php echo ($entity['status'] == '1' ? 'selected' : ''); ?>>Pagamento pendente</option>
                                                <option value="2" <?php echo ($entity['status'] == '2' ? 'selected' : ''); ?>>Pagamento concluída</option>
                                                <option value="3" <?php echo ($entity['status'] == '3' ? 'selected' : ''); ?>>Pagamento cancelada</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <hr>
                                        <div class="form-group">
                                            <label for="title">Título da Receita*</label>
                                            <input type="text" class="form-control" name="title" id="title" required maxlength="100"
                                                value="<?php echo $entity['title']; ?>" placeholder="Nome da Receita a ser paga">
                                        </div>
                                    </div>   
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="description">Descrição completa</label>
                                            <textarea name="description" id="description" class="form-control"
                                                rows="3" placeholder="Informe a descrição completo caso necessário"><?php echo $entity['title']; ?></textarea>
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-4">
                                        <div class="form-group">
                                            <label for="amount">Valor*</label>
                                            <input type="text" class="form-control" name="amount" id="amount" required placeholder="0,00"
                                                value="<?php echo number_format($entity['amount'], 2, ",", "."); ?>">
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-4">
                                        <div class="form-group">
                                            <label for="payment_type_uuid">Forma de Pagamento*</label>
                                            <select name="payment_type_uuid" id="payment_type_uuid" class="form-control" required>
                                                <option value="">Selecione</option>
                                                <?php foreach ($this->view->paymentTypes as $paymentType): ?>    
                                                    <option value="<?php echo $paymentType['uuid']; ?>"
                                                        <?php echo ($paymentType['uuid'] == $entity['payment_type_uuid'])
                                                            ? 'selected' : ''; ?>>
                                                        <?php echo $paymentType['name']; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-4">
                                        <div class="form-group">
                                            <label for="revenue_date">Data*</label>
                                            <input type="date" class="form-control" name="revenue_date" id="revenue_date" required
                                                value="<?php echo $entity['revenue_date']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-12"><hr></div>
                                    <div class="col-12 col-md-12">
                                        <div class="form-group">
                                            <label for="customer_uuid">Atribuir Cliente</label>
                                            <select name="customer_uuid" id="customer_uuid" class="form-control">
                                                <option value="">Selecione</option>
                                                <?php foreach ($this->view->customers as $customer): ?>
                                                    <option value="<?php echo $customer['uuid']; ?>"
                                                        <?php echo ($customer['uuid'] == $entity['customer_uuid'])
                                                            ? 'selected' : ''; ?>>
                                                        <?php echo $customer['name']; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12"><hr></div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="user_uuid">Anexar Arquivos</label>
                                            <input type="file" class="form-control" name="file[]" multiple id="file"
                                                accept="jpg,jpeg,png,pdf">
                                        </div>
                                        <div class="text-center mt-3">
                                            <b>Arquivos enviados:</b>
                                            <?php foreach ($this->view->files as $file) :  ?>
                                                <div class="my-3" id="box_<?php echo $file['uuid']; ?>">
                                                    <?php if ($this->isImage($file['file'])): ?>
                                                        <a href="<?php echo baseUrl . 'public/uploads/revenues/'
                                                            . $entity['uuid'] . '/' . $file['file']; ?>" target="_blank" title="Abrir o arquivo"
                                                            data-lightbox="image-1"
                                                            data-title="<?php echo $file['file']; ?>">
                                                            <span class="fa fa-image pr-1"></span>
                                                            <?php echo $file['file']; ?>
                                                        </a>
                                                    <?php else: ?>
                                                        <a href="<?php echo baseUrl . 'public/uploads/revenues/'
                                                            . $entity['uuid'] . '/' . $file['file']; ?>" target="_blank" title="Abrir o arquivo" class="">
                                                            <span class="fa fa-file pr-1"></span>
                                                            <?php echo $file['file']; ?>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($entity['status'] == '1'): ?>
                                                        <a onclick="deleteFile('<?php echo $file['uuid']; ?>');" style="cursor: pointer;" class="btn btn-danger btn-xs ml-1">
                                                            <span class="fa fa-trash"></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endforeach; ?>
                                            <?php if (empty($this->view->files)): ?>
                                                <p>Nenhum arquivo enviado</p>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <div class="col-md-8 mt-3 mb-2">
                                        <?php if ($entity['status'] == '1'): ?>
                                            <input type="hidden" name="uuid" id="id_receita" value="<?php echo $entity['uuid']; ?>">
                                            <button type="submit" class="btn btn-success w-100" id="btnSubmit" title="Salvar Receita">
                                                <i class="fa fa-save pr-1"></i> Salvar
                                            </button>
                                        <?php endif; ?>
                                    </div>
                                    <div class="col-md-4 mt-3 mb-2">
                                        <button type="button" class="btn btn-outline-primary w-100"
                                                onclick="openDetails('<?php echo $entity['uuid']; ?>');" title="Voltar para Detalhamento">
                                            <i class="fas fa-arrow-left pr-1"></i> Voltar
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function(){
            $("input[id=amount]").maskMoney({allowNegative: false, thousands:'.', decimal:',', affixesStay: true});

            $('#formUpdateRevenue').validate({
                submitHandler: function() {
                    let form_data = new FormData();         
                                        
                    $.each($("input[type='file']")[0].files, function (i, file) {
                        form_data.append('file_' + i, file);
                    });

                    form_data.append('title', $("#title").val());    
                    form_data.append('description', $("#description").val());    
                    form_data.append('amount', $("#amount").val());    
                    form_data.append('revenue_date', $("#revenue_date").val());    
                    form_data.append('customer_uuid', $("#customer_uuid").val());    
                    form_data.append('payment_type_uuid', $("#payment_type_uuid").val());    
                    form_data.append('status', $("#status_1").val());
                    form_data.append('uuid', $("#id_receita").val());    

                    $("#baseLoader").show();
                    $("#btnSubmit").attr('disabled', true);

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>receitas/processa-edicao",
                        cache: false,
                        contentType: false,
                        processData: false,
                        data: form_data,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        if (data.type === 'success') {
                            updateRevenue('<?php echo $entity['uuid']; ?>');
                        } else {
                            $("#baseLoader").hide();
                            $("#btnSubmit").attr('disabled', false);
                        }
                    }).fail(function() {
                        showInternalErrorAlert(); 
                        $("#baseLoader").hide();   
                        $("#btnSubmit").attr('disabled', false);
                    }); 

                    return false;
                }
            });
        });

        function deleteFile(uuid) {
            $("#box_" + uuid).fadeOut(999);

            $.ajax({
                type: "POST",
                url: "<?php echo baseUrl; ?>receitas/remove-arquivo",
                data: {
                    uuid: uuid
                },
                async: true
            });
        }
    </script>
<?php endif; ?>