<?php 
$data = $this->view->data; 
$role = $_SESSION['ROLE'];

$canView = $this->view->isAdmin || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('logs'));
?>
<?php if ($canView): ?>
    <section class="content" style="margin-left: 9px; margin-right: 9px; padding-top: 75px;">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body cardWrapper">
                    <div class="row">
                        <div class="col-6">
                            <h5 class="pt-2">
                                <i class="fas fa-th-list pr-1"></i>
                                Logs do Sistema
                            </h5>
                        </div>
                        <div class="col-6 text-right">
                            <a href="<?php echo baseUrl; ?>"  
                                class="btn btn-primary btnRadius" 
                                title="Página Inicial">
                                <i class="fas fa-home"></i> 
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="row">
                        <div class="col-12 col-md-4 offset-md-4 mb-3 text-center">
                            <a onclick="changeMonth();" style="width: 100%; cursor: pointer;" title="Alterar Mês">
                                <i class="fas fa-sync  pr-1"></i> Mês Atual:
                                <?php echo $this->view->month; ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body cardWrapperList">
                            <?php if (!$data): ?>
                                <div class="alert alert-info mt-3" role="alert">
                                    <i class="fas fa-info-circle pr-1"></i> Nenhuma informação até o momento.
                                </div>
                            <?php else: ?>
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover" id="tbl_logs" style="width: 100%;">
                                        <thead>
                                            <tr class="text-center" style="height: 30px;">
                                                <th style="font-size: 14px;">Data</th>
                                                <th style="font-size: 14px;">Horário</th>
                                                <th style="font-size: 14px;">Usuário</th>
                                                <th style="font-size: 14px;">Ação</th>
                                                <th style="font-size: 14px;">Situação</th>
                                                <th style="display: none;">IP</th>
                                                <th style="display: none;">Dispositivo</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($data as $entity): 
                                                $expData = explode(" ", $this->formatDateTime($entity['log_date']));

                                                ?>
                                                <tr class="text-center" style="cursor: pointer;" 
                                                    onclick="openLogDetails('<?php echo $entity['id']; ?>');">
                                                    <td style="font-size: 15px">
                                                        <?php echo $expData[0]; ?>
                                                    </td>
                                                    <td style="font-size: 15px">
                                                        <?php echo $expData[1]; ?>
                                                    </td>
                                                    <td style="font-size: 15px">
                                                        <?php echo $entity['username']; ?>
                                                    </td>
                                                    <td style="font-size: 15px;">
                                                        <?php 
                                                        $pos = strpos($entity['log_action'], 'REQUISIÇÃO BLOQUEADA:');
                                                        if ($pos === false):
                                                            echo $entity['log_action'];
                                                        else:
                                                            echo 'Requisiçao bloqueada!';
                                                        endif;
                                                        ?>
                                                    </td>
                                                    <td style="font-size: 15px">
                                                        <?php echo $entity['log_status']; ?>
                                                    </td>
                                                    <td style="display: none;">
                                                        <?php echo $entity['log_ip']; ?>
                                                    </td>
                                                    <td style="display: none;">
                                                        <?php echo $entity['log_user_agent']; ?>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        async function changeMonth() {
            $("#modalMonthTitle").html('<i class="fa fa-info-circle pr-2"></i> Alterar Mês');
            $("#modalMonthLoader").hide();
            $("#modalMonth").modal('show');
        }

        function selectMonth() {
            let month = $("#f_month").val();
            $("#modalMonthLoader").show();
            openModule('logs?m=' + month);
            $("#modalMonthLoader").hide();
            $("#modalMonth").modal('hide');
        }
    </script>
    <?php if ($data): ?>
        <script type="text/javascript">
            $(document).ready(function() {
                let buttonCommon = {
                    exportOptions: {
                        format: {
                            body: function ( data ) {
                                return data;
                            }
                        }
                    }
                };	

                $('#tbl_logs').DataTable({
                    "sDom": 'flBtip',
                    searching: true,
                    buttons: [
                        $.extend( true, {}, buttonCommon, {
                            extend: 'excel',
                            title: 'Lista de Categorias',
                            exportOptions: {columns: [0,1,2,3,4,5,6]}
                        })
                    ],
                    order: [ [0, "desc"] ],
                    columnDefs: [ 
                        {type: 'date-eu', targets: [0]},
                    ],
                    responsive: true,
                    info: true,
                    processing: true,
                    scrollCollapse: true,
                    paging: true,
                    "pageLength": 25,
                    "language": {
                        "sEmptyTable": "Nenhum registro encontrado",
                        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                        "sInfoPostFix": "",
                        "sInfoThousands": ".",
                        "sLengthMenu": "_MENU_ &nbsp;",
                        "sLoadingRecords": "Carregando...",
                        "sProcessing": "Processando...",
                        "sZeroRecords": "Nenhum registro encontrado",
                        "sSearch": "Filtrar",
                        "oPaginate": {
                            "sNext": "Próximo",
                            "sPrevious": "Anterior",
                            "sFirst": "Primeiro",
                            "sLast": "Último"
                        },
                        "oAria": {
                            "sSortAscending": ": Ordenar colunas de forma ascendente",
                            "sSortDescending": ": Ordenar colunas de forma descendente"
                        }
                    }
                });
            });

            async function openLogDetails(id) {
                $("#modalLargeResult").empty();
                $("#modalLargeTitle").html('<i class="fa fa-info-circle pr-2"></i> Informações do Log');
                $("#modalLargeLoader").show();
                $("#modalLarge").modal('show');

                await $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>logs/detalhes",
                    data: {
                        id:id,
                        target: '<?php echo $this->getTarget(); ?>',
                        month: $("#f_month").val()
                    },
                    async: true
                }).done(function(data) {
                    $("#modalLargeResult").html(data);
                    $("#modalLargeLoader").hide();
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#modalLargeLoader").hide();
                });
            
            }
        </script>
    <?php endif; ?>
<?php endif; ?>