<?php if ($this->view->acl['canView']): ?>
<section class="content" style="margin-left: 9px; margin-right: 9px; padding-top: 75px;">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body cardWrapper">
                <div class="row">
                    <div class="col-6">
                        <h5 class="pt-2">
                            <i class="fas fa-file pr-1"></i>
                            Relatórios
                        </h5>
                    </div>
                    <div class="col-6 text-right">
                        <a href="<?php echo baseUrl; ?>"  
                            class="btn btn-primary btnRadius" 
                            title="Página Inicial">
                            <i class="fas fa-home"></i> 
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body cardWrapper">
                        <form method="post" name="formExecuteReport" id="formExecuteReport">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="sis_module">Modulo*</label>
                                        <select class="form-control" name="sis_module" id="sis_module" required>
                                            <option value="">Selecione</option>
                                            <?php if ($this->view->isAdmin || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('schedules'))): ?>
                                                <option value="1">Agendamentos</option>
                                            <?php endif; ?>
                                            <?php if ($this->view->isAdmin || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('customers'))): ?>
                                                <option value="2">Clientes</option>
                                            <?php endif; ?>
                                            <?php if ($this->view->isAdmin || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('items'))): ?>
                                                <option value="3">Produtos</option>
                                            <?php endif; ?>
                                            <?php if ($this->view->isAdmin || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('services'))): ?>
                                                <option value="4">Serviços</option>
                                            <?php endif; ?>
                                            <?php if ($this->view->isAdmin || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('expenses'))): ?>
                                                <option value="5">Contas</option>
                                            <?php endif; ?>
                                            <?php if ($this->view->isAdmin || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('purchases'))): ?>
                                                <option value="6">Compras</option>
                                            <?php endif; ?>
                                            <?php if ($this->view->isAdmin || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('financial'))): ?>
                                                <option value="7">Fluxo de Caixa</option>
                                            <?php endif; ?>
                                            <?php if ($this->view->isAdmin || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('user'))): ?>
                                                <option value="8">Usuários</option>
                                            <?php endif; ?>
                                            <?php if ($this->view->isAdmin || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('logs'))): ?>
                                                <option value="9">Logs do Sistema</option>
                                            <?php endif; ?>
                                            <?php if ($this->view->isAdmin || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('support'))): ?>
                                                <option value="10">Chamados</option>
                                            <?php endif; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-6 col-md-4">
                                    <div class="form-group">
                                        <label for="initial_date">Data Inical*</label>
                                        <input type="date" class="form-control" name="initial_date" id="initial_date" required
                                            value="<?php echo date('Y-m'); ?>-01">
                                    </div>
                                </div>
                                <div class="col-6 col-md-4">
                                    <div class="form-group">
                                        <label for="final_date">Data Final*</label>
                                        <input type="date" class="form-control" name="final_date" id="final_date" required
                                            value="<?php echo date('Y-m'); ?>-30">
                                    </div>
                                </div>
                                <div class="col-6 col-md-3">
                                    <div class="form-group">
                                        <label for="order_type">Ordenação</label>
                                        <select class="form-control" name="order_type" id="order_type" required>
                                            <option value="1">Mais antigo para recente</option>
                                            <option value="2">Mais recente para antigo</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-6 col-md-3">
                                    <div class="form-group">
                                        <label for="report_limit">Limite*</label>
                                        <input type="number" class="form-control" name="report_limit" id="report_limit" min="0" max="1000" value="100"
                                            required>
                                    </div>
                                </div>
                                <div class="col-6 col-md-3">
                                    <div class="form-group">
                                        <label for="view_type">Exibição</label>
                                        <select class="form-control" name="view_type" id="view_type" required>
                                            <option value="1">Registros ativos</option>
                                            <option value="2">Registros excluídos</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-6 col-md-3">
                                    <br>
                                    <input type="hidden" name="target" value="<?php echo $this->getTarget(); ?>">
                                    <button type="submit" class="btn btn-primary btn-xl w-100 mt-2 btnRadius" id="btnSubmit">
                                        <span class="fa fa-file pr-1"></span> Gerar 
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div id="results"></div>
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function() {
        $('#formExecuteReport').validate({
            submitHandler: async function( form ){
                let dados = $( form ).serialize();

                $("#baseLoader").show();
                $("#btnSubmit").show('disabled', true);

                await $.ajax({
                    type: "POST",
                    url: "<?php echo baseUrl; ?>relatorios/gerar",
                    data: dados,
                    async: true
                }).done(function(data) {
                    $("#baseLoader").fadeOut();
                    $("#btnSubmit").attr('disabled', false);
                    $("#results").html(data);
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#baseLoader").fadeOut();
                    $("#btnSubmit").attr('disabled', false);
                });

                return false;
            }
        });
    });
</script>
<?php endif; ?>