<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('create'), $this->moduleCodes('tasks'))): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-plus-square pr-1"></i>
                        Tarefa
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Tarefas"
                                onclick="openModule('tarefas?m=<?php echo $_POST['month']; ?>');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formCreateTask" id="formCreateTask"
                                enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="title">Título*</label>
                                            <input type="text" class="form-control" name="title" id="title" required maxlength="150"
                                                placeholder="Nome da Tarefa">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="task_date">Data*</label>
                                            <input type="date" class="form-control" name="task_date" id="task_date" required>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="task_time">Hora</label>
                                            <input type="time" class="form-control" name="task_time" id="task_time">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="title">Descrição*</label>
                                            <textarea name="description" id="description" class="form-control" rows="5" required 
                                                placeholder="Descrição completa da Tarefa"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="description">Anexar Arquivos</label>
                                            <input type="file" class="form-control" name="file[]" multiple id="file"
                                                accept="jpg,jpeg,png,pdf">
                                        </div>
                                    </div>
                                    <div class="col-md-8 mt-3 mb-2">
                                        <button type="submit" class="btn btn-success w-100 " id="btnSubmit" title="Salvar Tarefa">
                                            <i class="fa fa-save pr-1"></i> Salvar
                                        </button>
                                    </div>
                                    <div class="col-md-4 mt-3 mb-2">
                                        <button type="button" class="btn btn-outline-primary w-100"
                                                onclick="openModule('tarefas?m=<?php echo $_POST['month']; ?>');" title="Voltar para Tarefas">
                                            <i class="fas fa-arrow-left pr-1"></i> Voltar
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function(){
            $('#formCreateTask').validate({
                submitHandler: function(){
                    let form_data = new FormData();         

                    $.each($("input[type='file']")[0].files, function (i, file) {
                        form_data.append('file_' + i, file);
                    });

                    form_data.append('title', $("#title").val());    
                    form_data.append('description', $("#description").val());    
                    form_data.append('task_date', $("#task_date").val());    
                    form_data.append('task_time', $("#task_time").val());    

                    $("#baseLoader").show();
                    $("#btnSubmit").show('disabled', true);

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>tarefas/processa-cadastro",
                        cache: false,
                        contentType: false,
                        processData: false,
                        data: form_data,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#baseLoader").hide();
                        $("#btnSubmit").attr('disabled', false);
                        $('#formCreateTask').trigger("reset");
                    }).fail(function() {
                        showInternalErrorAlert();
                        $("#baseLoader").hide();
                        $("#btnSubmit").attr('disabled', false);
                    });

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>