<?php
$data = $this->view->data;

$isAdmin = $_SESSION['ROLE_ADM'] == '1';
$role    = $_SESSION['ROLE'];

$canView    = $isAdmin || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('tasks'));
$canCreate  = $isAdmin || $this->acl($role, $this->resourceCodes('create'), $this->moduleCodes('tasks'));
$canUpdate  = $isAdmin || $this->acl($role, $this->resourceCodes('update'), $this->moduleCodes('tasks'));
$canDelete  = $isAdmin || $this->acl($role, $this->resourceCodes('delete'), $this->moduleCodes('tasks'));
?>
<?php if ($canView): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-tasks pr-1"></i>
                        Tarefas
                    </h1>
                </div>
                <div class="col-1">
                    <?php if ($canCreate): ?>
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item">
                                <?php if (!$this->view->reached_limit): ?>
                                    <button type="button" class="btn btn-outline-success" title="Adicionar Tarefa"
                                        onclick="createTask();" style="width: 100%;">
                                        <i class="fas fa-plus"></i> 
                                    </button>
                                <?php else: ?>
                                    <button type="button" class="btn btn-outline-primary" title="Limite de cadastros atingido, altere seu plano para aumentar o limite atual."
                                        onclick="openModule('planos-usuario');" style="width: 100%;">
                                        <i class="fas fa-sync"></i> 
                                    </button>
                                <?php endif; ?>
                            </li>
                        </ol>
                    <?php endif; ?>
                </div>
            </div>    
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <?php if ($this->view->reached_limit): ?>
                        <div class="alert bg-red" role="alert">
                            <span class="fa fa-info-circle pr-1"></span>
                            Limite de cadastros atingido! 
                            <a onclick="openModule('planos-usuario');" 
                                class="alert-link text-white" style="cursor: pointer;">Clique aqui</a> para aumentar o limite atual.
                        </div>
                    <?php else: ?>
                        <?php if (empty($_SESSION['PLAN']) && !$_SESSION['ROLE_ADM']): ?>
                            <div class="alert alert-info" role="alert">
                                <span class="fa fa-users pr-1"></span> 
                                Você está utilizando o Plano Gratuito. 
                                <a onclick="openModule('planos-usuario');" 
                                    class="alert-link text-white" style="cursor: pointer;">Clique aqui</a> para alterar e liberar todos os recursos do sistema.
                            </div>
                        <?php else: ?>
                            <div class="alert alert-info" role="alert">
                                <span class="fa fa-info-circle pr-1"></span> 
                                Cadastros disponíveis: <b><?php echo $this->view->total_free; ?></b> 
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                    <div class="row">
                        <div class="col-md-4 text-center">
                            <div class="card bg-info">
                                <div class="card-body">
                                    <span style="font-size: 1em"><i class="fa fa-calendar pr-1"></i> Pendentes</span> 
                                    <h3><?php echo $this->getTotalTasksByMonth('1', $this->view->month); ?></h3>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 text-center">
                            <div class="card bg-success">
                                <div class="card-body">
                                    <span style="font-size: 1em"><i class="fa fa-calendar-check pr-1"></i> Concluídas</span> 
                                    <h3><?php echo $this->getTotalTasksByMonth('2', $this->view->month); ?></h3>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 text-center">
                            <div class="card bg-danger">
                                <div class="card-body">
                                    <span style="font-size: 1em"><i class="fa fa-calendar-minus pr-1"></i> Canceladas</span> 
                                    <h3><?php echo $this->getTotalTasksByMonth('3', $this->view->month); ?></h3>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-4 offset-md-4 mb-3 text-center">
                            <a onclick="changeMonth();" style="width: 100%; cursor: pointer;" title="Alterar Mês">
                                <i class="fas fa-sync  pr-1"></i> Mês Atual: <?php echo $this->view->month; ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover" id="table_sv" style="width: 100%;">
                                    <thead>
                                        <tr class="text-center" style="height: 30px;">
                                            <th style="font-size: 14px;">Data</th>
                                            <th style="font-size: 14px;">Horário</th>
                                            <th style="font-size: 14px;">Tarefa</th>
                                            <th style="font-size: 14px;">Descrição</th>
                                            <th style="font-size: 14px;">Status</th>
                                            <th style="display: none;">Status</th>
                                            <th style="display: none;">Cadastrado em</th>
                                            <th style="display: none;">Atualizado em</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($data as $entity): ?>
                                            <?php 
                                            $today = strtotime(date('Y-m-d'));
                                            $entityDate = strtotime($entity['task_date']);
                                            $isLateClass = ($entityDate < $today && $entity['status'] == 1) ? 'alert alert-danger' : '';
                                            ?>
                                            <tr class="text-center <?php echo $isLateClass; ?>" style="cursor: pointer;" 
                                                onclick="openDetails('<?php echo $entity['uuid']; ?>');">
                                                <td style="font-size: 15px">
                                                    <?php echo $this->formatDate($entity['task_date']); ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo substr($entity['task_time'], 0, 5); ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['title']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['description']; ?>
                                                </td>
                                                <td style="width: 80px;">
                                                    <?php if ($entity['status'] == '1'): ?>
                                                            <i class="fa fa-circle pr-1" style="color: orange;"></i> 
                                                    <?php endif; ?>
                                                    <?php if ($entity['status'] == '2'): ?>
                                                            <i class="fa fa-circle pr-1" style="color: green;"></i> 
                                                    <?php endif; ?>
                                                    <?php if ($entity['status'] == '3'): ?>
                                                            <i class="fa fa-circle pr-1" style="color: red;"></i> 
                                                    <?php endif; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php if ($entity['status'] == '1'): ?>
                                                            Pendente
                                                    <?php endif; ?>
                                                    <?php if ($entity['status'] == '2'): ?>
                                                            Concluída
                                                    <?php endif; ?>
                                                    <?php if ($entity['status'] == '3'): ?>
                                                            Cancelada
                                                    <?php endif; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $this->formatDateTime($entity['created_at']); ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $this->formatDateTime($entity['updated_at']); ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php if (empty($_GET['m'])): ?>
        <script>
            $(document).ready(function() {
                $("#f_month").val('<?php echo date('Y-m'); ?>');
            });
        </script>
    <?php endif; ?>
    <script type="text/javascript">
        $(document).ready(function() {
            let buttonCommon = {
                exportOptions: {
                    format: {
                        body: function ( data ) {
                            return data;
                        }
                    }
                }
            };
        
            $('#table_sv').DataTable({
                "sDom": 'flBtip',
                searching: true,
                buttons: [
                    $.extend( true, {}, buttonCommon, {
                        extend: 'excel',
                        title: 'Tarefas',
                        exportOptions: {columns: [0,1,2,3,5,6,7]}
                    })
                ],
                order: [ [0, "desc"] ],
                columnDefs: [
                    {type: 'date-eu', targets: [0]},
                    {orderable: false, targets: [4]}
                ],
                responsive: true,
                info: true,
                processing: true,
                scrollCollapse: true,
                paging: true,
                "pageLength": 10,
                "language": {
                    "sEmptyTask": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ &nbsp;",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Filtrar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
        });

        function changeMonth() {
            $("#modalMonthTitle").html('<i class="fa fa-info-circle pr-2"></i> Alterar Mês');
            $("#modalMonthLoader").hide();
            $("#modalMonth").modal('show');           
        }

        function selectMonth() {
            let month = $("#f_month").val();
            $("#modalMonthLoader").show();
            openModule('tarefas?m=' + month);
            $("#modalMonthLoader").hide();
            $("#modalMonth").modal('hide');    
        }

        function openDetails(uuid) {
            $("#baseLoader").show();
            $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>tarefas/detalhes",
                data: {
                    uuid:uuid,
                    month: $("#f_month").val()
                },
                async: true
            }).done(function(data) {
                $("#sis_content").html(data);
                $("#baseLoader").hide();
            }).fail(function() {
                showInternalErrorAlert();
                $("#baseLoader").hide();
            });
        }
    </script>
    <?php if ($canCreate): ?>
        <script>
            function createTask() {
                $("#baseLoader").show();
                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>tarefas/cadastrar",
                    data: {
                        month: $("#f_month").val()
                    },  
                    async: true
                }).done(function(data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").hide();
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#baseLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canUpdate): ?>
        <script>
            function updateTask(uuid) {
                $("#baseLoader").show();
                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>tarefas/editar",
                    data: {uuid:uuid},
                    async: true
                }).done(function(data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").hide();
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#baseLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canDelete): ?>
        <script>
            function deleteTask(uuid) {
                $("#modalXL").modal('hide');
                $("#modalDeleteTitle").html('<i class="fa fa-trash pr-2"></i> Excluir Tarefa');
                $("#modalDeleteLoader").hide();
                $("#modalDelete").modal('show');
                $("#modalDeleteResult").html('<button type="button" class="btn btn-danger" title="Confirmar Exclusão" onclick="runDelete(\''+uuid+'\');"><i class="fa fa-trash"></i> CONFIRMAR E EXCLUIR</button>');
            }

            function runDelete(uuid) {
                if (uuid !== null) {
                    $("#modalDeleteLoader").show();
                    let month = $("#f_month").val();

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>tarefas/excluir",
                        data: {uuid: uuid},
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#modalDelete").modal('hide');
                        $("#modalXL").modal('hide');
                        openModule('tarefas?m=' + month);
                    }).fail(function() {
                        showInternalErrorAlert();
                        $("#modalDeleteLoader").hide();
                    });
                }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>