<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('tasks'))): ?>
    <?php $entity = $this->view->entity; ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-info-circle pr-1"></i>
                        Tarefa
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Tarefas"
                                onclick="openModule('tarefas?m=<?php echo $_POST['month']; ?>');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <?php if ($entity['status'] == '1'): ?>
                                            <i class="fa fa-circle pr-1" style="color: orange;"></i> Pendente
                                    <?php endif; ?>
                                    <?php if ($entity['status'] == '2'): ?>
                                            <i class="fa fa-circle pr-1" style="color: green;"></i> Concluída
                                    <?php endif; ?>
                                    <?php if ($entity['status'] == '3'): ?>
                                            <i class="fa fa-circle pr-1" style="color: red;"></i> Cancelada
                                    <?php endif; ?>
                                </div>
                                <div class="col-12"><hr></div>
                                <div class="col-md-6">
                                    <b>Data</b>
                                    <p><?php echo $this->formatDate($entity['task_date']); ?></p>
                                </div>
                                <div class="col-md-6">
                                    <b>Hora</b>
                                    <p>
                                        <?php if ($entity['task_time'] != '00:00:00'): ?>
                                            <?php echo $entity['task_time'] ? $entity['task_time'] : 'O dia todo'; ?>
                                        <?php else: ?>
                                            O dia todo
                                        <?php endif; ?>
                                    </p>
                                </div>
                                <div class="col-md-12">
                                    <b>Título</b>
                                    <p><?php echo $entity['title']; ?></p>
                                </div>
                                <div class="col-md-12">
                                    <b>Descrição</b>
                                    <p><?php echo $entity['description']; ?></p>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-md-12 text-center">
                                    <b>Arquivos Enviados</b>
                                    <?php if (!empty($this->view->files)) : ?>
                                        <?php foreach ($this->view->files as $file) : ?>
                                            <div>
                                                <a href="<?php echo baseUrl . 'public/uploads/tasks/' . $entity['uuid'] . '/' . $file['file']; ?>" 
                                                    target="_blank">
                                                    <?php echo $file['file']; ?>
                                                </a>
                                            </div>
                                        <?php endforeach; ?>
                                    <?php else : ?>
                                        <p class="text-center mt-2">Nenhum arquivo enviado</p>
                                    <?php endif; ?>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-6 text-left">
                                    <span class="fa fa-calendar pr-1"></span>
                                    <span>Cadastrada em</span> <br>
                                    <b>
                                        <?php echo $this->formatDateTime($entity['created_at']); ?>
                                    </b>
                                </div>
                                <div class="col-6 text-right">
                                    <?php if (!empty($entity['updated_at'])): ?>
                                        <span class="fa fa-calendar pr-1"></span>
                                        <span>Atualizada em</span> <br>
                                        <b>
                                            <?php echo $this->formatDateTime($entity['updated_at']); ?>
                                        </b>
                                    <?php endif; ?>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-6 col-lg-4 mt-2 mb-2">
                                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('delete'), $this->moduleCodes('tasks'))): ?>
                                                <button type="button" class="btn btn-outline-danger" title="Remover Tarefa"
                                                    onclick="deleteTask('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                                    <i class="fa fa-trash"></i> Remover
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                        <div class="col-md-6 col-lg-4 mt-2 mb-2">
                                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('update'), $this->moduleCodes('tasks'))): ?>
                                                <button type="button" class="btn btn-outline-success" title="Editar Tarefa"
                                                    onclick="updateTask('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                                    <i class="fa fa-pen pr-1"></i> Editar
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                        <div class="col-md-12 col-lg-4 mt-2 mb-2">
                                            <button type="button" class="btn btn-outline-primary" title="Voltar para Tarefas"
                                                 onclick="openModule('tarefas?m=<?php echo $_POST['month']; ?>');" style="width: 100%;">
                                                <i class="fas fa-arrow-left pr-1"></i> Voltar
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>