<?php 
$entity = $this->view->entity; 
$role = $_SESSION['ROLE'];
?>
<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($role, $this->resourceCodes('update'), $this->moduleCodes('tasks'))): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-pen-square pr-1"></i>
                        Tarefa
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary"
                                onclick="openDetails('<?php echo $entity['uuid']; ?>');" style="width: 100%;"
                                title="Voltar para Detalhamento">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formUpdateTask" id="formUpdateTask"
                                enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="name">Situação*</label>
                                            <select name="status" id="status_1" class="form-control">
                                                <option value="1" <?php echo ($entity['status'] == '1' ? 'selected' : ''); ?>>Tarefa pendente</option>
                                                <option value="2" <?php echo ($entity['status'] == '2' ? 'selected' : ''); ?>>Tarefa conclúida</option>
                                                <option value="3" <?php echo ($entity['status'] == '3' ? 'selected' : ''); ?>>Tarefa cancelada</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12"><hr></div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="name">Nome*</label>
                                            <input type="text" class="form-control" name="title" id="title" required
                                                value="<?php echo $entity['title']; ?>"
                                                   placeholder="Nome do Tarefa">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="task_date">Data*</label>
                                            <input type="date" class="form-control" name="task_date" id="task_date" required
                                                value="<?php echo $entity['task_date']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="task_time">Hora</label>
                                            <input type="time" class="form-control" name="task_time" id="task_time"
                                                value="<?php echo $entity['task_time']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="title">Descrição*</label>
                                            <textarea name="description" id="description" class="form-control" rows="10" required
                                                      placeholder="Descrição completa do Tarefa"><?php echo $entity['description']; ?></textarea>
                                        </div>
                                    </div>
                                    <div class="col-12"><hr></div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="user_uuid">Anexar Arquivos</label>
                                            <input type="file" class="form-control" name="file[]" multiple id="file"
                                                accept="jpg,jpeg,png,pdf">
                                        </div>
                                        <div class="text-center mt-3">
                                            <b>Arquivos enviados:</b>
                                            <?php foreach ($this->view->files as $file) :  ?>
                                                <div class="my-3" id="box_<?php echo $file['uuid']; ?>">
                                                    <?php if ($this->isImage($file['file'])): ?>
                                                        <a href="<?php echo baseUrl . 'public/uploads/tasks/'
                                                            . $entity['uuid'] . '/' . $file['file']; ?>" target="_blank" title="Abrir o arquivo"
                                                            data-lightbox="image-1"
                                                            data-title="<?php echo $file['file']; ?>">
                                                            <span class="fa fa-image pr-1"></span>
                                                            <?php echo $file['file']; ?>
                                                        </a>
                                                    <?php else: ?>
                                                        <a href="<?php echo baseUrl . 'public/uploads/tasks/'
                                                            . $entity['uuid'] . '/' . $file['file']; ?>" target="_blank" title="Abrir o arquivo" class="">
                                                            <span class="fa fa-file pr-1"></span>
                                                            <?php echo $file['file']; ?>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($entity['status'] == '1'): ?>
                                                        <a onclick="deleteFile('<?php echo $file['uuid']; ?>');" style="cursor: pointer;" class="btn btn-danger btn-xs ml-1">
                                                            <span class="fa fa-trash"></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endforeach; ?>
                                            <?php if (empty($this->view->files)): ?>
                                                <p>Nenhum arquivo enviado</p>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <div class="col-md-8 mt-3 mb-2">
                                        <?php if ($entity['status'] == '1'): ?>
                                            <input type="hidden" name="uuid" id="uuid" value="<?php echo $entity['uuid']; ?>">
                                            <button type="submit" class="btn btn-success w-100" id="btnSubmit" title="Salvar Tarefa">
                                                <i class="fa fa-save pr-1"></i> Salvar
                                            </button>
                                        <?php endif; ?>
                                    </div>
                                    <div class="col-md-4 mt-3 mb-2">
                                        <button type="button" class="btn btn-outline-primary w-100"
                                            onclick="openDetails('<?php echo $entity['uuid']; ?>');" title="Voltar para Detalhamento">
                                            <i class="fas fa-arrow-left pr-1"></i> Voltar
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function(){
            $('#formUpdateTask').validate({
                submitHandler: function() {
                    let form_data = new FormData();         
                    
                    $.each($("input[type='file']")[0].files, function (i, file) {
                        form_data.append('file_' + i, file);
                    });

                    form_data.append('title', $("#title").val());    
                    form_data.append('description', $("#description").val());    
                    form_data.append('task_date', $("#task_date").val());    
                    form_data.append('task_time', $("#task_time").val());    
                    form_data.append('status', $("#status_1").val());    
                    form_data.append('uuid', $("#uuid").val());    

                    $("#baseLoader").show();
                    $("#btnSubmit").show('disabled', true);

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>tarefas/processa-edicao",
                        cache: false,
                        contentType: false,
                        processData: false,
                        data: form_data,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        if (data.type === 'success') {
                            openDetails('<?php echo $entity['uuid']; ?>');
                        } else {
                            $("#baseLoader").hide();
                            $("#btnSubmit").attr('disabled', false);
                        }
                    }).fail(function() {
                        showInternalErrorAlert();
                        $("#baseLoader").hide();
                        $("#btnSubmit").attr('disabled', false);
                    });

                    return false;
                }
            });
        });

        function deleteFile(uuid) {
            $("#box_" + uuid).fadeOut(999);

            $.ajax({
                type: "POST",
                url: "<?php echo baseUrl; ?>tarefas/remove-arquivo",
                data: {
                    uuid: uuid
                },
                async: true
            });
        }
    </script>
<?php endif; ?>