<?php

$router = [];

/*
 * App routes
 */
$router['app'] = [
    ['namespace' => 'app', 'route' => '/', 'controller' => 'index', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/inicio', 'controller' => 'index', 'action' => 'index'],

    ['namespace' => 'app', 'route' => '/login', 'controller' => 'login', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/validar-token', 'controller' => 'login', 'action' => 'token-auth'],
    ['namespace' => 'app', 'route' => '/cancelar-token', 'controller' => 'login', 'action' => 'token-cancel'],
    ['namespace' => 'app', 'route' => '/esqueci-a-senha', 'controller' => 'login', 'action' => 'forgot-password'],
    ['namespace' => 'app', 'route' => '/validar-codigo', 'controller' => 'login', 'action' => 'code-validation'],
    ['namespace' => 'app', 'route' => '/alterar-senha', 'controller' => 'login', 'action' => 'change-password'],
    ['namespace' => 'app', 'route' => '/auth', 'controller' => 'login', 'action' => 'auth'],
    ['namespace' => 'app', 'route' => '/sair', 'controller' => 'login', 'action' => 'logout'],

    ['namespace' => 'app', 'route' => '/usuarios', 'controller' => 'user', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/usuarios/lista', 'controller' => 'user', 'action' => 'list'],
    ['namespace' => 'app', 'route' => '/usuarios/detalhes', 'controller' => 'user', 'action' => 'read'],
    ['namespace' => 'app', 'route' => '/usuarios/cadastrar', 'controller' => 'user', 'action' => 'create'],
    ['namespace' => 'app', 'route' => '/usuarios/processa-cadastro', 'controller' => 'user', 'action' => 'create-process'],
    ['namespace' => 'app', 'route' => '/usuarios/editar', 'controller' => 'user', 'action' => 'update'],
    ['namespace' => 'app', 'route' => '/usuarios/processa-edicao', 'controller' => 'user', 'action' => 'update-process'],
    ['namespace' => 'app', 'route' => '/usuarios/excluir', 'controller' => 'user', 'action' => 'delete'],
    ['namespace' => 'app', 'route' => '/usuarios/valor-existente', 'controller' => 'user', 'action' => 'field-exists'],
    ['namespace' => 'app', 'route' => '/usuarios/acl', 'controller' => 'user', 'action' => 'acl'],
    ['namespace' => 'app', 'route' => '/usuarios/altera-permissao', 'controller' => 'user', 'action' => 'alter-privilege'],
    ['namespace' => 'app', 'route' => '/usuarios/busca-responsavel', 'controller' => 'user', 'action' => 'search-responsible'],
    ['namespace' => 'app', 'route' => '/usuarios/folha-ponto', 'controller' => 'user', 'action' => 'time-sheets'],
    ['namespace' => 'app', 'route' => '/usuarios/folha-ponto/detalhes', 'controller' => 'user', 'action' => 'timesheet-details'],
    ['namespace' => 'app', 'route' => '/usuarios/folha-ponto/cadastrar', 'controller' => 'user', 'action' => 'timesheet-create'],
    ['namespace' => 'app', 'route' => '/usuarios/folha-ponto/editar', 'controller' => 'user', 'action' => 'timesheet-update'],
    ['namespace' => 'app', 'route' => '/usuarios/restaurar', 'controller' => 'user', 'action' => 'restore-process'],

    ['namespace' => 'app', 'route' => '/controle-acesso', 'controller' => 'role', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/controle-acesso/lista', 'controller' => 'role', 'action' => 'list'],
    ['namespace' => 'app', 'route' => '/controle-acesso/detalhes', 'controller' => 'role', 'action' => 'read'],
    ['namespace' => 'app', 'route' => '/controle-acesso/cadastrar', 'controller' => 'role', 'action' => 'create'],
    ['namespace' => 'app', 'route' => '/controle-acesso/processa-cadastro', 'controller' => 'role', 'action' => 'create-process'],
    ['namespace' => 'app', 'route' => '/controle-acesso/editar', 'controller' => 'role', 'action' => 'update'],
    ['namespace' => 'app', 'route' => '/controle-acesso/processa-edicao', 'controller' => 'role', 'action' => 'update-process'],
    ['namespace' => 'app', 'route' => '/controle-acesso/excluir', 'controller' => 'role', 'action' => 'delete'],
    ['namespace' => 'app', 'route' => '/controle-acesso/valor-existente', 'controller' => 'role', 'action' => 'field-exists'],
    ['namespace' => 'app', 'route' => '/controle-acesso/permissoes', 'controller' => 'privilege', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/controle-acesso/altera-permissao', 'controller' => 'privilege', 'action' => 'change-privilege'],

    ['namespace' => 'app', 'route' => '/formas-pagamento', 'controller' => 'payment-types', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/formas-pagamento/cadastrar', 'controller' => 'payment-types', 'action' => 'create'],
    ['namespace' => 'app', 'route' => '/formas-pagamento/processa-cadastro', 'controller' => 'payment-types', 'action' => 'create-process'],
    ['namespace' => 'app', 'route' => '/formas-pagamento/detalhes', 'controller' => 'payment-types', 'action' => 'read'],
    ['namespace' => 'app', 'route' => '/formas-pagamento/editar', 'controller' => 'payment-types', 'action' => 'update'],
    ['namespace' => 'app', 'route' => '/formas-pagamento/processa-edicao', 'controller' => 'payment-types', 'action' => 'update-process'],
    ['namespace' => 'app', 'route' => '/formas-pagamento/excluir', 'controller' => 'payment-types', 'action' => 'delete'],
    ['namespace' => 'app', 'route' => '/formas-pagamento/valor-existente', 'controller' => 'payment-types', 'action' => 'field-exists'],

    ['namespace' => 'app', 'route' => '/configuracoes', 'controller' => 'config', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/configuracoes/processa-edicao', 'controller' => 'config', 'action' => 'update-process'],

    ['namespace' => 'app', 'route' => '/logs', 'controller' => 'logs', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/logs/detalhes', 'controller' => 'logs', 'action' => 'read'],

    ['namespace' => 'app', 'route' => '/meu-perfil', 'controller' => 'my-profile', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/meu-perfil/processa-edicao', 'controller' => 'my-profile', 'action' => 'update-process'],
    ['namespace' => 'app', 'route' => '/meu-perfil/valor-existente', 'controller' => 'my-profile', 'action' => 'field-exists'],

    ['namespace' => 'app', 'route' => '/clientes', 'controller' => 'customers', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/clientes/detalhes', 'controller' => 'customers', 'action' => 'read'],
    ['namespace' => 'app', 'route' => '/clientes/cadastrar', 'controller' => 'customers', 'action' => 'create'],
    ['namespace' => 'app', 'route' => '/clientes/processa-cadastro', 'controller' => 'customers', 'action' => 'create-process'],
    ['namespace' => 'app', 'route' => '/clientes/editar', 'controller' => 'customers', 'action' => 'update'],
    ['namespace' => 'app', 'route' => '/clientes/processa-edicao', 'controller' => 'customers', 'action' => 'update-process'],
    ['namespace' => 'app', 'route' => '/clientes/excluir', 'controller' => 'customers', 'action' => 'delete'],
    ['namespace' => 'app', 'route' => '/clientes/valor-existente', 'controller' => 'customers', 'action' => 'field-exists'],
    ['namespace' => 'app', 'route' => '/clientes/busca-cliente', 'controller' => 'customers', 'action' => 'search'],

    ['namespace' => 'app', 'route' => '/servicos', 'controller' => 'services', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/servicos/cadastrar', 'controller' => 'services', 'action' => 'create'],
    ['namespace' => 'app', 'route' => '/servicos/processa-cadastro', 'controller' => 'services', 'action' => 'create-process'],
    ['namespace' => 'app', 'route' => '/servicos/detalhes', 'controller' => 'services', 'action' => 'read'],
    ['namespace' => 'app', 'route' => '/servicos/editar', 'controller' => 'services', 'action' => 'update'],
    ['namespace' => 'app', 'route' => '/servicos/processa-edicao', 'controller' => 'services', 'action' => 'update-process'],
    ['namespace' => 'app', 'route' => '/servicos/excluir', 'controller' => 'services', 'action' => 'delete'],
    ['namespace' => 'app', 'route' => '/servicos/valor-existente', 'controller' => 'services', 'action' => 'field-exists'],
    ['namespace' => 'app', 'route' => '/servicos/busca-servico', 'controller' => 'services', 'action' => 'search-service'],

    ['namespace' => 'app', 'route' => '/categorias', 'controller' => 'categories', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/categorias/cadastrar', 'controller' => 'categories', 'action' => 'create'],
    ['namespace' => 'app', 'route' => '/categorias/processa-cadastro', 'controller' => 'categories', 'action' => 'create-process'],
    ['namespace' => 'app', 'route' => '/categorias/detalhes', 'controller' => 'categories', 'action' => 'read'],
    ['namespace' => 'app', 'route' => '/categorias/editar', 'controller' => 'categories', 'action' => 'update'],
    ['namespace' => 'app', 'route' => '/categorias/processa-edicao', 'controller' => 'categories', 'action' => 'update-process'],
    ['namespace' => 'app', 'route' => '/categorias/excluir', 'controller' => 'categories', 'action' => 'delete'],
    ['namespace' => 'app', 'route' => '/categorias/valor-existente', 'controller' => 'categories', 'action' => 'field-exists'],

    ['namespace' => 'app', 'route' => '/subcategorias', 'controller' => 'subcategories', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/subcategorias/cadastrar', 'controller' => 'subcategories', 'action' => 'create'],
    ['namespace' => 'app', 'route' => '/subcategorias/processa-cadastro', 'controller' => 'subcategories', 'action' => 'create-process'],
    ['namespace' => 'app', 'route' => '/subcategorias/detalhes', 'controller' => 'subcategories', 'action' => 'read'],
    ['namespace' => 'app', 'route' => '/subcategorias/editar', 'controller' => 'subcategories', 'action' => 'update'],
    ['namespace' => 'app', 'route' => '/subcategorias/processa-edicao', 'controller' => 'subcategories', 'action' => 'update-process'],
    ['namespace' => 'app', 'route' => '/subcategorias/excluir', 'controller' => 'subcategories', 'action' => 'delete'],
    ['namespace' => 'app', 'route' => '/subcategorias/valor-existente', 'controller' => 'subcategories', 'action' => 'field-exists'],

    ['namespace' => 'app', 'route' => '/estoque', 'controller' => 'items', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/estoque/detalhes', 'controller' => 'items', 'action' => 'read'],
    ['namespace' => 'app', 'route' => '/estoque/cadastrar', 'controller' => 'items', 'action' => 'create'],
    ['namespace' => 'app', 'route' => '/estoque/processa-cadastro', 'controller' => 'items', 'action' => 'create-process'],
    ['namespace' => 'app', 'route' => '/estoque/editar', 'controller' => 'items', 'action' => 'update'],
    ['namespace' => 'app', 'route' => '/estoque/processa-edicao', 'controller' => 'items', 'action' => 'update-process'],
    ['namespace' => 'app', 'route' => '/estoque/excluir', 'controller' => 'items', 'action' => 'delete'],
    ['namespace' => 'app', 'route' => '/estoque/valor-existente', 'controller' => 'items', 'action' => 'field-exists'],
    ['namespace' => 'app', 'route' => '/estoque/busca-item', 'controller' => 'items', 'action' => 'search'],
    ['namespace' => 'app', 'route' => '/estoque/cadastrar-categoria', 'controller' => 'items', 'action' => 'create-category'],
    ['namespace' => 'app', 'route' => '/estoque/cadastrar-subcategoria', 'controller' => 'items', 'action' => 'create-subcategory'],
    ['namespace' => 'app', 'route' => '/estoque/cadastrar-fornecedor', 'controller' => 'items', 'action' => 'create-provider'],
    ['namespace' => 'app', 'route' => '/estoque/subcategorias', 'controller' => 'items', 'action' => 'subcategories'],

    ['namespace' => 'app', 'route' => '/contas', 'controller' => 'expenses', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/contas/cadastrar', 'controller' => 'expenses', 'action' => 'create'],
    ['namespace' => 'app', 'route' => '/contas/processa-cadastro', 'controller' => 'expenses', 'action' => 'create-process'],
    ['namespace' => 'app', 'route' => '/contas/detalhes', 'controller' => 'expenses', 'action' => 'read'],
    ['namespace' => 'app', 'route' => '/contas/editar', 'controller' => 'expenses', 'action' => 'update'],
    ['namespace' => 'app', 'route' => '/contas/processa-edicao', 'controller' => 'expenses', 'action' => 'update-process'],
    ['namespace' => 'app', 'route' => '/contas/excluir', 'controller' => 'expenses', 'action' => 'delete'],
    ['namespace' => 'app', 'route' => '/contas/remove-arquivo', 'controller' => 'expenses', 'action' => 'delete-file'],
    ['namespace' => 'app', 'route' => '/contas/alterar-situacao', 'controller' => 'expenses', 'action' => 'change-status'],
    ['namespace' => 'app', 'route' => '/contas/processa-situacao', 'controller' => 'expenses', 'action' => 'process-status'],
    ['namespace' => 'app', 'route' => '/contas/cadastrar-cliente', 'controller' => 'expenses', 'action' => 'create-customer'],
    ['namespace' => 'app', 'route' => '/contas/cadastrar-fornecedor', 'controller' => 'expenses', 'action' => 'create-provider'],
    ['namespace' => 'app', 'route' => '/contas/arquivos', 'controller' => 'expenses', 'action' => 'files'],
    ['namespace' => 'app', 'route' => '/contas/enviar-arquivos', 'controller' => 'expenses', 'action' => 'upload-files'],
    ['namespace' => 'app', 'route' => '/contas/processa-upload', 'controller' => 'expenses', 'action' => 'upload-process'],
    ['namespace' => 'app', 'route' => '/contas/restaurar', 'controller' => 'expenses', 'action' => 'restore-process'],

    ['namespace' => 'app', 'route' => '/financeiro', 'controller' => 'financial', 'action' => 'index'],

    ['namespace' => 'app', 'route' => '/agendamentos', 'controller' => 'schedules', 'action' => 'index'],
	['namespace' => 'app', 'route' => '/agendamentos/cadastrar', 'controller' => 'schedules', 'action' => 'create'],
	['namespace' => 'app', 'route' => '/agendamentos/processa-cadastro', 'controller' => 'schedules', 'action' => 'create-process'],
	['namespace' => 'app', 'route' => '/agendamentos/detalhes', 'controller' => 'schedules', 'action' => 'read'],
	['namespace' => 'app', 'route' => '/agendamentos/editar', 'controller' => 'schedules', 'action' => 'update'],
	['namespace' => 'app', 'route' => '/agendamentos/processa-edicao', 'controller' => 'schedules', 'action' => 'update-process'],
	['namespace' => 'app', 'route' => '/agendamentos/excluir', 'controller' => 'schedules', 'action' => 'delete'],
	['namespace' => 'app', 'route' => '/agendamentos/remove-arquivo', 'controller' => 'schedules', 'action' => 'delete-file'],
	['namespace' => 'app', 'route' => '/agendamentos/cadastrar-cliente', 'controller' => 'schedules', 'action' => 'create-customer'],
    ['namespace' => 'app', 'route' => '/agendamentos/alterar-situacao', 'controller' => 'schedules', 'action' => 'change-status'],
    ['namespace' => 'app', 'route' => '/agendamentos/processa-situacao', 'controller' => 'schedules', 'action' => 'process-status'],
    ['namespace' => 'app', 'route' => '/agendamentos/arquivos', 'controller' => 'schedules', 'action' => 'files'],
    ['namespace' => 'app', 'route' => '/agendamentos/enviar-arquivos', 'controller' => 'schedules', 'action' => 'upload-files'],
    ['namespace' => 'app', 'route' => '/agendamentos/processa-upload', 'controller' => 'schedules', 'action' => 'upload-process'],
    ['namespace' => 'app', 'route' => '/agendamentos/restaurar', 'controller' => 'schedules', 'action' => 'restore-process'],

    ['namespace' => 'app', 'route' => '/relatorios', 'controller' => 'reports', 'action' => 'index'],
	['namespace' => 'app', 'route' => '/relatorios/gerar', 'controller' => 'reports', 'action' => 'generate'],
    
	['namespace' => 'app', 'route' => '/chamados', 'controller' => 'support', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/chamados/abre-chamado', 'controller' => 'support', 'action' => 'create-process'],
    ['namespace' => 'app', 'route' => '/chamados/detalhes', 'controller' => 'support', 'action' => 'read'],
    ['namespace' => 'app', 'route' => '/chamados/editar', 'controller' => 'support', 'action' => 'update'],
    ['namespace' => 'app', 'route' => '/chamados/processa-edicao', 'controller' => 'support', 'action' => 'update-process'],
    ['namespace' => 'app', 'route' => '/chamados/excluir', 'controller' => 'support', 'action' => 'delete'],
    ['namespace' => 'app', 'route' => '/chamados/remove-arquivo', 'controller' => 'support', 'action' => 'delete-file'],
    ['namespace' => 'app', 'route' => '/chamados/alterar-situacao', 'controller' => 'support', 'action' => 'change-status'],
    ['namespace' => 'app', 'route' => '/chamados/processa-situacao', 'controller' => 'support', 'action' => 'process-status'],
    ['namespace' => 'app', 'route' => '/chamados/mensagens', 'controller' => 'support', 'action' => 'messages'],
	['namespace' => 'app', 'route' => '/chamados/processa-mensagem', 'controller' => 'support', 'action' => 'message-process'],
    ['namespace' => 'app', 'route' => '/chamados/busca-modulo', 'controller' => 'support', 'action' => 'modules-search'],
    ['namespace' => 'app', 'route' => '/chamados/lista-responsibles', 'controller' => 'support', 'action' => 'responsibles-list'],
    ['namespace' => 'app', 'route' => '/chamados/processa-responsavel', 'controller' => 'support', 'action' => 'responsible-process'],
    ['namespace' => 'app', 'route' => '/chamados/excluir-responsavel', 'controller' => 'support', 'action' => 'delete-responsible'],
    ['namespace' => 'app', 'route' => '/chamados/arquivos', 'controller' => 'support', 'action' => 'files'],
    ['namespace' => 'app', 'route' => '/chamados/enviar-arquivos', 'controller' => 'support', 'action' => 'upload-files'],
    ['namespace' => 'app', 'route' => '/chamados/processa-upload', 'controller' => 'support', 'action' => 'upload-process'],
    ['namespace' => 'app', 'route' => '/chamados/excluir-mensagem', 'controller' => 'support', 'action' => 'delete-message'],
    ['namespace' => 'app', 'route' => '/chamados/restaurar', 'controller' => 'support', 'action' => 'restore-process'],

    ['namespace' => 'app', 'route' => '/notificacoes', 'controller' => 'notifications', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/notificacoes/conteudo', 'controller' => 'notifications', 'action' => 'content'],
    ['namespace' => 'app', 'route' => '/notificacoes/ler', 'controller' => 'notifications', 'action' => 'read'],
    ['namespace' => 'app', 'route' => '/notificacoes/excluir', 'controller' => 'notifications', 'action' => 'delete'],
    ['namespace' => 'app', 'route' => '/notificacoes/valida-modulo', 'controller' => 'notifications', 'action' => 'module-validation'],
    ['namespace' => 'app', 'route' => '/notificacoes/lida', 'controller' => 'notifications', 'action' => 'mark-read'],
    ['namespace' => 'app', 'route' => '/notificacoes/lidas', 'controller' => 'notifications', 'action' => 'mark-reads'],
    ['namespace' => 'app', 'route' => '/notificacoes/excluidas', 'controller' => 'notifications', 'action' => 'delete-all'],

    ['namespace' => 'app', 'route' => '/mensagens', 'controller' => 'messages', 'action' => 'index'],
    ['namespace' => 'app', 'route' => '/mensagens/checa-mensagens', 'controller' => 'messages', 'action' => 'check-messages'],
    ['namespace' => 'app', 'route' => '/mensagens/valida-modulo', 'controller' => 'messages', 'action' => 'module-validation'],
    ['namespace' => 'app', 'route' => '/mensagens/ler', 'controller' => 'messages', 'action' => 'read'],
    ['namespace' => 'app', 'route' => '/mensagens/lidas', 'controller' => 'messages', 'action' => 'mark-reads'],
    ['namespace' => 'app', 'route' => '/mensagens/excluir', 'controller' => 'messages', 'action' => 'delete'],
    ['namespace' => 'app', 'route' => '/mensagens/ler-todas', 'controller' => 'messages', 'action' => 'read-all'],
    ['namespace' => 'app', 'route' => '/mensagens/excluir-todas', 'controller' => 'messages', 'action' => 'delete-all'],
];

/*
 * Client routes
 */
$router['client'] = [
	['namespace' => 'client', 'route' => '/cliente', 'controller' => 'index', 'action' => 'index'],
	['namespace' => 'client', 'route' => '/cliente/', 'controller' => 'index', 'action' => 'index'],
	
	['namespace' => 'client', 'route' => '/cliente/login', 'controller' => 'login', 'action' => 'index'],
	['namespace' => 'client', 'route' => '/cliente/auth',  'controller' => 'login', 'action' => 'auth'],
	['namespace' => 'client', 'route' => '/cliente/token',  'controller' => 'login', 'action' => 'token'],
	['namespace' => 'client', 'route' => '/cliente/sair',  'controller' => 'login', 'action' => 'logout'],

	['namespace' => 'client', 'route' => '/cliente/meus-dados', 'controller' => 'profile', 'action' => 'index'],
	['namespace' => 'client', 'route' => '/cliente/meus-dados/processa-edicao', 'controller' => 'profile', 'action' => 'update-process'],

    ['namespace' => 'client', 'route' => '/cliente/relatorios', 'controller' => 'reports', 'action' => 'index'],
	['namespace' => 'client', 'route' => '/cliente/relatorios/gerar', 'controller' => 'reports', 'action' => 'generate'],
    
    ['namespace' => 'client', 'route' => '/cliente/chamados', 'controller' => 'support', 'action' => 'index'],
    ['namespace' => 'client', 'route' => '/cliente/chamados/abre-chamado', 'controller' => 'support', 'action' => 'create-process'],
    ['namespace' => 'client', 'route' => '/cliente/chamados/detalhes', 'controller' => 'support', 'action' => 'read'],
    ['namespace' => 'client', 'route' => '/cliente/chamados/editar', 'controller' => 'support', 'action' => 'update'],
    ['namespace' => 'client', 'route' => '/cliente/chamados/processa-edicao', 'controller' => 'support', 'action' => 'update-process'],
    ['namespace' => 'client', 'route' => '/cliente/chamados/excluir', 'controller' => 'support', 'action' => 'delete'],
    ['namespace' => 'client', 'route' => '/cliente/chamados/remove-arquivo', 'controller' => 'support', 'action' => 'delete-file'],
    ['namespace' => 'client', 'route' => '/cliente/chamados/alterar-situacao', 'controller' => 'support', 'action' => 'change-status'],
    ['namespace' => 'client', 'route' => '/cliente/chamados/processa-situacao', 'controller' => 'support', 'action' => 'process-status'],
    ['namespace' => 'client', 'route' => '/cliente/chamados/mensagens', 'controller' => 'support', 'action' => 'messages'],
    ['namespace' => 'client', 'route' => '/cliente/chamados/processa-mensagem', 'controller' => 'support', 'action' => 'message-process'],
    ['namespace' => 'client', 'route' => '/cliente/chamados/arquivos', 'controller' => 'support', 'action' => 'files'],

    ['namespace' => 'client', 'route' => '/cliente/notificacoes', 'controller' => 'notifications', 'action' => 'index'],
    ['namespace' => 'client', 'route' => '/cliente/notificacoes/conteudo', 'controller' => 'notifications', 'action' => 'content'],
    ['namespace' => 'client', 'route' => '/cliente/notificacoes/ler', 'controller' => 'notifications', 'action' => 'read'],
    ['namespace' => 'client', 'route' => '/cliente/notificacoes/excluir', 'controller' => 'notifications', 'action' => 'delete'],
    ['namespace' => 'client', 'route' => '/cliente/notificacoes/valida-modulo', 'controller' => 'notifications', 'action' => 'module-validation'],
    ['namespace' => 'client', 'route' => '/cliente/notificacoes/lida', 'controller' => 'notifications', 'action' => 'mark-read'],
    ['namespace' => 'client', 'route' => '/cliente/notificacoes/lidas', 'controller' => 'notifications', 'action' => 'mark-reads'],
    ['namespace' => 'client', 'route' => '/cliente/notificacoes/excluidas', 'controller' => 'notifications', 'action' => 'delete-all'],

    ['namespace' => 'client', 'route' => '/cliente/mensagens', 'controller' => 'messages', 'action' => 'index'],
    ['namespace' => 'client', 'route' => '/cliente/mensagens/checa-mensagens', 'controller' => 'messages', 'action' => 'check-messages'],
    ['namespace' => 'client', 'route' => '/cliente/mensagens/valida-modulo', 'controller' => 'messages', 'action' => 'module-validation'],
    ['namespace' => 'client', 'route' => '/cliente/mensagens/ler', 'controller' => 'messages', 'action' => 'read'],
    ['namespace' => 'client', 'route' => '/cliente/mensagens/lidas', 'controller' => 'messages', 'action' => 'mark-reads'],
    ['namespace' => 'client', 'route' => '/cliente/mensagens/excluir', 'controller' => 'messages', 'action' => 'delete'],
    ['namespace' => 'client', 'route' => '/cliente/mensagens/ler-todas', 'controller' => 'messages', 'action' => 'read-all'],
    ['namespace' => 'client', 'route' => '/cliente/mensagens/excluir-todas', 'controller' => 'messages', 'action' => 'delete-all'],

    ['namespace' => 'client', 'route' => '/cliente/agendamentos', 'controller' => 'schedules', 'action' => 'index'],
    ['namespace' => 'client', 'route' => '/cliente/agendamentos/detalhes', 'controller' => 'schedules', 'action' => 'read'],
    ['namespace' => 'client', 'route' => '/cliente/agendamentos/arquivos', 'controller' => 'schedules', 'action' => 'files'],
    ['namespace' => 'client', 'route' => '/cliente/agendamentos/responder-agendamento', 'controller' => 'schedules', 'action' => 'answer-schedule'],
    ['namespace' => 'client', 'route' => '/cliente/agendamentos/processa-resposta', 'controller' => 'schedules', 'action' => 'process-answer'],
];

$systemDir = match ($_SERVER['HTTP_HOST']) {
    'localhost' => baseDir,
    default => "",
};

$app = new Core\Init\Bootstrap($router, $systemDir);