<?php if ($this->view->acl['canCreateSubcategory']): ?>
    <form method="post" name="formCreateItemSubcategory" id="formCreateItemSubcategory">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label>Categoria</label>
                    <input type="text" class="form-control" disabled value="<?php echo $this->view->category['title']; ?>">
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label for="title">Título*</label>
                    <input type="text" class="form-control" name="title" required maxlength="150"
                        placeholder="Título da Subcategoria">
                </div>
            </div>
            <div class="col-md-12 mt-3 mb-2">
                <input type="hidden" name="target" value="<?php echo $this->getTarget(); ?>">
                <input type="hidden" name="category_id" value="<?php echo $this->view->category['id']; ?>">
                <button type="submit" class="btn btn-success w-100 btnRadius" id="btnSubmitSubcategory" title="Salvar Subcategoria">
                    <i class="fa fa-save pr-1"></i> Salvar
                </button>
            </div>
        </div>
    </form>
    <script>
        $(document).ready(function(){
            $('#formCreateItemSubcategory').validate({
                submitHandler: async function( form ){
                    let dados = $( form ).serialize();

                    $("#modalGreenMidLoader").show();
                    $("#btnSubmitSubcategory").attr('disabled', true);
                    
                    await $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>subcategorias/processa-cadastro",
                        data: dados,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        if (data.type === 'success') {
                            $("#subcategory_id").append('<option value="'+data.id+'" selected>'+data.id+' - '+data.name+'</option>');
                            $("#modalGreenMid").modal('hide');   
                        }
        
                        $("#btnSubmitSubcategory").attr('disabled', false);
                    }).fail(function() {
                        showInternalErrorAlert();
                        $("#modalGreenMidLoader").hide();
                        $("#btnSubmitSubcategory").attr('disabled', false);
                    });

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>