<?php if ($_SESSION['ROLE_ADM'] == '0' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('create'), $this->moduleCodes('schedules'))): ?>
    <?php
    $canCreateCustomer = $_SESSION['ROLE_ADM'] == '0' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('create'), $this->moduleCodes('customers'));
    $canCreateService = $_SESSION['ROLE_ADM'] == '0' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('create'), $this->moduleCodes('services'));
    ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-plus-square pr-1"></i>
                        Agendamento
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary"
                                onclick="openModule('agendamentos?m=<?php echo $_POST['month']; ?>');" style="width: 100%;" title="Voltar para Agendamentos">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formCreateSchedule" id="formCreateSchedule"
                                enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-12 col-md-4">
                                        <div class="form-group">
                                            <label for="service_uuid">Situação do Agendamento*</label>
                                            <select name="status" id="status_1" class="form-control" required>
                                                <option value="1">Agendar no Sistema</option>
                                                <option value="2">Concluído</option>
                                                <option value="3">Cancelado</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12"><hr></div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="service_uuid">
                                                Atribuir Serviço*
                                            </label>
                                            <?php if ($canCreateService): ?>
                                                <a onclick="newService();" class="text-success" 
                                                    style="cursor: pointer; float: right" title="Adicionar Serviço">
                                                    <span class="fa fa-plus-circle"></span>
                                                </a> 
                                            <?php endif; ?>
                                            <select name="service_uuid" id="service_uuid" class="form-control" required
                                                onchange="getServiceDescription();">
                                                <option value="">Selecione</option>
                                                <?php foreach ($this->view->services as $service): ?>
                                                    <option value="<?php echo $service['uuid']; ?>">
                                                        <?php echo $service['title']; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>   
                                    <div class="col-12"><hr></div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="customer_uuid">Atribuir Cliente</label>
                                            <?php if ($canCreateCustomer): ?>
                                                <a onclick="newCustomer();" class="text-success" 
                                                    style="cursor: pointer; float: right" title="Adicionar Cliente">
                                                    <span class="fa fa-plus-circle"></span>
                                                </a> 
                                            <?php endif; ?>
                                            <select name="customer_uuid" id="customer_uuid" class="form-control">
                                                <option value="">Selecione</option>
                                                <?php foreach ($this->view->customers as $customer): ?>
                                                    <option value="<?php echo $customer['uuid']; ?>">
                                                        <?php echo $customer['name']; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <input type="checkbox" name="send_email_customer" id="send_email_customer" value="1" class="mr-1"> Enviar email de notificação para o cliente.</small>
                                    </div>
                                    <div class="col-12"><hr></div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="title">Responsável</label>
                                            <select name="user_uuid" id="user_uuid" class="form-control">
                                                <option value="">Selecione</option>
                                                <?php foreach ($this->view->users as $user): ?>
                                                    <option value="<?php echo $user['uuid']; ?>">
                                                        <?php echo $user['name'] . ' (' . $user['email'] . ')'; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <input type="checkbox" name="send_email_user" id="send_email_user" value="1" class="mr-1"> Enviar email de notificação para o responsável.</small>
                                    </div>
                                    <div class="col-12"><hr></div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="schedule_date">Data*</label>
                                            <input type="date" class="form-control" name="schedule_date" id="schedule_date" required>
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="schedule_time">Horário*</label>
                                            <input type="time" class="form-control" name="schedule_time" id="schedule_time" required>
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="amount">Valor*</label>
                                            <input type="text" class="form-control" name="amount" id="amount" required placeholder="0,00">
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="payment_type_uuid">Forma de Pagamento</label>
                                            <select name="payment_type_uuid" id="payment_type_uuid" class="form-control">
                                                <option value="">Selecione</option>
                                                <?php foreach ($this->view->paymentTypes as $paymentType): ?>    
                                                    <option value="<?php echo $paymentType['uuid']; ?>">
                                                        <?php echo $paymentType['name']; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12"><hr></div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="description">Informações Adicionais</label>
                                            <textarea rows="1" class="form-control" name="description" id="description"
                                                placeholder="Informações adicionais para o agendamento"></textarea>
                                        </div>
                                    </div>   
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="description">Anexar Arquivos</label>
                                            <input type="file" class="form-control" name="file[]" multiple id="file"
                                                accept="jpg,jpeg,png,pdf">
                                        </div>
                                    </div>
                                    <div class="col-md-8 mt-3 mb-2">
                                        <button type="submit" class="btn btn-success w-100" id="btnSubmit" title="Salvar Agendamento">
                                            <i class="fa fa-save pr-1"></i> Salvar
                                        </button>
                                    </div>
                                    <div class="col-md-4 mt-3 mb-2">
                                        <button type="button" class="btn btn-outline-primary w-100"
                                                onclick="openModule('agendamentos?m=<?php echo $_POST['month']; ?>');" title="Voltar para Agendamentos">
                                            <i class="fas fa-arrow-left pr-1"></i> Voltar
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function(){
            $("input[id=amount]").maskMoney({allowNegative: false, thousands:'.', decimal:',', affixesStay: true});
            $('#formCreateSchedule').validate({
                submitHandler: function() {
                    let form_data = new FormData();         

                    $.each($("input[type='file']")[0].files, function (i, file) {
                        form_data.append('file_' + i, file);
                    });

                    form_data.append('description', $("#description").val());    
                    form_data.append('amount', $("#amount").val());    
                    form_data.append('payment_type_uuid', $("#payment_type_uuid").val());    
                    form_data.append('schedule_date', $("#schedule_date").val());    
                    form_data.append('schedule_time', $("#schedule_time").val());    
                    form_data.append('customer_uuid', $("#customer_uuid").val());    
                    form_data.append('service_uuid', $("#service_uuid").val());    
                    form_data.append('user_uuid', $("#user_uuid").val());    
                    form_data.append('status', $("#status_1").val());

                    form_data.append('target', '<?php echo $this->getTarget(); ?>');

                    if ($('#send_email_customer').is(':checked')) {
                        form_data.append('send_email_customer', $("#send_email_customer").val());    
                    }

                    if ($('#send_email_user').is(':checked')) {
                        form_data.append('send_email_user', $("#send_email_user").val());    
                    }

                    $("#baseLoader").show();
                    $("#btnSubmit").attr('disabled', true);

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>agendamentos/processa-cadastro",
                        cache: false,
                        contentType: false,
                        processData: false,
                        data: form_data,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#baseLoader").hide();
                        $("#btnSubmit").attr('disabled', false);
                        $('#formCreateSchedule').trigger("reset");
                    }).fail(function() {
                        showInternalErrorAlert(); 
                        $("#baseLoader").hide();   
                        $("#btnSubmit").attr('disabled', false);
                    }); 

                    return false;
                }
            });
        }); 

        function getServiceDescription() {
            let serviceUuid = $("#service_uuid").val();
            if (serviceUuid !== '') {
                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>agendamentos/detalhes-servico",
                    data: {uuid: serviceUuid, target: '<?php echo $this->getTarget(); ?>'},
                    async: true
                }).done(function(data) {
                    $("#amount").val(data);
                }).fail(function() {
                    $("#amount").val('0,00');
                });
            } else {
                $("#amount").val('0,00');
            }
        }
    </script>
    <?php if ($canCreateService): ?>
        <script>
            function newService() {
                $("#modalGreenLargeResult").empty();
                $("#modalGreenLarge").modal('hide');
                $("#modalGreenLargeTitle").html('<i class="fa fa-plus-circle pr-1"></i> Adicionar Serviço');
                $("#modalGreenLargeLoader").show();
                $("#modalGreenLarge").modal('show');

                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>agendamentos/cadastrar-servico",
                    data: {
                        target: '<?php echo $this->getTarget(); ?>'
                    },
                    async: true
                }).done(function(data) {
                    $("#modalGreenLargeResult").html(data);
                    $("#modalGreenLargeLoader").hide();
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#modalGreenLargeLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canCreateCustomer): ?>
        <script>
            function newCustomer() {
                $("#modalGreenLargeResult").empty();
                $("#modalGreenLarge").modal('hide');
                $("#modalGreenLargeTitle").html('<i class="fa fa-plus-circle pr-1"></i> Adicionar Cliente');
                $("#modalGreenLargeLoader").show();
                $("#modalGreenLarge").modal('show');

                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>agendamentos/cadastrar-cliente",
                    data: {
                        target: '<?php echo $this->getTarget(); ?>'
                    },
                    async: true
                }).done(function(data) {
                    $("#modalGreenLargeResult").html(data);
                    $("#modalGreenLargeLoader").hide();
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#modalGreenLargeLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
<?php endif; ?>