<?php
$aclData = $this->view->acl;
$canCreate = $aclData['canCreate'];
$canCreateCustomer = $aclData['canCreateCustomer'];

if ($canCreate): ?>
    <style>
        .select2-selection {
            height: 38px !important;
        }
    </style>
    <section class="content" style="margin-left: 9px; margin-right: 9px; padding-top: 75px;">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body cardWrapper">
                    <div class="row">
                        <div class="col-6">
                            <h5 class="pt-2">
                                <i class="fas fa-plus-square pr-1"></i>
                                Agendamento
                            </h5>
                        </div>
                        <div class="col-6 text-right">
                            <button type="button" class="btn btn-primary btnRadius" 
                                title="Voltar para Agendamentos"
                                onclick="openModule('agendamentos');">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body cardWrapperBody">
                            <form method="post" name="formCreateSchedule" id="formCreateSchedule"
                                enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="title">Título*</label>
                                            <input type="text" class="form-control" name="title" id="title" required maxlength="150"
                                                placeholder="Título do Agendamento">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="schedule_date">Data*</label>
                                            <input type="date" class="form-control" name="schedule_date" id="schedule_date" required
                                                value="<?php echo date('Y-m-d'); ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="schedule_time">Hora</label>
                                            <input type="time" class="form-control" name="schedule_time" id="schedule_time">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="description">Informações adicionais</label>
                                            <textarea name="description" id="description" class="form-control" rows="5"  
                                                placeholder="Informações adicionais do Agendamento"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="customer_id">Atribuir Cliente</label>
                                            <?php if ($canCreateCustomer): ?>
                                                <a onclick="newCustomer();" class="text-success"
                                                    style="cursor: pointer; float: right" title="Adicionar Cliente">
                                                    <span class="fa fa-plus-circle"></span>
                                                </a>
                                            <?php endif; ?>
                                            <select name="customer_id" id="customer_id" class="form-control" style="width: 100%;">
                                                <option value="">Clique para Pesquisar</option>
                                            </select>
                                        </div>
                                        <div id="sendMailCustomer" style="display: none;" class="mb-3">
                                            <input type="checkbox" name="send_email_customer" id="send_email_customer" value="1" class="mr-1"> 
                                            <small style="position: relative; top: -2px;">Enviar notificação sobre a operação.</small>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="title">Atribuir Usuário</label>
                                            <select name="user_id" id="user_id" class="form-control" style="width: 100%;">
                                                <option value="">Clique para Pesquisar</option>
                                            </select>
                                        </div>
                                        <div id="sendMailUser" style="display: none;">
                                            <input type="checkbox" name="send_email_user" id="send_email_user" value="1" class="mr-1"> 
                                            <small style="position: relative; top: -2px;">Enviar notificação sobre a operação.</small>
                                        </div>
                                    </div>
                                    <div class="col-md-6 offset-md-3 mt-2 mb-3">
                                        <div class="bg-info text-center p-3 btnRadius">
                                            <span style="font-size: 20px; color: #fff; ">
                                                <i class="fa fa-file-upload pr-1"></i> <b>Enviar Arquivos</b>
                                            </span>
                                            <div class="form-group text-center">
                                                <label for="file"><small style="color: #fff;">
                                                    <i>(jpg, jpeg, png, gif, pdf)</i></small>
                                                </label>
                                                <input type="file" class="form-control inputUpload" name="file[]" multiple id="file"
                                                    accept=".png,.jpg,.jpeg,.gif,.pdf">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12 mt-1">
                                        <div class="row">
                                            <div class="col-md-6 offset-md-3 mb-2">
                                                <button type="submit" class="btn btn-success w-100 btnRadius" id="btnSubmit" title="Salvar Agendamento">
                                                    <i class="fa fa-save pr-1"></i> Salvar
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 text-center mb-3">
                    <button type="button" class="btn btn-default btn-sm btnRadius"
                        onclick="openModule('agendamentos');" 
                        title="Voltar para Agendamentos">
                        <i class="fas fa-arrow-left pr-1"></i> Voltar
                    </button>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function() {
            $('#customer_id').select2({
                ajax: {
                    type: 'POST',
                    url: '<?php echo baseUrl; ?>clientes/busca-cliente',
                    dataType: 'json',
                    processResults: function (data) {
                        if(data[0]) {
                            if (data[0].id) {
                                $("#sendMailCustomer").removeAttr("style");
                            }
                        }

                        return {
                            results: data
                        };
                    }
                }
            });

            $('#user_id').select2({
                ajax: {
                    type: 'POST',
                    url: '<?php echo baseUrl; ?>usuarios/busca-responsavel',
                    dataType: 'json',
                    processResults: function (data) {
                        if(data[0]) {
                            if (data[0].id) {
                                $("#sendMailUser").removeAttr("style");
                            }
                        } 

                        return {
                            results: data
                        };
                    }
                }
            });

            $('#formCreateSchedule').validate({
                submitHandler: async function(){
                    let form_data = new FormData();         

                    $.each($("input[type='file']")[0].files, function (i, file) {
                        form_data.append('file_' + i, file);
                    });
                    
                    form_data.append('title', $("#title").val());    
                    form_data.append('description', $("#description").val());    
                    form_data.append('schedule_date', $("#schedule_date").val());    
                    form_data.append('schedule_time', $("#schedule_time").val());    
                    form_data.append('target', '<?php echo $this->getTarget(); ?>');
                    
                    form_data.append('user_id', $("#user_id").val());    
                    if ($('#send_email_user').is(':checked')) {
                        form_data.append('send_email_user', $("#send_email_user").val());    
                    }

                    form_data.append('customer_id', $("#customer_id").val());    
                    if ($('#send_email_customer').is(':checked')) {
                        form_data.append('send_email_customer', $("#send_email_customer").val());    
                    }
                    
                    $("#baseLoader").show();
                    $("#btnSubmit").show('disabled', true);

                    await $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>agendamentos/processa-cadastro",
                        cache: false,
                        contentType: false,
                        processData: false,
                        data: form_data,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        if (data.type === 'success') {
                            openScheduleDetails(data.id);
                        } else {
                            $("#baseLoader").fadeOut();
                            $("#btnSubmit").attr('disabled', false);
                        }
                    }).fail(function() {
                        showInternalErrorAlert();
                        $("#baseLoader").fadeOut();
                        $("#btnSubmit").attr('disabled', false);
                    });

                    return false;
                }
            });
        });
    </script>
    <?php if ($canCreateCustomer): ?>
        <script>
            async function newCustomer() {
                $("#modalGreenLargeResult").empty();
                $("#modalGreenLarge").modal('hide');
                $("#modalGreenLargeTitle").html('<i class="fa fa-plus-circle pr-1"></i> Adicionar Cliente');
                $("#modalGreenLargeLoader").show();
                $("#modalGreenLarge").modal('show');

                await $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>agendamentos/cadastrar-cliente",
                    data: {
                        target: '<?php echo $this->getTarget(); ?>'
                    },
                    async: true
                }).done(function (data) {
                    $("#modalGreenLargeResult").html(data);
                    $("#modalGreenLargeLoader").hide();
                }).fail(function () {
                    showInternalErrorAlert();
                    $("#modalGreenLargeLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
<?php endif; ?>