<form method="post" name="formCreateServiceSchedule" id="formCreateServiceSchedule">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label for="title">Título*</label>
                <input type="text" class="form-control" name="title" id="service_title" required maxlength="150"
                    placeholder="Nome do Serviço">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="price">Valor*</label>
                <input type="text" class="form-control" name="price" id="service_price" placeholder="0,00" required>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label for="title">Descrição</label>
                <textarea name="description" id="service_description" class="form-control" rows="2"  
                    placeholder="Descrição completa do Serviço"></textarea>
            </div>
        </div>
        <div class="col-md-12 mt-3 mb-2">
            <input type="hidden" name="target" value="<?php echo $this->getTarget(); ?>">
            <button type="submit" class="btn btn-success w-100" id="btnSubmitService" title="Salvar Serviço">
                <i class="fa fa-save pr-1"></i> Salvar
            </button>
        </div>
    </div>
</form>
<script>
    $(document).ready(function(){
        $("input[id=service_price]").maskMoney({allowNegative: false, thousands:'.', decimal:',', affixesStay: true});

        $('#formCreateServiceSchedule').validate({
            rules: {
                title: {
                    remote: { 
                        type: "post",
                        url: "<?php echo baseUrl; ?>servicos/valor-existente",
                    }
                },
            },
            messages: {
                title: {
                    remote: "Serviço já cadastrado"
                },
            },
            submitHandler: function( form ){
                let dados = $( form ).serialize();

                $("#modalGreenLargeLoader").show();
                $("#btnSubmitService").show('disabled', true);
                
                $.ajax({
                    type: "POST",
                    url: "<?php echo baseUrl; ?>servicos/processa-cadastro",
                    data: dados,
                    dataType: 'json',
                    async: true
                }).done(function(data) {
                    showAlert(data.type, data.title, data.msg, data.pos);
                    $("#modalGreenLarge").modal('hide');    
                    $("#amount").val(data.price);
                    $("#service_uuid").append('<option value="'+data.uuid+'" selected>'+data.titlesv+'</option>');
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#modalGreenLargeLoader").hide();
                    $("#btnSubmitService").attr('disabled', false);
                });

                return false;
            }
        });
    });
</script>