<?php 
$data = $this->view->data; 

$isAdmin = $_SESSION['ROLE_ADM'] == '1';
$role    = $_SESSION['ROLE'];

$canView    = $isAdmin || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('schedules'));
$canCreate  = $isAdmin || $this->acl($role, $this->resourceCodes('create'), $this->moduleCodes('schedules'));
$canUpdate  = $isAdmin || $this->acl($role, $this->resourceCodes('update'), $this->moduleCodes('schedules'));
$canDelete  = $isAdmin || $this->acl($role, $this->resourceCodes('delete'), $this->moduleCodes('schedules'));
?>
<?php if ($canView): ?>
    <section class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-file-invoice-dollar pr-1"></i>
                        Agendamentos
                    </h1>
                </div>
                <div class="col-1">
                    <?php if ($canCreate): ?>
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item">
                                <button type="button" class="btn btn-outline-success"
                                    onclick="createSchedule();" style="width: 100%;" title="Novo Agendamento">
                                    <i class="fas fa-plus"></i> 
                                </button>
                            </li>
                        </ol>
                    <?php endif; ?>
                </div>
            </div>
            <div class="row">
                <div class="col-12 p-3">
                    <div class="row">
                        <div class="col-4 bg-secondary text-center py-2 pt-3">
                            <span style="font-size: 0.9em">Agendados</span> <br>
                            <h3><?php echo $this->getTotalSchedules('1'); ?></h3>
                        </div>
                        <div class="col-4 bg-primary text-center py-2 pt-3">
                            <span style="font-size: 0.9em">Concluídos</span> <br>
                            <h3><?php echo $this->getTotalSchedules('2'); ?></h3>
                        </div>
                        <div class="col-4 bg-secondary text-center py-2 pt-3">
                            <span style="font-size: 0.9em">Cancelados</span> <br>
                            <h3><?php echo $this->getTotalSchedules('3'); ?></h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover" id="table_agendamentos" style="width: 100%">
                                    <thead>
                                        <tr class="text-center" style="height: 30px;">
                                            <th style="font-size: 14px;">Data</th>
                                            <th style="font-size: 14px;">Horário</th>
                                            <th style="font-size: 14px;">Serviço</th>
                                            <th style="font-size: 14px;">Cliente</th>
                                            <th style="font-size: 14px;">Valor</th>
                                            <th style="font-size: 14px;">Status</th>
                                            <th style="display: none;">Descrição</th>
                                            <th style="display: none;">Forma de Pagamento</th>
                                            <th style="display: none;">Status</th>
                                            <th style="display: none;">Cadastrado em</th>
                                            <th style="display: none;">Atualizado em</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($data as $entity): ?>
                                            <tr class="text-center" style="cursor: pointer;" 
                                                onclick="openDetails('<?php echo $entity['uuid']; ?>');">
                                                <td style="font-size: 15px">
                                                    <?php echo $this->formatDate($entity['schedule_date']); ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo substr($entity['schedule_time'], 0, 5); ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['serviceName']; ?>
                                                </td> 
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['customerName'] ?? 'Não informado'; ?>
                                                </td> 
                                                <td style="font-size: 15px">
                                                    <?php echo number_format($entity['amount'], 2, ",","."); ?>
                                                </td> 
                                                <td style="width: 80px;">
                                                    <?php if ($entity['status'] == '1'): ?>
                                                        <i class="fa fa-circle" style="color: orange;"></i>
                                                    <?php endif; ?>
                                                    <?php if ($entity['status'] == '2'): ?>
                                                        <i class="fa fa-circle" style="color: green;"></i>
                                                    <?php endif; ?>
                                                    <?php if ($entity['status'] == '3'): ?>
                                                        <i class="fa fa-circle" style="color: red;"></i>
                                                    <?php endif; ?>
                                                </td>  
                                                <td style="display: none;">
                                                    <?php echo $entity['description']; ?>
                                                </td> 
                                                <td style="display: none;">
                                                    <?php echo $entity['paymentTypeName']; ?>   
                                                </td> 
                                                <td style="display: none;">
                                                    <?php echo ($entity['status'] == '1') ? 'Agendado' : ''; ?>
                                                    <?php echo ($entity['status'] == '2') ? 'Concluído' : ''; ?>
                                                    <?php echo ($entity['status'] == '3') ? 'Cancelado' : ''; ?>
                                                </td> 
                                                <td style="display: none;">
                                                    <?php echo $this->formatDateTime($entity['created_at']); ?>
                                                </td> 
                                                <td style="display: none;">
                                                    <?php echo $this->formatDateTime($entity['updated_at']); ?>
                                                </td> 
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script type="text/javascript">
        $(document).ready(function() {
            let buttonCommon = {
                exportOptions: {
                    format: {
                        body: function ( data, row, column ) {
                            return  column === 4  ?
                                parseFloat(data.replace(/[.]/g, '' ).replace( ',', '.' )).toLocaleString('en-IN',
                                {minimumFractionDigits: 2 , maximumFractionDigits: 2}) : data;
                        }
                    }
                }
            };	

            $('#table_agendamentos').DataTable({
                "sDom": 'flBtip',
                searching: true,
                buttons: [
                    $.extend( true, {}, buttonCommon, {
                        extend: 'excel',
                        title: 'Agendamentos',
                        exportOptions: {columns: [0,1,2,3,4,6,7,8,9,10]}
                    })
                ],
                order: [ [0, "desc"] ],
                columnDefs: [
                    {type: 'date-eu', targets: [0]},
                    {type: 'valoresemreais', targets: [4]},
                    {orderable: false, targets: [5]},
                ],
                responsive: true,
                info: true,
                processing: true,
                scrollCollapse: true,
                paging: true,
                "pageLength": 25,
                "language": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ &nbsp;",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Filtrar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
        });

        function openDetails(uuid) {
            $("#baseLoader").show();
            $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>agendamentos/detalhes",
                data: {uuid:uuid},
                async: true
            }).done(function(data) {
                $("#sis_content").html(data);
                $("#baseLoader").hide();
            }).fail(function() {
                showInternalErrorAlert();
                $("#baseLoader").hide();
            });
        }
    </script>
    <?php if ($canCreate): ?>
        <script>
            function createSchedule() {
                $("#baseLoader").show();
                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>agendamentos/cadastrar",
                    async: true
                }).done(function(data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").hide();
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#baseLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canUpdate): ?>
        <script>
            function updateSchedule(uuid) {
                $("#baseLoader").show();
                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>agendamentos/editar",
                    data: {uuid:uuid},
                    async: true
                }).done(function(data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").hide();
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#baseLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canDelete): ?>
        <script>
            function deleteSchedule(uuid) {
                $("#modalXL").modal('hide');
                $("#modalDeleteTitle").html('<i class="fa fa-trash pr-2"></i> Remover Agendamento');
                $("#modalDeleteLoader").hide();
                $("#modalDelete").modal('show');
                $("#modalDeleteResult").html('<button type="button" class="btn btn-default" onclick="runDelete(\''+uuid+'\');"><i class="fa fa-trash"></i> CONFIRMAR E EXCLUIR</button>');
            }   

            function runDelete(uuid) {
                if (uuid !== null) {
                    $("#modalDeleteLoader").show();

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>agendamentos/excluir",
                        data: {uuid: uuid},
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#modalDelete").modal('hide');
                        $("#modalXL").modal('hide');
                        openModule('agendamentos');
                    }).fail(function() {
                        showInternalErrorAlert();
                        $("#modalDeleteLoader").hide();
                    });
                }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>