<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('schedules'))): ?>
    <?php $entity = $this->view->entity; ?>
    <section class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-info-circle pr-1"></i>
                        Agendado para <?php echo $this->formatDate($entity['schedule_date']); ?>
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Agendamentos"
                                onclick="openModule('agendamentos');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body"> 
                            <div class="row">
                                <div class="col-md-12">
                                    <b>Situação:</b>
                                    <?php if ($entity['status'] == '1'): ?>
                                            <i class="fa fa-circle pl-1" style="color: orange;"></i> Agendado
                                    <?php endif; ?>
                                    <?php if ($entity['status'] == '2'): ?>
                                            <i class="fa fa-circle pl-1" style="color: green;"></i> Concluído
                                    <?php endif; ?>
                                    <?php if ($entity['status'] == '3'): ?>
                                            <i class="fa fa-circle pl-1" style="color: red;"></i> Cancelado
                                    <?php endif; ?>
                                    <hr>
                                </div>
                                <div class="col-md-6">
                                    <b>Serviço:</b>
                                    <p>
                                        <?php echo $entity['serviceName']; ?> 
                                        <br> 
                                        <?php echo $entity['serviceDescription']; ?>
                                    </p>
                                </div>
                                <?php if (!empty($entity['customerName'])): ?>
                                    <div class="col-md-6">
                                        <b>Dados do Cliente:</b>
                                        <p>
                                            <?php echo $entity['customerName']; ?><br>
                                            <?php echo $entity['customerEmail'] ?? 'Não informado'; ?><br>
                                            <?php echo $entity['customerCellphone'] ?? 'Não informado'; ?>
                                        </p>
                                    </div>
                                <?php endif; ?>
                                <div class="col-md-12"><hr></div>
                                <div class="col-md-4">
                                    <b>Data do Agendamento:</b>
                                    <p><?php echo $this->formatDate($entity['schedule_date']); ?> - <?php echo substr($entity['schedule_time'], 0, 5); ?></p>
                                </div>
                                <div class="col-md-4">
                                    <b>Valor</b>
                                    <p>R$ <?php echo number_format($entity['amount'], 2, ",", "."); ?></p>
                                </div>
                                <div class="col-md-4">
                                    <b>Forma de Pagamento:</b>
                                    <p>
                                        <?php echo $entity['paymentTypeName'] ?? 'Não informada'; ?>    
                                    </p>
                                </div>
                                <?php if (!empty($entity['description'])): ?>
                                    <div class="col-md-12">
                                        <hr>
                                        <b>Informações Adicionais: </b>
                                        <?php echo $entity['description']; ?>
                                    </div>
                                <?php endif; ?>
                                <?php if (!empty($entity['file'])): ?>
                                    <div class="col-12">
                                        <hr>
                                        <b>Anexo: </b>
                                        <a href="<?php echo baseUrl . 'public/uploads/schedules/' . $entity['file']; ?>" target="_blank">
                                            <?php echo $entity['file']; ?>
                                        </a>
                                    </div>
                                <?php endif; ?>
                                <div class="col-md-12"><hr></div>
                                <div class="col-12 col-md-6">
                                    <b>Cadastrado em: </b> 
                                    <p><?php echo $this->formatDateTime($entity['created_at']); ?></p>
                                </div>
                                <div class="col-12 col-md-6 ">
                                    <?php if (!empty($entity['updated_at'])): ?>
                                        <b>Atualizado em: </b>
                                        <p><?php echo $this->formatDateTime($entity['updated_at']); ?></p>
                                    <?php endif; ?>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-md-12">
                                    <div class="row">
                                        <?php if ($entity['status'] == '1'): ?>
                                            <div class="col-md-4 col-lg-4 mt-2 mb-2">
                                                <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('delete'), $this->moduleCodes('schedules'))): ?>
                                                    <button type="button" class="btn btn-outline-danger"  title="Remover Agendamento"
                                                        onclick="deleteSchedule('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                                        <i class="fa fa-trash"></i> Remover
                                                    </button>
                                                <?php endif; ?>
                                            </div>
                                            <div class="col-md-4 col-lg-4 mt-2 mb-2">
                                                <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('update'), $this->moduleCodes('schedules'))): ?>
                                                    <button type="button" class="btn btn-outline-success"  title="Editar Agendamento"
                                                        onclick="updateSchedule('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                                        <i class="fa fa-pen pr-1"></i> Editar
                                                    </button>
                                                <?php endif; ?>
                                            </div>
                                            <div class="col-md-4 col-lg-4 mt-2 mb-2">
                                                <button type="button" class="btn btn-outline-primary" title="Voltar para Agendamentos"
                                                    onclick="openModule('agendamentos');" style="width: 100%;">
                                                    <i class="fas fa-arrow-left pr-1"></i> Voltar
                                                </button>
                                            </div>
                                        <?php else: ?>
                                            <div class="col-md-4 offset-md-4 mt-2 mb-2">
                                                <button type="button" class="btn btn-outline-primary" title="Voltar para Agendamentos"
                                                    onclick="openModule('agendamentos');" style="width: 100%;">
                                                    <i class="fas fa-arrow-left pr-1"></i> Voltar
                                                </button>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>