<?php 
$isAdmin = $this->view->isAdmin;
$aclData = $this->view->acl;
$canUpdate = $aclData['canUpdate'];
$canCreateCustomer = $aclData['canCreateCustomer'];

if ($canUpdate): ?>
    <?php $entity = $this->view->entity; ?>
    <style>
        .select2-selection {
            height: 38px !important;
        }
    </style>
    <section class="content" style="margin-left: 9px; margin-right: 9px; padding-top: 75px;">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body cardWrapper">
                    <div class="row">
                        <div class="col-6">
                            <h5 class="pt-2">
                                <i class="fas fa-pen-square pr-1"></i>
                                Agendamento <small class="text-gray">#<?php echo $entity['id']; ?></small>
                            </h5>
                        </div>
                        <div class="col-6 text-right">
                            <button type="button" class="btn btn-primary btnRadius"
                                onclick="openScheduleDetails('<?php echo $entity['id']; ?>');"
                                title="Voltar para Detalhamento">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body cardWrapperBody">
                            <form method="post" name="formUpdateSchedule" id="formUpdateSchedule"
                                enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label>Código</label>
                                            <input type="text" class="form-control" value="<?php echo $entity['id']; ?>" disabled>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label for="status">Situação</label>
                                            <select name="status" id="status_1" class="form-control">
                                                <option value="1" <?php echo ($entity['status'] == '1' ? 'selected' : ''); ?>>1 - Pendente</option>
                                                <option value="2" <?php echo ($entity['status'] == '2' ? 'selected' : ''); ?>>2 - Confirmado</option>
                                                <option value="3" <?php echo ($entity['status'] == '3' ? 'selected' : ''); ?>>3 - Concluído</option>
                                                <option value="4" <?php echo ($entity['status'] == '4' ? 'selected' : ''); ?>>4 - Cancelado</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="title">Título*</label>
                                            <input type="text" class="form-control" name="title" id="title" required
                                                value="<?php echo $entity['title']; ?>"
                                                   placeholder="Título do Agendamento">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="schedule_date">Data*</label>
                                            <input type="date" class="form-control" name="schedule_date" id="schedule_date" required
                                                value="<?php echo $entity['schedule_date']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="schedule_time">Hora</label>
                                            <input type="time" class="form-control" name="schedule_time" id="schedule_time"
                                                value="<?php echo $entity['schedule_time']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="description">Informações adicionais</label>
                                            <textarea name="description" id="description" class="form-control" rows="5" 
                                                      placeholder="Informações adicionais do Agendamento"><?php echo $entity['description']; ?></textarea>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="customer_id">Atribuir Cliente</label>
                                            <?php if ($canCreateCustomer): ?>
                                                <a onclick="newCustomer();" class="text-success"
                                                    style="cursor: pointer; float: right" title="Adicionar Cliente">
                                                    <span class="fa fa-plus-circle"></span>
                                                </a>
                                            <?php endif; ?>
                                            <select name="customer_id" id="customer_id" class="form-control" style="width: 100%;">
                                                <option value="">Clique para Pesquisar</option>
                                            </select>
                                        </div>
                                        <div id="sendMailCustomer" style="display: none;" class="mb-3">
                                            <input type="checkbox" name="send_email_customer" id="send_email_customer" value="1" class="mr-1"> 
                                            <small style="position: relative; top: -2px;">Enviar notificação sobre a operação.</small>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="user_id">Atribuir Usuário</label>
                                            <select name="user_id" id="user_id" class="form-control" style="width: 100%;">
                                                <option value="">Clique para Pesquisar</option>
                                            </select>
                                        </div>
                                        <div id="sendMailUser" style="display: none;">
                                            <input type="checkbox" name="send_email_user" id="send_email_user" value="1" class="mr-1"> 
                                            <small style="position: relative; top: -2px;">Enviar notificação sobre a operação.</small>
                                        </div>
                                    </div>
                                    <div class="col-md-6 offset-md-3">
                                        <?php if ($this->view->files): ?>
                                            <div class="text-center mb-3">
                                                <b>Arquivos enviados:</b>
                                                <?php foreach ($this->view->files as $file) :  ?>
                                                    <div class="my-2" id="box_<?php echo $file['id']; ?>">
                                                        <?php if ($this->isFile($file['file'], 'schedules/' . $_POST['id'])): ?>
                                                            <?php if ($this->isImage($file['file'])): ?>
                                                                <a href="<?php echo baseUrl . 'public/uploads/schedules/'
                                                                    . $entity['id'] . '/' . $file['file']; ?>" target="_blank" title="Abrir o arquivo"
                                                                    data-lightbox="image-1"
                                                                    data-title="<?php echo $file['file']; ?>">
                                                                    <span class="fa fa-image pr-1"></span>
                                                                    <?php echo $file['file']; ?>
                                                                </a>
                                                            <?php else: ?>
                                                                <a href="<?php echo baseUrl . 'public/uploads/schedules/'
                                                                    . $entity['id'] . '/' . $file['file']; ?>" target="_blank" title="Abrir o arquivo" class="">
                                                                    <span class="fa fa-file-pdf pr-1"></span>
                                                                    <?php echo $file['file']; ?>
                                                                </a>
                                                            <?php endif; ?>
                                                        
                                                        <?php else: ?>
                                                            <span class="fa fa-info-circle pr-1"></span>
                                                            <?php echo $file['file']; ?> <small class="text-red">(Arquivo indisponível)</small>
                                                        <?php endif; ?>
                                                        <?php if ($entity['status'] == '1' || $isAdmin): ?>
                                                            <a onclick="deleteFile('<?php echo $file['id']; ?>');" 
                                                                style="cursor: pointer; font-size: 10px;" 
                                                                class="btn btn-danger btn-xs ml-1 btnRadius">
                                                                <span class="fa fa-trash"></span>
                                                            </a>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endforeach; ?>
                                                <?php if (empty($this->view->files)): ?>
                                                    <p>Nenhum arquivo enviado</p>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                    <div class="col-md-6 offset-md-3 mt-2 mb-3">
                                        <div class="bg-info text-center p-3 btnRadius">
                                            <span style="font-size: 20px; color: #fff; ">
                                                <i class="fa fa-file-upload pr-1"></i> <b>Enviar Arquivos</b>
                                            </span>
                                            <div class="form-group text-center">
                                                <label for="file"><small style="color: #fff;">
                                                    <i>(jpg, jpeg, png, gif, pdf)</i></small>
                                                </label>
                                                <input type="file" class="form-control inputUpload" name="file[]" multiple id="file"
                                                    accept=".png,.jpg,.jpeg,.gif,.pdf">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12 mt-1">
                                        <div class="row">
                                            <?php if ($entity['status'] != '2' || $isAdmin): ?>
                                                <div class="col-md-6 offset-md-3 mb-2">
                                                    <input type="hidden" name="id" id="id" value="<?php echo $entity['id']; ?>">
                                                    <button type="submit" class="btn btn-success w-100 btnRadius" id="btnSubmit" title="Salvar Agendamento">
                                                        <i class="fa fa-save pr-1"></i> Salvar
                                                    </button>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 text-center mb-3">
                    <button type="button" class="btn btn-default btn-sm btnRadius"
                        onclick="openScheduleDetails('<?php echo $entity['id']; ?>');" 
                        title="Voltar para Detalhamento">
                        <i class="fas fa-arrow-left pr-1"></i> Voltar
                    </button>
                </div>
            </div>
        </div>
    </section>
    <?php if ($entity['status'] != '2' || $isAdmin): ?>
        <script>
            $(document).ready(function() {
                $('#customer_id').select2({
                    ajax: {
                        type: 'POST',
                        url: '<?php echo baseUrl; ?>clientes/busca-cliente',
                        dataType: 'json',
                        processResults: function (data) {
                            if(data[0]) {
                                if (data[0].id) {
                                    $("#sendMailCustomer").removeAttr("style");
                                }
                            }

                            return {
                                results: data
                            };
                        }
                    }
                });

                $('#user_id').select2({
                    ajax: {
                        type: 'POST',
                        url: '<?php echo baseUrl; ?>usuarios/busca-responsavel',
                        dataType: 'json',
                        processResults: function (data) {
                            if(data[0]) {
                                if (data[0].id) {
                                    $("#sendMailUser").removeAttr("style");
                                }
                            } 

                            return {
                                results: data
                            };
                        }
                    }
                });

                $('#formUpdateSchedule').validate({
                    submitHandler: async  function() {
                        let form_data = new FormData();         
                        
                        $.each($("input[type='file']")[0].files, function (i, file) {
                            form_data.append('file_' + i, file);
                        });

                        form_data.append('title', $("#title").val());    
                        form_data.append('description', $("#description").val());    
                        form_data.append('schedule_date', $("#schedule_date").val());    
                        form_data.append('schedule_time', $("#schedule_time").val());    
                        form_data.append('status', $("#status_1").val());    
                        form_data.append('id', $("#id").val());    
                        
                        form_data.append('target', '<?php echo $this->getTarget(); ?>');

                        form_data.append('user_id', $("#user_id").val());    
                        if ($('#send_email_user').is(':checked')) {
                            form_data.append('send_email_user', $("#send_email_user").val());    
                        }

                        form_data.append('customer_id', $("#customer_id").val());    
                        if ($('#send_email_customer').is(':checked')) {
                            form_data.append('send_email_customer', $("#send_email_customer").val());    
                        }

                        $("#baseLoader").show();
                        $("#btnSubmit").show('disabled', true);

                        await $.ajax({
                            type: "POST",
                            url: "<?php echo baseUrl; ?>agendamentos/processa-edicao",
                            cache: false,
                            contentType: false,
                            processData: false,
                            data: form_data,
                            dataType: 'json',
                            async: true
                        }).done(function(data) {
                            showAlert(data.type, data.title, data.msg, data.pos);
                            if (data.type === 'success') {
                                openScheduleDetails('<?php echo $entity['id']; ?>');
                            } else {
                                $("#baseLoader").fadeOut();
                                $("#btnSubmit").attr('disabled', false);
                            }
                        }).fail(function() {
                            showInternalErrorAlert();
                            $("#baseLoader").fadeOut();
                            $("#btnSubmit").attr('disabled', false);
                        });

                        return false;
                    }
                });
            });

            function deleteFile(id) {
                $("#modalDeleteBasicFileTitle").html('<i class="fa fa-trash pr-2"></i> Remover Arquivo');
                $("#modalDeleteBasicFileLoader").hide();
                $("#modalDeleteBasicFile").modal('show');
                $("#modalDeleteBasicFileResult").html('<button type="button" class="btn btn-danger btnRadius" title="Confirmar Exclusão" onclick="runFileDelete(\'' + id + '\');"><i class="fa fa-trash"></i> CONFIRMAR E EXCLUIR</button>');
            }
            
            async function runFileDelete(id) {
                if (id !== null) {
                    $("#modalDeleteBasicFileLoader").show();

                    let send_notification_target = null;
                    if ($('#basic_delete_notification_file').is(':checked')) {
                        send_notification_target = $("#basic_delete_notification_file").val();    
                    }

                    await $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>agendamentos/remove-arquivo",
                        data: { 
                            id: id,
                            schedule_id: '<?php echo $_POST['id']; ?>',
                            target: '<?php echo $this->getTarget(); ?>',
                            send_notification: send_notification_target
                        },
                        async: true
                    }).done(async function (data) {
                        $("#box_" + id).fadeOut(999);
                        $("#modalDeleteBasicFile").modal('hide');
                    }).fail(function () {
                        showInternalErrorAlert();
                        $("#modalDeleteBasicFileLoader").hide();
                    });
                }
            }
        </script>
    <?php endif; ?>
    <?php if ($canCreateCustomer): ?>
        <script>
            async function newCustomer() {
                $("#modalGreenLargeResult").empty();
                $("#modalGreenLarge").modal('hide');
                $("#modalGreenLargeTitle").html('<i class="fa fa-plus-circle pr-1"></i> Adicionar Cliente');
                $("#modalGreenLargeLoader").show();
                $("#modalGreenLarge").modal('show');

                await $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>agendamentos/cadastrar-cliente",
                    data: {
                        target: '<?php echo $this->getTarget(); ?>'
                    },
                    async: true
                }).done(function (data) {
                    $("#modalGreenLargeResult").html(data);
                    $("#modalGreenLargeLoader").hide();
                }).fail(function () {
                    showInternalErrorAlert();
                    $("#modalGreenLargeLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if (!empty($entity['customer_id'])): ?>
        <script>
            $("#customer_id").html('<option value="<?php echo $entity['customer_id']; ?>"><?php echo $entity['customerCod'] . ' - ' . $entity['customerName'] . ' ('.$entity['customerEmail'] . ')'; ?></option>');
            $("#sendMailCustomer").removeAttr("style");
        </script>
    <?php endif; ?>
    <?php if (!empty($entity['user_id'])): ?>
        <script>
            $("#user_id").html('<option value="<?php echo $entity['user_id']; ?>"><?php echo $entity['userCod'] . ' - ' . $entity['userName'] . ' - ' . $entity['userRole'] . ' ('.$entity['userEmail'] . ')'; ?></option>');
            $("#sendMailUser").removeAttr("style");
        </script>
    <?php endif; ?>
<?php endif; ?>