<section class="content" style="margin-left: 9px; margin-right: 9px; padding-top: 75px; padding-bottom: 75px;">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body cardWrapper bg-danger">
                <div class="row">
                    <div class="col-12 mt-3">
                        <h3><i class="fas fa-exclamation-triangle text-warning text-white"></i> 401 - Permissão negada.</h3>
                        <p>
                            Não foi possível realizar esta solicitação, entre em contato com o administrador. 
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>