<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('create'), $this->moduleCodes('services'))): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-plus-square pr-1"></i>
                        Plano
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Planos"
                                onclick="openModule('planos');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formCreatePlan" id="formCreatePlan">
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <label for="name">Nome do Plano*</label>
                                            <input type="text" class="form-control" name="name" id="name" required maxlength="150"
                                                placeholder="Nome do Plano">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="price">Valor*</label>
                                            <input type="text" class="form-control" name="price" id="price" placeholder="0,00" required>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="title">Descrição*</label>
                                            <textarea name="description" id="description" class="form-control" rows="5" required 
                                                placeholder="Descrição completa do Plano"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="btn_link">Link de Pagamento*</label>
                                            <input type="text" class="form-control" name="btn_link" id="btn_link" required
                                                placeholder="Link">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="total_customers">Qtd. Clientes*</label>
                                            <input type="number" class="form-control" name="total_customers" id="total_customers" min="1" placeholder="0" required>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="total_services">Qtd. Serviços*</label>
                                            <input type="number" class="form-control" name="total_services" id="total_services" min="1" placeholder="0" required>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="total_schedules">Qtd. Agendamentos*</label>
                                            <input type="number" class="form-control" name="total_schedules" id="total_schedules" min="1" placeholder="0" required>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="total_revenues">Qtd. Receitas*</label>
                                            <input type="number" class="form-control" name="total_revenues" id="total_revenues" min="1" placeholder="0" required>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="total_expenses">Qtd. Despesas*</label>
                                            <input type="number" class="form-control" name="total_expenses" id="total_expenses" min="1" placeholder="0" required>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="total_tasks">Qtd. Tarefas*</label>
                                            <input type="number" class="form-control" name="total_tasks" id="total_tasks" min="1" placeholder="0" required>
                                        </div>
                                    </div>
                                    <div class="col-md-8 mt-3 mb-2">
                                        <button type="submit" class="btn btn-success w-100" id="btnSubmit" title="Salvar Serviço">
                                            <i class="fa fa-save pr-1"></i> Salvar
                                        </button>
                                    </div>
                                    <div class="col-md-4 mt-3 mb-2">
                                        <button type="button" class="btn btn-outline-primary w-100"
                                                onclick="openModule('planos');" title="Voltar para Planos">
                                            <i class="fas fa-arrow-left pr-1"></i> Voltar
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function(){
            $("input[id=price]").maskMoney({allowNegative: false, thousands:'.', decimal:',', affixesStay: true});

            $('#formCreatePlan').validate({
                rules: {
                    name: {
                        remote: { 
                            type: "post",
                            url: "<?php echo baseUrl; ?>planos/valor-existente",
                        }
                    },
                },
                messages: {
                    name: {
                        remote: "Plano já cadastrado"
                    },
                },
                submitHandler: function( form ){
                    let dados = $( form ).serialize();

                    $("#baseLoader").show();
                    $("#btnSubmit").show('disabled', true);

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>planos/processa-cadastro",
                        data: dados,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#baseLoader").hide();
                        $("#btnSubmit").attr('disabled', false);
                        $('#formCreatePlan').trigger("reset");
                    }).fail(function() {
                        showInternalErrorAlert();
                        $("#baseLoader").hide();
                        $("#btnSubmit").attr('disabled', false);
                    });

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>