<?php 
$entity = $this->view->entity; 
$plans = $this->view->plans; 
?>
<div class="row">
    <div class="col-md-12">
        <form method="post" name="formUpdateUserPlan" id="formUpdateUserPlan">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="name">Plano Selecionado</label>
                            <select name="plan_uuid" id="plan_uuid" class="form-control">
                                <?php foreach ($plans as $plan): ?>
                                    <option value="<?php echo $plan['uuid']; ?>" 
                                        <?php echo ($entity['plan_uuid'] == $plan['uuid'] ? 'selected' : ''); ?>>
                                        <?php echo $plan['name']; ?>
                                    </option>        
                                <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="name">Situação Selecionada</label>
                            <select name="status" id="status" class="form-control">
                            <option value="0" <?php echo ($entity['status'] == '0' ? 'selected' : ''); ?>>AGUARDANDO COMPROVANTE</option>
                            <option value="1" <?php echo ($entity['status'] == '1' ? 'selected' : ''); ?>>ATIVO</option>
                            <option value="2" <?php echo ($entity['status'] == '2' ? 'selected' : ''); ?>>CANCELADO</option>
                            <option value="3" <?php echo ($entity['status'] == '3' ? 'selected' : ''); ?>>ATIVAÇÃO PENDENTE</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="renovation_at">Data de Renovação</label>
                        <input type="date" class="form-control" name="renovation_at" id="renovation_at" required
                            value="<?php echo $entity['renovation_at']; ?>">
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="message">Enviar mensagem ao usuário:</label>
                        <textarea name="message" id="message" class="form-control" rows="3"></textarea>
                    </div>
                </div>
                <div class="col-12"><hr></div>
                <div class="col-12 text-center">
                    <input type="hidden" name="uuid" id="uuid" value="<?php echo $entity['uuid']; ?>">
                    <button type="submit" class="btn btn-primary" id="btnSubmit">
                        <i class="fa fa-save pr-1"></i> Salvar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $(document).ready(function(){
        $('#formUpdateUserPlan').validate({
            submitHandler: function( form ){
                let dados = $( form ).serialize();

                $("#modalLargeLoader").show();
                $("#btnSubmit").show('disabled', true);

                $.ajax({
                    type: "POST",
                    url: "<?php echo baseUrl; ?>planos/planos-usuarios/processa-plano-usario",
                    data: dados,
                    dataType: 'json',
                    async: true
                }).done(function(data) {
                    showAlert(data.type, data.title, data.msg, data.pos);
                    if (data.type === 'success') {
                        $("#modalLarge").modal('hide');
                        usersPlans('<?php echo $entity['plan_uuid']; ?>');
                    } else {
                        $("#modalLargeLoader").hide();
                        $("#btnSubmit").attr('disabled', false);
                    }
                }).fail(function() {
                    showInternalErrorAlert(); 
                    $("#modalLargeLoader").hide();   
                    $("#btnSubmit").attr('disabled', false);
                }); 

                return false;
            }
        });
    });
</script>