<?php
$isAdmin = $_SESSION['ROLE_ADM'] == '1';
$role    = $_SESSION['ROLE'];

$canView    = $isAdmin || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('user-plans'));
$canUpdate  = $isAdmin || $this->acl($role, $this->resourceCodes('update'), $this->moduleCodes('user-plans'));
$canDelete  = $isAdmin || $this->acl($role, $this->resourceCodes('delete'), $this->moduleCodes('user-plans'));

$data = $this->view->data; 
if ($canView):
    ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-user-cog pr-1"></i>
                        Planos de Usuários
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item">
                                <button type="button" class="btn btn-outline-primary"
                                    onclick="openDetails('<?php echo $_POST['uuid']; ?>');" style="width: 100%;">
                                    <i class="fas fa-arrow-left"></i> 
                                </button>
                            </li>
                        </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover" id="table_users_plans" style="width: 100%;">
                                    <thead>
                                        <tr class="text-center" style="height: 30px;">
                                            <th style="font-size: 14px;">Data</th>
                                            <th style="font-size: 14px;">Renovação</th>
                                            <th style="font-size: 14px;">Usuário</th>
                                            <th style="font-size: 14px;">Comprovante</th>
                                            <th style="font-size: 14px;">Situação</th>
                                            <th style="font-size: 14px;">Ações</th>
                                            <th style="display: none;">Situação</th>
                                            <th style="display: none;">Comprovante</th>
                                            <th style="display: none;">Data Comprovante</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($data as $entity): ?>
                                            <tr class="text-center">
                                                <td style="font-size: 15px; ">
                                                    <?php echo $this->formatDateTime($entity['created_at'], false); ?>
                                                </td>
                                                <td style="font-size: 15px; ">
                                                    <?php echo $this->formatDate($entity['renovation_at']); ?>
                                                </td>
                                                <td style="font-size: 15px; ">
                                                    <?php echo $entity['userName'] . ' (' . $entity['userEmail'] . ')'; ?>
                                                </td>
                                                <td style="font-size: 15px;">
                                                    <?php if (!empty($entity['file'])): ?>
                                                        <a href="<?php echo baseUrl . 'public/uploads/userplans/' . $entity['uuid'] . '/' . $entity['file']; ?>"
                                                            target="_blank">
                                                            <?php echo $entity['file']; ?>
                                                        </a>
                                                        <?php if ($canDelete): ?>
                                                            <button type="button" class="btn btn-danger btn-xs" title="Excluir Comprovante"
                                                                onclick="deleteUserPlanFile('<?php echo $entity['uuid']; ?>', '<?php echo $entity['file']; ?>');">
                                                                <span class="fa fa-trash"></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <b>Aguradando</b>
                                                    <?php endif; ?>
                                                </td>
                                                <td style="font-size: 15px;">
                                                    <?php if ($entity['status'] == '0'): ?>
                                                        <span style="color: blue;">AGUARDANDO COMPROVANTE</span>
                                                    <?php endif; ?>
                                                    <?php if ($entity['status'] == '1'): ?>
                                                        <span style="color: green;">ATIVO</span>
                                                    <?php endif; ?>
                                                    <?php if ($entity['status'] == '2'): ?>
                                                        <span style="color: red;">CANCELADO</span>
                                                    <?php endif; ?>
                                                    <?php if ($entity['status'] == '3'): ?>
                                                        <span style="color: purple;">ATIVAÇÃO PENDENTE</span>
                                                    <?php endif; ?>
                                                </td>
                                                <td style="font-size: 15px;">
                                                    <?php if ($canUpdate): ?>
                                                        <button type="button" class="btn btn-success btn-xs"
                                                            onclick="updateUserPlan('<?php echo $entity['uuid']; ?>');">
                                                            <span class="fa fa-sync"></span>
                                                        </button>
                                                    <?php endif; ?>
                                                    <?php if ($canDelete): ?>
                                                        <button type="button" class="btn btn-danger btn-xs"
                                                            onclick="deleteUserPlan('<?php echo $entity['uuid']; ?>');">
                                                            <span class="fa fa-trash"></span>
                                                        </button>
                                                    <?php endif; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php if ($entity['status'] == '0'): ?>
                                                        AGUARDANDO COMPROVANTE
                                                    <?php endif; ?>
                                                    <?php if ($entity['status'] == '1'): ?>
                                                        ATIVO
                                                    <?php endif; ?>
                                                    <?php if ($entity['status'] == '2'): ?>
                                                        CANCELADO
                                                    <?php endif; ?>
                                                    <?php if ($entity['status'] == '3'): ?>
                                                        ATIVAÇÃO PENDENTE
                                                    <?php endif; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php if (!empty($entity['file'])): ?>
                                                        <?php echo baseUrl . 'public/uploads/userplans/' . $entity['uuid'] . '/' . $entity['file']; ?>
                                                    <?php else: ?>
                                                        <b>Aguradando</b>
                                                    <?php endif; ?>
                                                </td>
                                                <td style="display: none;">
                                                    <?php echo $this->formatDateTime($entity['uploaded_at']); ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script type="text/javascript">
        $(document).ready(function() {
            let buttonCommon = {
                exportOptions: {
                    format: {
                        body: function ( data ) {
                            return data;
                        }
                    }
                }
            };	

            $('#table_users_plans').DataTable({
                "sDom": 'flBtip',
                searching: true,
                buttons: [
                    $.extend( true, {}, buttonCommon, {
                        extend: 'excel',
                        title: 'PLANOS DE USUÁRIOS',
                        exportOptions: {columns: [0,1,2,6,7,8]}
                    })
                ],
                order: [ [0, "desc"] ],
                columnDefs: [{orderable: false, targets: [3,5]}],
                responsive: true,
                info: true,
                processing: true,
                scrollCollapse: true,
                paging: true,
                "pageLength": 10,
                "language": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ &nbsp;",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Filtrar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
        });
    </script>
    <?php if ($canUpdate): ?>
        <script>
            function updateUserPlan(uuid) {
                $("#modalLargeResult").empty();
                $("#modalLargeTitle").html('<i class="fa fa-info-circle pr-2"></i> Atualizar Plano de Usuário');
                $("#modalLargeLoader").show();
                $("#modalLarge").modal('show');
                
                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>planos/planos-usuarios/atualizar",
                    data: {uuid:uuid},
                    async: true
                }).done(function(data) {
                    $("#modalLargeResult").html(data);
                    $("#modalLargeLoader").hide();
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#modalLargeLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canDelete): ?>
        <script>
            function deleteUserPlan(uuid) {
                $("#modalXL").modal('hide');
                $("#modalDeleteTitle").html('<i class="fa fa-trash pr-2"></i> Excluir Plano');
                $("#modalDeleteLoader").hide();
                $("#modalDelete").modal('show');
                $("#modalDeleteResult").html('<button type="button" class="btn btn-danger" title="Confirmar Exclusão" onclick="runUserPlanDelete(\''+uuid+'\');"><i class="fa fa-trash"></i> CONFIRMAR E EXCLUIR</button>');
            }

            function runUserPlanDelete(uuid) {
                if (uuid !== null) {
                    $("#modalDeleteLoader").show();
                    
                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>planos/planos-usuarios/excluir",
                        data: {uuid: uuid},
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#modalDelete").modal('hide');
                        $("#modalXL").modal('hide');
                        usersPlans('<?php echo $this->view->plan_uuid; ?>');
                    }).fail(function() {
                        showInternalErrorAlert();
                        $("#modalDeleteLoader").hide();
                    });
                }
            }

            function deleteUserPlanFile(uuid, file) {
                $("#modalXL").modal('hide');
                $("#modalDeleteTitle").html('<i class="fa fa-trash pr-2"></i> Excluir Comprovante de Pagamento');
                $("#modalDeleteLoader").hide();
                $("#modalDelete").modal('show');
                $("#modalDeleteResult").html('<button type="button" class="btn btn-danger" title="Confirmar Exclusão" onclick="runUserPlanDeleteFile(\''+uuid+'\',\''+file+'\');"><i class="fa fa-trash"></i> CONFIRMAR E EXCLUIR</button>');
            }

            function runUserPlanDeleteFile(uuid, file) {
                $.ajax({
                    type: "POST",
                    url: "<?php echo baseUrl; ?>planos/planos-usuarios/excluir-comprovante",
                    data: {
                        uuid: uuid,
                        file: file
                    },
                    dataType: 'json',
                    async: true
                }).done(function(data) {
                    showAlert(data.type, data.title, data.msg, data.pos);
                    $("#modalDelete").modal('hide');
                    $("#modalXL").modal('hide');
                    usersPlans('<?php echo $this->view->plan_uuid; ?>');
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#modalDeleteLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
<?php endif; ?>