<section class="content-header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12" >
                <h1 style="position: relative; top: 5px; font-size: 25px;">
                    <i class="fas fa-dollar-sign pr-1"></i>
                    Planos
                </h1>
            </div>
        </div>
    </div>
</section>
<section class="content" style="margin-left: 9px; margin-right: 9px;">
    <div class="container-fluid">
        <div class="row">
            <?php if ($this->view->user_plans): ?>
                <?php foreach ($this->view->user_plans as $entity): ?>
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body ">
                                <h2>
                                    <small>Plano Selecionado: </small> <br><?php echo $entity['planName']; ?>  
                                    <?php if ($entity['status'] == '0'): ?>
                                        <span style="color: blue;">( PENDENTE DE ATIVAÇÃO ) </span>
                                    <?php endif; ?>
                                    <?php if ($entity['status'] == '1'): ?>
                                        <span style="color: green;">( ATIVO ) </span>
                                    <?php endif; ?>
                                    <?php if ($entity['status'] == '2'): ?>
                                        <span style="color: blue;">( CANCELADO ) </span>
                                    <?php endif; ?>
                                </h2>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <?php foreach ($this->view->data as $entity): ?>
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-body">
                                <div class="bg-primary text-center py-3" style="border-radius: 10px;">
                                    <h3 class="text-center pt-2"><?php echo $entity['name']; ?></h3>
                                </div>
                                <div class="text-center mt-3">
                                    <p><?php echo $entity['description']; ?></p>
                                    <h2>R$ <?php echo number_format($entity['price'], 2, ",","."); ?> /mês</h2>
                                </div>
                                <button type="button" class="btn btn-outline-success btn-lg w-100 mt-3"
                                    onclick="selectPlan('<?php echo $entity['uuid']; ?>');" >
                                    <span class="fa fa-check pr-1"></span>
                                    SOLICITAR
                                </button>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
</section>
<script>
    function selectPlan(uuid) {
        $("#baseLoader").show();
        $.ajax({
            type: 'post',
            url: "<?php echo baseUrl; ?>planos/plano-selecionado",
            data: {uuid:uuid},
            dataType: 'json',
            async: true
        }).done(function(data) {
            showAlert(data.type, data.title, data.msg, data.pos);
            $("#baseLoader").hide();
            openModule('planos-usuario');
        }).fail(function() {
            showInternalErrorAlert();
            $("#baseLoader").hide();
        });
    }
</script>