<?php 
$config = $this->getSiteConfig();
$config['logo'] = $this->isImage($config['logo'], 'logo') ? $config['logo'] : 'jaconsultoriati.png';
$config['logo_icon'] = $this->isImage($config['logo_icon'], 'logo') ? $config['logo_icon'] : 'jaconsultoriati.png';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login | Área do Cliente | <?php echo $config['site_title']; ?></title>
    <meta author="João Augusto Bonfante">
    <link rel="icon" href="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo_icon']; ?>" type="image/x-icon" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/plugins/jquery-toast-plugin/dist/jquery.toast.min.css">
    <style>
        h1 {
            color: <?php echo $config['primary_color']; ?> !important;
        }

        .bg-primary {
            background: <?php echo $config['primary_color']; ?> !important;
        }

        .bg-primary:hover {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .bg-secondary {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .bg-secondary:hover {
            background: <?php echo $config['primary_color']; ?> !important;
        }

        .btn-primary {
            background: <?php echo $config['primary_color']; ?> !important;
        }

        .btn-primary:hover {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .btn-secondary {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .btn-secondary:hover {
            background: <?php echo $config['primary_color']; ?> !important;
        }

        .btnRadius {
            border-radius: 20px !important;
        }

        .btnRadiusLg {
            border-radius: 30px !important;
        }
    </style>
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="card card-outline card-dark">
            <div class="card-header text-center">
                <img src="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo']; ?>" alt="logo" style="width: 100%;">
            </div>
            <div class="card-body">
                <form action="<?php echo baseUrl; ?>cliente/auth" method="post" id="formEmail">
                    <div class="input-group mb-3">
                        <input type="email" class="form-control" placeholder="Email" name="email" id="email" required>
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 mt-2">
                            <button type="submit" class="btn btn-primary btn-block btnRadius" title="Entrar" id="btnConfirm">Entrar</button>
                        </div>
                        <div class="col-12 text-center mt-2">
                            <a href="<?php echo baseUrl; ?>" style=" color: #000;" title="Voltar para login">
                                Voltar
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalLoad" data-keyboard="false" data-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <div style="color: <?php echo $config['secondary_color'] ?>" class="pt-2">
                        <h2><span class="fa fa-clock"></span> Aguarde...</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="<?php echo baseUrl; ?>public/app/plugins/jquery/jquery.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>
