<?php 
$isAdmin = $_SESSION['ROLE_ADM'] == '1';
$role    = $_SESSION['ROLE'];

$canView = $isAdmin || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('financial'));
?>
<?php if ($canView): ?>
    <section class="content-header mt-5">
        <div class="container-fluid mt-2">
            <div class="row">
                <div class="col-8" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-cash-register pr-1"></i>
                        Financeiro
                    </h1>
                </div>
                <div class="col-4">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary"
                                onclick="changeMonth();" style="width: 100%;" title="Alterar Mês">
                                <i class="fas fa-sync  pr-1"></i> <?php echo $this->view->month; ?>
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
            <div class="row">
                <div class="col-12 mt-3">
                    <div class="row">
                        <div class="col-md-4 text-center">
                            <div class="card bg-danger">
                                <div class="card-body">
                                    <span style="font-size: 1em"><i class="fa fa-minus-circle pr-1"></i> Despesas</span> 
                                    <h3>R$ <?php echo number_format($this->view->total_expenses, 2, ",","."); ?></h3>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 text-center">
                            <div class="card bg-success">
                                <div class="card-body">
                                    <span style="font-size: 1em"><i class="fa fa-plus-circle pr-1"></i> Receitas</span> 
                                    <h3>R$ <?php echo number_format($this->view->total_schedules, 2, ",","."); ?></h3>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 text-center">
                            <div class="card bg-info">
                                <div class="card-body">
                                    <span style="font-size: 1em"><i class="fa fa-cash-register pr-1"></i> Caixa</span> 
                                    <h3>R$ <?php echo number_format(($this->view->total_schedules - $this->view->total_expenses), 2, ",","."); ?></h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?php if (empty($_SESSION['PLAN']) && !$_SESSION['ROLE_ADM']): ?>
                        <div class="alert alert-info" role="alert">
                            <span class="fa fa-users pr-1"></span> 
                            Você está utilizando o Plano Gratuito. 
                            <a onclick="openModule('planos-usuario');" 
                                class="alert-link text-white" style="cursor: pointer;">Clique aqui</a> para alterar e liberar todos os recursos do sistema.
                        </div>
                    <?php endif; ?>
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover" id="table_fn" style="width: 100%;">
                                    <thead>
                                        <tr class="text-center" style="height: 30px;">
                                            <th style="font-size: 14px;">Data</th>
                                            <th style="font-size: 14px;">Tipo</th>
                                            <th style="font-size: 14px;">Descrição</th>
                                            <th style="font-size: 14px;">Valor</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->view->schedules as $entity): ?>
                                            <tr class="text-center" style="cursor: pointer;">
                                                <td style="font-size: 15px">
                                                    <?php echo $this->formatDate($entity['schedule_date']); ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    Receita
                                                </td>
                                                <td style="font-size: 15px; width: 60%;">
                                                    <?php echo $entity['serviceName']; ?><?php echo !empty($entity['customerName']) ? ' para ' . $entity['customerName'] : ''; ?><?php echo !empty($entity['description']) ? ' - ' . $entity['description'] : ''; ?> 
                                                </td> 
                                                <td style="font-size: 15px">
                                                    <?php echo number_format($entity['amount'], 2, ",","."); ?>
                                                </td> 
                                            </tr>
                                        <?php endforeach; ?>
                                        <?php foreach ($this->view->expenses as $entity): ?>
                                            <tr class="text-center" style="cursor: pointer;">
                                                <td style="font-size: 15px">
                                                    <?php echo $this->formatDate($entity['expense_date']); ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    Despesa
                                                </td>
                                                <td style="font-size: 15px; width: 60%;">
                                                    <?php echo $entity['title']; ?><?php echo !empty($entity['customerName']) ? ' para ' . $entity['customerName'] : ''; ?><?php echo !empty($entity['description']) ? ' - ' . $entity['description'] : ''; ?> 
                                                </td> 
                                                <td style="font-size: 15px">
                                                    <?php echo number_format($entity['amount'], 2, ",","."); ?>
                                                </td> 
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php if (empty($_GET['m'])): ?>
        <script>
            $(document).ready(function() {
                $("#f_month").val('<?php echo date('Y-m'); ?>');
            });
        </script>
    <?php endif; ?>
    <script type="text/javascript">
        $(document).ready(function() {
            let buttonCommon = {
                exportOptions: {
                    format: {
                        body: function ( data, row, column ) {
                            return  column === 3  ?
                                parseFloat(data.replace(/[.]/g, '' ).replace( ',', '.' )).toLocaleString('en-IN',
                                {minimumFractionDigits: 2 , maximumFractionDigits: 2}) : data;
                        }
                    }
                }
            };	

            $('#table_fn').DataTable({
                "sDom": 'flBtip',
                searching: true,
                buttons: [
                    $.extend( true, {}, buttonCommon, {
                        extend: 'excel',
                        title: 'Receitas e Despesas do Mês <?php echo $this->view->month; ?>',
                        exportOptions: {columns: [0,1,2,3]}
                    })
                ],
                order: [ [0, "desc"] ],
                columnDefs: [
                    {type: 'date-eu', targets: [0]},
                    {type: 'valoresemreais', targets: [3]},
                ],
                responsive: true,
                info: true,
                processing: true,
                scrollCollapse: true,
                paging: true,
                "pageLength": 25,
                "language": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ &nbsp;",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Filtrar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
        });
    </script>

    <script>
        function openDetails(uuid) {
            $("#baseLoader").show();
            $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>despesas/detalhes",
                data: {uuid:uuid},
                async: true
            }).done(function(data) {
                $("#sis_content").html(data);
                $("#baseLoader").hide();
            }).fail(function() {
                showInternalErrorAlert();
                $("#baseLoader").hide();
            });
        }

        function changeMonth() {
            $("#modalMonthTitle").html('<i class="fa fa-info-circle pr-2"></i> Alterar Mês');
            $("#modalMonthLoader").hide();
            $("#modalMonth").modal('show');           
        }

        function selectMonth() {
            let month = $("#f_month").val();
            $("#modalMonthLoader").show();
            openModule('financeiro?m=' + month);
            $("#modalMonthLoader").hide();
            $("#modalMonth").modal('hide');    
        }
    </script>
<?php endif; ?>