<?php if ($this->view->acl['canCreate']): ?>
    <section class="content" style="margin-left: 9px; margin-right: 9px; padding-top: 75px;">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body cardWrapper">
                    <div class="row">
                        <div class="col-6">
                            <h5 class="pt-2">
                                <i class="fas fa-plus-square pr-1"></i>
                                Cliente
                            </h5>
                        </div>
                        <div class="col-6 text-right">
                            <button type="button" class="btn btn-primary btnRadius" 
                                title="Voltar para Clientes"
                                onclick="openModule('clientes');">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body cardWrapperBody">
                            <form method="post" name="formCreateCustomer" id="formCreateCustomer">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="name">Nome*</label>
                                            <input type="text" class="form-control" name="name" id="name" required maxlength="100" placeholder="Nome completo do Cliente/Empresa">
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-3">
                                        <div class="form-group">
                                            <label for="document_1">CPF</label>
                                            <input type="text" class="form-control" name="document_1" id="document_1" onchange="validateCPF();"
                                                placeholder="000.000.000-00">
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-3">
                                        <div class="form-group">
                                            <label for="document_2">CNPJ</label>
                                            <input type="text" class="form-control" name="document_2" id="document_2" onchange="validateCNPJ();"
                                                placeholder="00.000.000/0000-00">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <hr>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="email">Email*</label>
                                            <input type="email" class="form-control" name="email" id="email" required maxlength="100"
                                            placeholder="cliente@exemplo.com">
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6 col-lg-3">
                                        <div class="form-group">
                                            <label for="phone">Telefone</label>
                                            <input type="text" class="form-control" name="phone" id="phone"
                                                placeholder="(00)0000-0000">
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6 col-lg-3">
                                        <div class="form-group">
                                            <label for="cellphone">Celular</label>
                                            <input type="text" class="form-control" name="cellphone" id="cellphone"
                                                placeholder="(00)00000-0000">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <hr>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="postal_code">CEP</label>
                                            <input type="text" class="form-control" name="postal_code" id="postal_code" placeholder="00000-000">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="address">Endereço</label>
                                            <input type="text" class="form-control" name="address" id="address"  maxlength="100" placeholder="Endereço completo">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="number">Número</label>
                                            <input type="text" class="form-control" name="number" id="number"  maxlength="50" placeholder="000">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="complement">Complemento</label>
                                            <input type="text" class="form-control" name="complement" id="complement"  maxlength="50" placeholder="Complemento adicional">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="neighborhood">Bairro</label>
                                            <input type="text" class="form-control" name="neighborhood" id="neighborhood"  maxlength="100" placeholder="Nome do Bairro">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="city">Cidade</label>
                                            <input type="text" class="form-control" name="city" id="city"  maxlength="100" placeholder="Nome da Cidade">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="state">UF</label>
                                            <input type="text" class="form-control" name="state" id="state"  maxlength="2" placeholder="Estado">
                                        </div>
                                    </div>
                                    <div class="col-12 mt-1">
                                        <div class="row">
                                            <div class="col-md-6 offset-md-3 mb-2">
                                                <input type="hidden" name="target" value="<?php echo $this->getTarget(); ?>">
                                                <button type="submit" class="btn btn-success w-100 btnRadius" id="btnSubmit" title="Salvar Cliente">
                                                    <i class="fa fa-save pr-1"></i> Salvar
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 text-center mb-3">
                    <button type="button" class="btn btn-default btn-sm btnRadius"
                        onclick="openModule('clientes');" 
                        title="Voltar para Clientes">
                        <i class="fas fa-arrow-left pr-1"></i> Voltar
                    </button>
                </div>
            </div>
        </div>
    </section>
    <script src="<?php echo baseUrl; ?>public/js/api_cep.js"></script>
    <script src="<?php echo baseUrl; ?>public/js/documents_validators.js"></script>
    <script>
        $(document).ready(function() {
            $("#name").focus();
            $("#document_1").mask("999.999.999-99");
            $("#document_2").mask("99.999.999/9999-99");
            $("#phone").mask("(99)9999-9999");
            $("#cellphone").mask("(99)99999-9999");
            $("#postal_code").mask("99999-999");
            
            $('#formCreateCustomer').validate({
                submitHandler: async function( form ){
                    let dados = $( form ).serialize();
                    $("#baseLoader").show();
                    $("#btnSubmit").attr('disabled', true);
                    
                    await $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>clientes/processa-cadastro",
                        data: dados,
                        dataType: 'json',
                        async: true
                    }).done(async function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        if (data.type === 'success') {
                            await openCustomerDetails(data.id);
                        } else {
                            $("#baseLoader").fadeOut();
                            $("#btnSubmit").attr('disabled', false);
                        }
                    }).fail(function() {
                        showInternalErrorAlert(); 
                        $("#baseLoader").fadeOut();
                        $("#btnSubmit").attr('disabled', false);
                    }); 

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>