<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('customers'))): ?>
    <?php $entity = $this->view->entity; ?>
    <section class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-info-circle pr-1"></i>
                        Cliente
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Clientes"
                                onclick="openModule('clientes');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body"> 
                            <div class="row">
                                <div class="col-md-12">
                                    <b>Situação:</b>
                                    <?php if ($entity['status'] == '1'): ?>
                                            <i class="fa fa-circle pl-1" style="color: green;"></i> Ativo no sistema
                                    <?php endif; ?>
                                    <?php if ($entity['status'] == '2'): ?>
                                            <i class="fa fa-circle pl-1" style="color: red;"></i> Inativo no sistema
                                    <?php endif; ?>
                                    <hr>
                                </div>
                                <div class="col-12 col-md-6">
                                    <b>Nome</b>
                                    <p><?php echo $entity['name']; ?></p>
                                </div>
                                <div class="col-12 col-md-6">
                                    <b>Email</b>
                                    <p><?php echo $entity['email']; ?></p>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <b>CPF</b>
                                    <p><?php echo (!empty($entity['document_1']) ? $entity['document_1'] : 'Não informado'); ?></p>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <b>CNPJ</b>
                                    <p><?php echo (!empty($entity['document_2']) ? $entity['document_2'] : 'Não informado'); ?></p>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <b>Telefone</b>
                                    <p><?php echo (!empty($entity['phone']) ? $entity['phone'] : 'Não informado'); ?></p>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <b>Celular</b>
                                    <p><?php echo (!empty($entity['cellphone']) ? $entity['cellphone'] : 'Não informado'); ?></p>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <b>CEP</b>
                                    <p><?php echo (!empty($entity['postal_code']) ? $entity['postal_code'] : 'Não informado'); ?></p>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <b>Endereço</b>
                                    <p><?php echo (!empty($entity['address']) ? $entity['address'] : 'Não informado'); ?></p>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <b>Número</b>
                                    <p><?php echo (!empty($entity['number']) ? $entity['number'] : 'Não informado'); ?></p>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <b>Complemento</b>
                                    <p><?php echo (!empty($entity['complement']) ? $entity['complement'] : 'Não informado'); ?></p>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <b>Bairro</b>
                                    <p><?php echo (!empty($entity['neighborhood']) ? $entity['neighborhood'] : 'Não informado'); ?></p>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <b>Cidade</b>
                                    <p><?php echo (!empty($entity['city']) ? $entity['city'] : 'Não informada'); ?></p>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <b>UF</b>
                                    <p><?php echo (!empty($entity['state']) ? $entity['state'] : 'Não informado'); ?></p>
                                </div>
                                <div class="col-12 col-md-6 col-lg-3">
                                    <b>Status</b>
                                    <p><?php echo ($entity['status'] == '1') ? 'Ativo' : 'Inativo'; ?></p>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-12 col-md-6">
                                    <b>Cadastrado em: </b> 
                                    <span><?php echo $this->formatDateTime($entity['created_at']); ?></span>
                                </div>
                                <div class="col-12 col-md-6 ">
                                    <?php if (!empty($entity['updated_at'])): ?>
                                        <b>Atualizado em: </b>
                                        <span><?php echo $this->formatDateTime($entity['updated_at']); ?></span>
                                    <?php endif; ?>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-6 col-lg-4 mt-2 mb-2">
                                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('delete'), $this->moduleCodes('customers'))): ?>
                                                <button type="button" class="btn btn-outline-danger btn-lg" title="Remover Cliente"
                                                    onclick="deleteCustomer('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                                    <i class="fa fa-trash"></i> Remover
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                        <div class="col-md-6 col-lg-4 mt-2 mb-2">
                                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('update'), $this->moduleCodes('customers'))): ?>
                                                <button type="button" class="btn btn-outline-success btn-lg" title="Editar Cliente"
                                                    onclick="updateCustomer('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                                    <i class="fa fa-pen pr-1"></i> Editar
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                        <div class="col-md-6 col-lg-4 mt-2 mb-2">
                                            <button type="button" class="btn btn-outline-primary btn-lg" onclick="openModule('clientes');" 
                                                style="width: 100%;" title="Voltar para Clientes">
                                                <i class="fas fa-arrow-left pr-1"></i> Voltar
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>