<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('create'), $this->moduleCodes('services'))): ?>
    <section class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-plus-square pr-1"></i>
                        Serviço
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-primary"
                                onclick="openModule('servicos');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formCreateService" id="formCreateService">
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <label for="title">Título*</label>
                                            <input type="text" class="form-control" name="title" id="title" required maxlength="150"
                                                placeholder="Nome do Serviço">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="price">Valor*</label>
                                            <input type="text" class="form-control" name="price" id="price" placeholder="0,00" required>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="title">Descrição*</label>
                                            <textarea name="description" id="description" class="form-control" rows="10" required placeholder="Descrição completa do Serviço"></textarea>
                                        </div>
                                    </div>
                                    <div class="col-md-12 text-right mt-3 mb-2">
                                        <button type="button" class="btn btn-default mr-3"
                                                onclick="openModule('servicos');">
                                            <i class="fas fa-arrow-left pr-1"></i> Voltar
                                        </button>
                                        <button type="submit" class="btn btn-primary" id="btnSubmit">
                                            <i class="fa fa-save pr-1"></i> Salvar
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function(){
            $("input[id=price]").maskMoney({allowNegative: false, thousands:'.', decimal:',', affixesStay: true});

            $('#formCreateService').validate({
                rules: {
                    title: {
                        remote: { 
                            type: "post",
                            url: "<?php echo baseUrl; ?>servicos/valor-existente",
                        }
                    },
                },
                messages: {
                    title: {
                        remote: "Serviço já cadastrado"
                    },
                },
                submitHandler: function( form ){
                    let dados = $( form ).serialize();

                    $("#baseLoader").show();
                    $("#btnSubmit").show('disabled', true);

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>servicos/processa-cadastro",
                        data: dados,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#baseLoader").hide();
                        $("#btnSubmit").attr('disabled', false);
                        $('#formCreateService').trigger("reset");
                    }).fail(function() {
                        showInternalErrorAlert();
                        $("#baseLoader").hide();
                        $("#btnSubmit").attr('disabled', false);
                    });

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>