<?php
$aclData = $this->view->acl;
$canView = $aclData['canView'];
$canCreate = $aclData['canCreate'];

if ($canView): ?>
    <?php $data = $this->view->data; ?>
    <section class="content" style="margin-left: 9px; margin-right: 9px; padding-top: 75px;">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body cardWrapper">
                    <div class="row">
                        <div class="col-6">
                            <h5 class="pt-2">
                                <i class="fas fa-tools pr-1"></i>
                                Serviços
                            </h5>
                        </div>
                        <div class="col-6 text-right">
                            <?php if ($canCreate): ?>
                                <button type="button" class="btn btn-success btnRadius" 
                                    title="Adicionar Serviço"
                                    onclick="createService();">
                                    <i class="fas fa-plus"></i>
                                </button>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body cardWrapperList">
                            <?php if (!$data): ?>
                                <div class="alert alert-info mt-3" role="alert">
                                    <i class="fas fa-info-circle pr-1"></i> Nenhuma informação até o momento.
                                </div>
                            <?php else: ?>
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover" id="table_sv" style="width: 100%;">
                                        <thead>
                                            <tr class="text-center" style="height: 30px;">
                                                <th style="font-size: 14px;">Código</th>
                                                <th style="font-size: 14px;">Serviço</th>
                                                <th style="font-size: 14px;">Valor</th>
                                                <th style="font-size: 14px;">Tipo</th>
                                                <th style="font-size: 14px;">Situação</th>
                                                <th style="display: none;">Situação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($data as $entity): ?>
                                                <tr class="text-center" style="cursor: pointer;"
                                                    onclick="openServiceDetails('<?php echo $entity['id']; ?>');">
                                                    <td style="font-size: 15px">
                                                        <?php echo $entity['id']; ?>
                                                    </td>
                                                    <td style="font-size: 15px">
                                                        <?php echo $entity['title']; ?>
                                                    </td>
                                                    <td style="font-size: 15px">
                                                        <?php echo number_format($entity['price'], 2, ",", "."); ?>
                                                    </td>
                                                    <td style="font-size: 15px">
                                                        <?php echo ($entity['service_type']  == '1')
                                                            ? 'Total' : 'Por Hora'; ?>
                                                    </td>
                                                    <td style="font-size: 15px;">
                                                        <?php if ($entity['status'] == '1'): ?>
                                                            <span class="text-success">Ativo</span>
                                                        <?php else: ?>
                                                            <span class="text-danger">Inativo</span>
                                                        <?php endif; ?>
                                                    </td>
                                                    <td style="display: none;">
                                                        <?php echo ($entity['status'] == '1') ? 'Ativo' : 'Inativo'; ?>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php if ($data): ?>
        <script type="text/javascript">
            $(document).ready(function () {
                let buttonCommon = {
                    exportOptions: {
                        format: {
                            body: function (data, row, column) {
                                return column === 2 ?
                                    parseFloat(data.replace(/[.]/g, '').replace(',', '.')).toLocaleString('en-IN',
                                        { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : data;
                            }
                        }
                    }
                };

                $('#table_sv').DataTable({
                    "sDom": 'flBtip',
                    searching: true,
                    buttons: [
                        $.extend(true, {}, buttonCommon, {
                            extend: 'excel',
                            title: 'Serviços',
                            exportOptions: { columns: [0, 1, 2, 3, 5] }
                        })
                    ],
                    order: [[0, "asc"]],
                    columnDefs: [
                        { type: 'valoresemreais', targets: [2] },
                    ],
                    responsive: true,
                    info: true,
                    processing: true,
                    scrollCollapse: true,
                    paging: true,
                    "pageLength": 25,
                    "language": {
                        "sEmptyService": "Nenhum registro encontrado",
                        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                        "sInfoPostFix": "",
                        "sInfoThousands": ".",
                        "sLengthMenu": "_MENU_ &nbsp;",
                        "sLoadingRecords": "Carregando...",
                        "sProcessing": "Processando...",
                        "sZeroRecords": "Nenhum registro encontrado",
                        "sSearch": "Filtrar",
                        "oPaginate": {
                            "sNext": "Próximo",
                            "sPrevious": "Anterior",
                            "sFirst": "Primeiro",
                            "sLast": "Último"
                        },
                        "oAria": {
                            "sSortAscending": ": Ordenar colunas de forma ascendente",
                            "sSortDescending": ": Ordenar colunas de forma descendente"
                        }
                    }
                });
            });
        </script>
    <?php endif; ?>
    <?php if ($canCreate): ?>
        <script>
            async function createService() {
                $("#baseLoader").show();
                await $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>servicos/cadastrar",
                    data: {
                        target: '<?php echo $this->getTarget(); ?>'
                    },
                    async: true
                }).done(function (data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").fadeOut();
                }).fail(function () {
                    showInternalErrorAlert();
                    $("#baseLoader").fadeOut();
                });
            }
        </script>
    <?php endif; ?>
    <script>
        async function openServiceDetails(id) {
            $("#baseLoader").show();
            await $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>servicos/detalhes",
                data: { 
                    id: id,
                    target: '<?php echo $this->getTarget(); ?>' 
                },
                async: true
            }).done(function (data) {
                $("#sis_content").html(data);
                $("#baseLoader").fadeOut();
            }).fail(function () {
                showInternalErrorAlert();
                $("#baseLoader").fadeOut();
            });
        }
    </script>
<?php endif; ?>