<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('services'))): ?>
    <?php $entity = $this->view->entity; ?>
    <section class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-11" >
                    <h1 style="position: relative; top: 5px; font-size: 25px;">
                        <i class="fas fa-info-circle pr-1"></i>
                        Serviço
                    </h1>
                </div>
                <div class="col-1">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-outline-primary" title="Voltar para Serviços"
                                onclick="openModule('servicos');" style="width: 100%;">
                                <i class="fas fa-arrow-left"></i> 
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <b>Situação:</b>
                                    <?php if ($entity['status'] == '1'): ?>
                                            <i class="fa fa-circle pl-1" style="color: green;"></i> Ativo no sistema
                                    <?php endif; ?>
                                    <?php if ($entity['status'] == '2'): ?>
                                            <i class="fa fa-circle pl-1" style="color: red;"></i> Inativo no sistema
                                    <?php endif; ?>
                                    <hr>
                                </div>
                                <div class="col-md-8">
                                    <b>Título</b>
                                    <p><?php echo $entity['title']; ?></p>
                                </div>
                                <div class="col-md-4">
                                    <b>Valor</b>
                                    <p>
                                        R$ <?php echo number_format($entity['price'], 2, ",", "."); ?>
                                    </p>
                                </div>
                                <div class="col-md-12">
                                    <b>Descrição</b>
                                    <p><?php echo $entity['description']; ?></p>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-12 col-md-6">
                                    <b>Cadastrado em: </b> 
                                    <span><?php echo $this->formatDateTime($entity['created_at']); ?></span>
                                </div>
                                <div class="col-12 col-md-6 ">
                                    <?php if (!empty($entity['updated_at'])): ?>
                                        <b>Atualizado em: </b>
                                        <span><?php echo $this->formatDateTime($entity['updated_at']); ?></span>
                                    <?php endif; ?>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-6 col-lg-4 mt-2 mb-2">
                                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('delete'), $this->moduleCodes('services'))): ?>
                                                <button type="button" class="btn btn-outline-danger" title="Remover Serviço"
                                                    onclick="deleteService('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                                    <i class="fa fa-trash"></i> Remover
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                        <div class="col-md-6 col-lg-4 mt-2 mb-2">
                                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], $this->resourceCodes('update'), $this->moduleCodes('services'))): ?>
                                                <button type="button" class="btn btn-outline-success" title="Editar Serviço"
                                                    onclick="updateService('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                                                    <i class="fa fa-pen pr-1"></i> Editar
                                                </button>
                                            <?php endif; ?>
                                        </div>
                                        <div class="col-md-6 col-lg-4 mt-2 mb-2">
                                            <button type="button" class="btn btn-outline-primary" title="Voltar para Serviços"
                                                 onclick="openModule('servicos');" style="width: 100%;">
                                                <i class="fas fa-arrow-left pr-1"></i> Voltar
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>