<?php if ($this->view->acl['canUpdate']): ?>
    <?php $entity = $this->view->entity; ?>
    <section class="content" style="margin-left: 9px; margin-right: 9px; padding-top: 75px;">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body cardWrapper">
                    <div class="row">
                        <div class="col-6">
                            <h5 class="pt-2">
                                <i class="fas fa-pen-square pr-1"></i>
                                Serviço <small class="text-gray">#<?php echo $entity['id']; ?></small>
                            </h5>
                        </div>
                        <div class="col-6 text-right">
                            <button type="button" class="btn btn-primary btnRadius" 
                                title="Voltar para Serviço"
                                onclick="openServiceDetails('<?php echo $entity['id']; ?>');">
                                <i class="fas fa-arrow-left"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body cardWrapperBody">
                            <form method="post" name="formUpdateService" id="formUpdateService">
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label>Código</label>
                                            <input type="text" class="form-control" value="<?php echo $entity['id']; ?>" disabled>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label for="status">Situação</label>
                                            <select name="status" id="status_1" class="form-control">
                                                <option value="1" <?php echo ($entity['status'] == '1' ? 'selected' : ''); ?>>
                                                    1 - Ativo</option>
                                                <option value="0" <?php echo ($entity['status'] == '0' ? 'selected' : ''); ?>>
                                                    2 - Inativo</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="title">Título*</label>
                                            <input type="text" class="form-control" name="title" id="title" required
                                                value="<?php echo $entity['title']; ?>" placeholder="Título do Serviço">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="price">Valor*</label>
                                            <input type="text" class="form-control" name="price" id="price"
                                                placeholder="0,00" required
                                                value="<?php echo number_format($entity['price'], 2, ",", "."); ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="price">Tipo de Cobrança*</label>
                                            <select name="service_type" id="service_type" class="form-control" required>
                                                <option value="">Selecione</option>
                                                <option value="1" <?php echo ($entity['service_type'] == '1') ? 'selected' : ''; ?>>Valor Total</option>
                                                <option value="2" <?php echo ($entity['service_type'] == '2') ? 'selected' : ''; ?>>Valor por Hora</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-12 mt-1">
                                        <div class="row">
                                            <div class="col-md-6 offset-md-3 mb-2">
                                                <input type="hidden" name="target" value="<?php echo $this->getTarget(); ?>">
                                                <input type="hidden" name="id" value="<?php echo $entity['id']; ?>">
                                                <button type="submit" class="btn btn-success w-100 btnRadius" id="btnSubmit"
                                                    title="Salvar Serviço">
                                                    <i class="fa fa-save pr-1"></i> Salvar
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 text-center mb-3">
                    <button type="button" class="btn btn-default btn-sm btnRadius"
                        onclick="openServiceDetails('<?php echo $entity['id']; ?>');" 
                        title="Voltar para Serviço">
                        <i class="fas fa-arrow-left pr-1"></i> Voltar
                    </button>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function () {
            $("input[id=price]").maskMoney({ allowNegative: false, thousands: '.', decimal: ',', affixesStay: true });

            $('#formUpdateService').validate({
                submitHandler: async function (form) {
                    let dados = $(form).serialize();

                    $("#baseLoader").show();
                    $("#btnSubmit").attr('disabled', true);

                    await $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>servicos/processa-edicao",
                        data: dados,
                        dataType: 'json',
                        async: true
                    }).done(async function (data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        if (data.type === 'success') {
                            await openServiceDetails('<?php echo $entity['id']; ?>');
                        } else {
                            $("#baseLoader").fadeOut();
                            $("#btnSubmit").attr('disabled', false);
                        }
                    }).fail(function () {
                        showInternalErrorAlert();
                        $("#baseLoader").fadeOut();
                        $("#btnSubmit").attr('disabled', false);
                    });

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>